- ui/src/app/core-ui/linechart/labeling-tool/components/label-selection/label-selection.component.css
- ui/src/app/core-ui/linechart/labeling-tool/components/label-selection/label-selection.component.html
- ui/src/app/core-ui/linechart/labeling-tool/components/label-selection/label-selection.component.ts
- ui/src/app/core-ui/linechart/labeling-tool/components/point-selection-info/point-selection-info.component.css
- ui/src/app/core-ui/linechart/labeling-tool/components/point-selection-info/point-selection-info.component.html
- ui/src/app/core-ui/linechart/labeling-tool/components/point-selection-info/point-selection-info.component.ts
- ui/src/app/core-ui/linechart/labeling-tool/dialogs/change-chartmode/change-chartmode.dialog.css
- ui/src/app/core-ui/linechart/labeling-tool/dialogs/change-chartmode/change-chartmode.dialog.html
- ui/src/app/core-ui/linechart/labeling-tool/dialogs/change-chartmode/change-chartmode.dialog.ts
- ui/src/app/core-ui/linechart/labeling-tool/dialogs/labeling/labeling.dialog.css
- ui/src/app/core-ui/linechart/labeling-tool/dialogs/labeling/labeling.dialog.html
- ui/src/app/core-ui/linechart/labeling-tool/dialogs/labeling/labeling.dialog.ts
- ui/src/app/core-ui/linechart/labeling-tool/labeling-tool.module.ts
- ui/src/app/core-ui/linechart/labeling-tool/services/color.service.ts
- ui/src/app/core-ui/linechart/lineChart.component.html
- ui/src/app/core-ui/linechart/lineChart.component.ts
- ui/src/app/data-explorer/data-explorer.module.ts
Hi there,
I started to add a labeling tool for time series data.
The tool is fully integrated into the line chart component and can be activated via button click (custom button with 'pencil'-icon in plotly mode bar).
Features:
- marking data points of interest in line chart
- selecting appropriate label
- visualization of labeled data in line chart
Next ToDos:
- saving labels persistently (with data)
- receiving labels from the backend
Screenshots:
> Time Series Data Labeling Tool

- ui/src/app/dashboard/registry/widget-config-builder.ts
Change the default secondary text color so that it's visible from the grid.
Fixes: STREAMPIPES-172
> [STREAMPIPES-172] Set default secondary text color

- streampipes-backend/pom.xml
- streampipes-connect-container-master/pom.xml
Add all env vars from `development/env` to `pom.xml` so that Springboot can be run directly from the command line, using `mvn spring-boot:run`
Fixes: STREAMPIPES-173
> [STREAMPIPES-173] Add env vars to pom.xml

- README.md
Point broken installer links in Readme to StreamPipe Installer repo's master branch
> Fixes broken installer links

- streampipes-node-controller-container/src/main/java/org/apache/streampipes/node/controller/container/api/InvocableEntityResource.java
- streampipes-node-controller-container/src/main/java/org/apache/streampipes/node/controller/container/management/relay/DataStreamRelayManager.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/execution/http/EndpointUrlGenerator.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/execution/http/GraphSubmitter.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/execution/http/PipelineExecutor.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/execution/http/PipelineStorageService.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/ProtocolSelector.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/operations/Operations.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineWithUserResource.java
- ui/src/app/pipelines/components/pipeline-overview/pipeline-overview.component.html
- ui/src/app/pipelines/services/pipeline-operations.service.ts
Added the functionality for partial migration, meaning the migration of single pipeline elements, while the corresponding pipeline continues running.
Allows for alterations in the pipeline deployment, without requiring stopping the pipeline first, e.g., desirable if pipeline should continue running while a node undergoes maintenance.
Selectively start and stop specific pipeline elements (PEs) and datastream relays. With a focus on performance, the new PE is invoked first, then the event routing is adjusted accordingly before the original PE is detached.
Additionally, new endpoints for stopping and starting relays of PEs were added to the node controller.
-
-
> [WIP] Added functionality for (partial/selective) pipeline element migration

- streampipes-wrapper-flink/src/main/java/org/apache/streampipes/wrapper/flink/FlinkRuntime.java
If the flink job is not found, then it means that it is cancelled or failed. So streampipes should continue to stop this PE from its in-memory storage and mark the whole pipeline as Stopped.
Changed in FlinkRuntime.java. Modified method discardRuntime() to also check if the job is present and its state is running then cancel the job, else if job is present but bot running then don't throw exception. 
Also change method getJobStatus() method to return job with any status.
Fixes: https://issues.apache.org/jira/projects/STREAMPIPES/issues/STREAMPIPES-321
> [STREAMPIPES-321] Updated flinkruntime jobstatus checks to check actual running status

- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/Expressions.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/AggregationFunction.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/AndExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/AverageExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/CountExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/DistinctCountExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MaxExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MaxForeverExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MinExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MinForeverExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/OrExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/StandardDeviationExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/SumExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/UnionSetExpression.java
Fixes: https://issues.apache.org/jira/browse/STREAMPIPES-337
> [STREAMPIPES-337] Add missing functionalities for Aggregations.

- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/AggregationFunction.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/AndExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/AverageExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/DistinctCountExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MaxExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MaxForeverExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MinExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/MinForeverExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/OrExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/StandardDeviationExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/SumExpression.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/expression/aggregation/UnionSetExpression.java
> [STREAMPIPES-337] Added ASF license information

- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/SiddhiQueryBuilder.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/constants/SiddhiConstants.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/OffsetClause.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/query/SiddhiQuery.java
Fixes: https://issues.apache.org/jira/browse/STREAMPIPES-340
> [STREAMPIPES-340] Support of offset clause in Siddhi wrapper/processors

- streampipes-model/pom.xml
- streampipes-model/src/main/java/org/apache/streampipes/model/base/AbstractStreamPipesEntity.java
- streampipes-model/src/main/java/org/apache/streampipes/model/quality/EventPropertyQualityRequirement.java
- streampipes-model/src/main/java/org/apache/streampipes/model/runtime/SchemaInfo.java
- streampipes-model/src/main/java/org/apache/streampipes/model/schema/EventProperty.java
- streampipes-model/src/main/java/org/apache/streampipes/model/schema/EventSchema.java
Fixes: https://issues.apache.org/jira/browse/STREAMPIPES-323
> [STREAMPIPES-323] Implemented Merge by Schema Inbox.

- docker-compose.yml
Fixes the https://issues.apache.org/jira/browse/STREAMPIPES-351
> [STREAMPIPES-351] Remove invalid dependency entry to avoid start-up failure

- README.md
> [hotfix] Fixes broken links

- streampipes-wrapper-flink/src/main/java/org/apache/streampipes/wrapper/flink/sink/MqttFlinkProducer.java
> [hotfix] Remove unused imports

- pom.xml
- streampipes-wrapper-flink/pom.xml
> [STREAMPIPES-389] upgrade flink to 1.13

- streampipes-commons/src/main/java/org/apache/streampipes/commons/MD5.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/Utils.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/execution/http/PipelineExecutor.java
- streampipes-wrapper-flink/pom.xml
- streampipes-wrapper-flink/src/main/java/org/apache/streampipes/wrapper/flink/FlinkRuntime.java
1. custom flink rest port from configuration for version 1.13
2. Make kafka consumer group id fixed for pipeline action and sepas
> flink 1.13 rest port config & Keep kafka consumer group for Pipeline action and sepas

- ui/src/app/data-explorer/components/designer-panel/visualisation-settings/data-explorer-visualisation-settings.component.html
- ui/src/app/data-explorer/components/widgets/map/config/map-widget-config.component.html
- ui/src/app/data-explorer/components/widgets/map/config/map-widget-config.component.scss
- ui/src/app/data-explorer/components/widgets/map/config/map-widget-config.component.ts
- ui/src/app/data-explorer/components/widgets/map/map-widget.component.html
- ui/src/app/data-explorer/components/widgets/map/map-widget.component.scss
- ui/src/app/data-explorer/components/widgets/map/map-widget.component.ts
- ui/src/app/data-explorer/components/widgets/map/model/map-widget.model.ts
- ui/src/app/data-explorer/data-explorer.module.ts
- ui/src/app/data-explorer/registry/data-explorer-widgets.ts
Added a map widget to the data-explorer to visualize gathered geo data.
Added the map widget in accordance to the established structure.
> added map widget to data-explorer

- ui/nginx_config/default.conf
"HTTP Server" adapter endpoints will be accessible over the ui container as described in the configuration wizard.
Update proxy configuration
Fixes:  https://issues.apache.org/jira/browse/STREAMPIPES-440
> Provide "HTTP Server" adapter endpoints

- ui/src/app/data-explorer/components/widgets/time-series-chart/time-series-chart-widget.component.ts
A user should be able to use the existing grouping option for time series charts in the data-explorer.
> [STREAMPIPES-459] Enable grouping for time series charts in data-explorer

- .github/workflows/cypress-test.yml
- streampipes-client/pom.xml
- streampipes-client/src/main/java/org/apache/streampipes/client/api/FileApi.java
- streampipes-client/src/main/java/org/apache/streampipes/client/http/HttpRequest.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/utils/FileProtocolUtils.java
> Streampipes 482

- installer/cli/deploy/standalone/extensions-all-jvm/docker-compose.dev.yml
- installer/cli/deploy/standalone/pipeline-elements-all-flink/docker-compose.dev.yml
- installer/cli/deploy/standalone/pipeline-elements-all-jvm/docker-compose.dev.yml
- installer/cli/deploy/standalone/sources-vehicle-simulator/docker-compose.dev.yml
- installer/cli/deploy/standalone/sources-watertank-simulator/docker-compose.dev.yml
- installer/cli/deploy/standalone/taskmanager/docker-compose.dev.yml
- installer/cli/deploy/standalone/ui/docker-compose.dev.yml
Fixes:  https://issues.apache.org/jira/browse/STREAMPIPES-515
> [STREAMPIPES-515] Add label to dev docker-compose services

- ui/package.json
Fix dependabot vulnerability
Fixes: [STREAMPIPES-519]
> Update lodash version

- streampipes-extensions/pom.xml
> [STREAMPIPES-519] upgrade nimbus-jose-jwt due to cve

- streampipes-extensions/pom.xml
- streampipes-extensions/streampipes-sources-watertank-simulator/pom.xml
> [STREAMPIPES-519] upgrade proton-j due to CVE

- installer/k8s/templates/core/ui-ingress.yaml
Resolves issue reported here: https://issues.apache.org/jira/browse/STREAMPIPES-532
> #STREAMPIPES-532 Fixed k8s errors due to outdated spec

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataLakeManagementV4.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/v4/query/DataExplorerQueryV4.java
- streampipes-model/src/main/java/org/apache/streampipes/model/datalake/SpQueryResult.java
- streampipes-platform-services/src/main/java/org/apache/streampipes/ps/DataLakeResourceV4.java
- ui/projects/streampipes/platform-services/src/lib/apis/datalake-rest.service.ts
- ui/projects/streampipes/platform-services/src/lib/model/datalake/DatalakeQueryParameters.ts
- ui/projects/streampipes/platform-services/src/lib/model/gen/streampipes-model.ts
- ui/src/app/dashboard/components/grid/dashboard-grid.component.html
- ui/src/app/dashboard/components/grid/dashboard-grid.component.ts
- ui/src/app/dashboard/components/overview/dashboard-overview.component.ts
- ui/src/app/dashboard/components/panel/dashboard-panel.component.html
- ui/src/app/dashboard/components/panel/dashboard-panel.component.ts
- ui/src/app/dashboard/components/widget/dashboard-widget.component.html
- ui/src/app/dashboard/components/widget/dashboard-widget.component.ts
- ui/src/app/dashboard/components/widgets/base/base-widget.ts
- ui/src/app/dashboard/dialogs/edit-dashboard/edit-dashboard-dialog.component.html
> Streampipes 579

- pom.xml
- streampipes-extensions/pom.xml
Upgrade pulsar version to 2.10.1.
> Upgrade pulsar version to 2.10.1

- streampipes-maven-plugin/pom.xml
https://github.com/advisories/GHSA-c4r9-r8fh-9vj2
> [STREAMPIPES-519] update snakeyaml due to CVEs

- streampipes-data-explorer-commons/src/main/java/org/apache/streampipes/dataexplorer/commons/influx/InfluxStore.java
- streampipes-model/src/main/java/org/apache/streampipes/model/runtime/Event.java
- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/routing/StandaloneSpInputCollector.java
- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/runtime/StandaloneEventProcessorRuntime.java
- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/runtime/StandaloneEventSinkRuntime.java
- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/runtime/StandaloneExternalEventProcessorRuntime.java
- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/runtime/StandaloneExternalEventSinkRuntime.java
- streampipes-wrapper/src/main/java/org/apache/streampipes/wrapper/routing/RawDataProcessor.java
Fix STREAMPIPES-585
No incomplete events are written to the internal time-series storage.
Further, exception handling is added for runtime exceptions within processing elements and sinks
> Streampipes 585

- ui/src/app/assets/components/asset-overview/asset-overview.component.html
- ui/src/app/assets/dialog/create-asset/create-asset-dialog.component.html
Fix some small bugs in the asset model
> fix labels and tool tip in asset view

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/pulsar/PulsarProtocol.java
Currently, we are using the pulsar consumer to fetch messages in the pulsar adapter. This will create some redundant subscriptions in the pulsar broker. It's better to use the Pulsar reader to fetch small amounts of messages. 
* Use Pulsar reader to fetch messages
* Use a more robust style to read messages instead of using `thread.sleep`
> Use the Pulsar reader to fetch messages in Pulsar adapter

- streampipes-connect/src/main/java/org/apache/streampipes/connect/adapter/Adapter.java
- streampipes-connect/src/main/java/org/apache/streampipes/connect/adapter/AdapterPipelineGenerator.java
- streampipes-connect/src/main/java/org/apache/streampipes/connect/adapter/preprocessing/elements/DebugAdapterSink.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/pulsar/PulsarConsumer.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/pulsar/PulsarProtocol.java
- streampipes-integration-tests/src/test/java/org/apache/streampipes/integration/adapters/AdapterTesterBase.java
- streampipes-integration-tests/src/test/java/org/apache/streampipes/integration/adapters/PulsarAdapterTester.java
- streampipes-integration-tests/src/test/java/org/apache/streampipes/integration/containers/PulsarContainer.java
- streampipes-integration-tests/src/test/java/org/apache/streampipes/integration/containers/PulsarDevContainer.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/grounding/ProtocolDescription.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/rules/DebugSinkRuleDescription.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/rules/TransformationRuleDescription.java
- streampipes-model/src/main/java/org/apache/streampipes/model/staticproperty/FreeTextStaticProperty.java
Improve the integration test framework
* Refine the interface of `AdapterTesterBase`
* Use the low level approach to start and stop the adapter
* Add `DebugAdapterSInk` to collect the data for verification
* Improve the pulsar adapter integration tests
> Improve the integration test framework

- ui/package.json
While setting up the ui an out of memory error occurred. This small change prevents this.
Increasing the memory limit
> Fix package.json to prevent out of memory error

- streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/FiltersJvmInit.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/movingaverage/MovingAverageProcessor.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/movingaverage/util/MovingAverageFilter.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/movingaverage/util/MovingFilter.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/movingaverage/util/MovingMedianFilter.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/main/resources/org.apache.streampipes.processors.filters.jvm.movingaverage/documentation.md
- streampipes-extensions/streampipes-processors-filters-jvm/src/main/resources/org.apache.streampipes.processors.filters.jvm.movingaverage/strings.en
A new data processor has been added. The Moving Average Filter is used to smooth the data of a data stream.
> Add new Moving Average Processor

- streampipes-backend/src/main/resources/openapi.yaml
- ui/src/app/profile/components/token/token-management-settings.component.html
- ui/src/app/profile/profile.component.html
- ui/src/app/profile/profile.module.ts
Make API Docs available for logged-in StreamPipes user.
Add section to view API docs within the user's profile menu
Fixes: STREAMPIPES-617
> [STREAMPIPES-617] add acces to API docs in Profile menu

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineResource.java
A new enpoint to get the user pipelines is added to simplify the Python Client API.
Fixes: [STREAMPIPES-633]
> [STREAMPIPES-633] Add new default get method to PipelineResource

- installer/cli/deploy/standalone/rocketmq/Dockerfile
- installer/cli/deploy/standalone/rocketmq/docker-compose.dev.yml
- installer/cli/deploy/standalone/rocketmq/docker-compose.yml
Provide RocketMQ 5.0.0 `Dockerfile` and `docker-compose.yml` files
> STREAMPIPES-640: Provide RocketMQ 5.0.0 Dockerfile and docker-compose.yml files

- pom.xml
This PR fixes failing powermock tests when compiling with Java 17+.
I will create a separate ticket to remove Powermock in the first release after 0.90.0
> [STREAMPIPES-591] Prevent tests from failing with Java 17+

- README.md
- installer/README.md
- installer/cli/README.md
- streampipes-client-python/README.md
- streampipes-client-python/docs/getting-started/quickstart.md
- streampipes-extensions/README.md
- streampipes-wrapper-python/README.md
- ui/src/app/info/about/about.component.html
Update docs to remove incubator status.
> hotfix: update docs to remove incubator status

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/DataStreamResource.java
Harmonize the API to read data streams.
Fixes: [STREAMPIPES-649]
> [STREAMPIPES-649] Update REST API for data streams

- .asf.yaml
Currently, the Github discussion doesn't seem to be synced to the dev mailing list. Let's make it also happen in the mailing list.
> Let discussions also happen in the dev mailing list

- installer/cli/.env
- installer/cli/environments/backend-nats
- installer/cli/environments/basic-nats
- installer/cli/environments/pipeline-element-nats
- installer/compose/README.md
- installer/compose/docker-compose.nats.yml
Adds a new docker-compose file and CLI environments for using StreamPipes with Nats as internal broker instead of Kafka/Zookeeper.
Fixes: <GitHub issue link>
> Add docker-compose and CLI environments for Nats messaging option (#818)

- ui/src/app/data-explorer/components/designer-panel/data-settings/field-selection-panel/field-selection-panel.component.ts
This PR sorts all fields that are displayed in the data explorer's field selection, filter and group by panels by name for better discoverability.
Fixes: <GitHub issue link>
> Always sort data explorer fields by name (#817)

- streampipes-backend/src/main/java/org/apache/streampipes/backend/migrations/v090/UpdateUsernameViewMigration.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/setup/CouchDbInstallationStep.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/setup/design/DesignDocumentUtils.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/setup/design/UserDesignDocument.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/UserResource.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/UserStorage.java
> Ignore case when fetching users from database (#822)

- archetypes/streampipes-archetype-extensions-jvm/pom.xml
- pom.xml
Enable checkstyle for streampipes-archetype-extensions-jvm
Fixes: #830
> 830-streampipes-archetype-extensions-jvm

- archetypes/streampipes-archetype-pe-processors-flink/pom.xml
enable checkstyle for streampipes-archetype-pe-processors-flink
Fixes: #833
> 833-streampipes-archetype-pe-processors-flink

- streampipes-commons/pom.xml
- streampipes-commons/src/main/java/org/apache/streampipes/commons/MD5.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/exceptions/ElementNotFoundException.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/exceptions/RemoteServerNotAccessibleException.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/exceptions/SpConfigurationException.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/exceptions/SpException.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/exceptions/SpRuntimeException.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/exceptions/TooManyEdgesException.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/exceptions/UserNotFoundException.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/exceptions/UsernameAlreadyTakenException.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/networking/Networking.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/zip/ZipFileExtractor.java
enable checkstyle for streampipes-commons
Fixes: #834
> 834-streampipes-commons

- streampipes-container-extensions/pom.xml
- streampipes-container-extensions/src/main/java/org/apache/streampipes/container/extensions/ExtensionsModelSubmitter.java
- streampipes-container-extensions/src/main/java/org/apache/streampipes/container/extensions/ExtensionsResourceConfig.java
- streampipes-container-extensions/src/main/java/org/apache/streampipes/container/extensions/function/FunctionDeregistrationHandler.java
- streampipes-container-extensions/src/main/java/org/apache/streampipes/container/extensions/function/FunctionRegistrationHandler.java
- streampipes-container-extensions/src/main/java/org/apache/streampipes/container/extensions/function/RegistrationHandler.java
enable checkstyle for streampipes-container-extensions
Fixes: <GitHub issue link>
#838
> 838-streampipes-container-extensions

- archetypes/streampipes-archetype-pe-sinks-flink/pom.xml
enable checkstyle for streampipes-archetype-pe-sinks-flink
Fixes: #832
> 832-streampipes-archetype-pe-sinks-flink

- .github/PULL_REQUEST_TEMPLATE.md
Update and simplify the template for PRs
> [#808] simplify & update PR template

- .github/release.yml
Create config file for custom release notes automatically created by GitHub
Fixes: #805
> [#805] create custom release notes configuration

- streampipes-service-base/pom.xml
- streampipes-service-base/src/main/java/org/apache/streampipes/service/base/BaseNetworkingConfig.java
- streampipes-service-base/src/main/java/org/apache/streampipes/service/base/StreamPipesServiceBase.java
- streampipes-service-base/src/main/java/org/apache/streampipes/service/base/rest/BaseResourceConfig.java
- streampipes-service-base/src/main/java/org/apache/streampipes/service/base/security/UnauthorizedRequestEntryPoint.java
- streampipes-service-base/src/main/resources/logback-spring.xml
- streampipes-service-discovery-api/pom.xml
- streampipes-service-discovery-api/src/main/java/org/apache/streampipes/svcdiscovery/api/ISpServiceDiscovery.java
- streampipes-service-discovery-api/src/main/java/org/apache/streampipes/svcdiscovery/api/SpConfig.java
- streampipes-service-discovery-api/src/main/java/org/apache/streampipes/svcdiscovery/api/model/ConfigItem.java
- streampipes-service-discovery-api/src/main/java/org/apache/streampipes/svcdiscovery/api/model/DefaultSpServiceTags.java
- streampipes-service-discovery-api/src/main/java/org/apache/streampipes/svcdiscovery/api/model/PeConfig.java
- streampipes-service-discovery-api/src/main/java/org/apache/streampipes/svcdiscovery/api/model/SpServiceRegistrationRequest.java
- streampipes-service-discovery-api/src/main/java/org/apache/streampipes/svcdiscovery/api/model/SpServiceTag.java
- streampipes-service-discovery-api/src/main/java/org/apache/streampipes/svcdiscovery/api/model/SpServiceUrlProvider.java
- streampipes-service-discovery-consul/pom.xml
- streampipes-service-discovery-consul/src/main/java/org/apache/streampipes/svcdiscovery/consul/ConsulHealthServiceManager.java
- streampipes-service-discovery-consul/src/main/java/org/apache/streampipes/svcdiscovery/consul/ConsulProvider.java
- streampipes-service-discovery-consul/src/main/java/org/apache/streampipes/svcdiscovery/consul/ConsulSpConfig.java
- streampipes-service-discovery-consul/src/main/java/org/apache/streampipes/svcdiscovery/consul/SpConsulKvManagement.java
- streampipes-service-discovery-consul/src/main/java/org/apache/streampipes/svcdiscovery/consul/SpConsulServiceDiscovery.java
- streampipes-service-discovery/pom.xml
- streampipes-service-discovery/src/main/java/org/apache/streampipes/svcdiscovery/SpServiceDiscovery.java
- streampipes-service-extensions-base/pom.xml
- streampipes-service-extensions-base/src/main/java/org/apache/streampipes/service/extensions/base/StreamPipesExtensionsServiceBase.java
- streampipes-service-extensions-base/src/main/java/org/apache/streampipes/service/extensions/base/WebSecurityConfig.java
- streampipes-service-extensions-base/src/main/java/org/apache/streampipes/service/extensions/base/client/StreamPipesClientRuntimeConnectionResolver.java
- streampipes-service-extensions-base/src/main/java/org/apache/streampipes/service/extensions/base/security/TokenAuthenticationFilter.java
- streampipes-service-extensions-base/src/main/java/org/apache/streampipes/service/extensions/base/security/UnauthenticatedInterfaces.java
adds checkstyle configuration to streampipes-service-* modules
> add-checkstyle-streampipes-service

- archetypes/streampipes-archetype-extensions-jvm/pom.xml
- archetypes/streampipes-archetype-pe-processors-flink/pom.xml
- archetypes/streampipes-archetype-pe-sinks-flink/pom.xml
- pom.xml
- streampipes-container-extensions/pom.xml
- streampipes-integration-tests/pom.xml
- streampipes-messaging-jms/pom.xml
- streampipes-messaging-kafka/pom.xml
- streampipes-messaging-mqtt/pom.xml
- streampipes-messaging-nats/pom.xml
- streampipes-messaging/pom.xml
- streampipes-rest/pom.xml
- streampipes-service-base/pom.xml
- streampipes-service-discovery-api/pom.xml
- streampipes-service-discovery-consul/pom.xml
- streampipes-service-discovery/pom.xml
- streampipes-service-extensions-base/pom.xml
> Simplify checkstyle configuration

- streampipes-dataformat-cbor/pom.xml
- streampipes-dataformat-cbor/src/main/java/org/apache/streampipes/dataformat/cbor/CborDataFormatDefinition.java
- streampipes-dataformat-fst/pom.xml
- streampipes-dataformat-fst/src/main/java/org/apache/streampipes/dataformat/fst/FstDataFormatDefinition.java
- streampipes-dataformat-json/pom.xml
- streampipes-dataformat-json/src/main/java/org/apache/streampipes/dataformat/json/JsonDataFormatDefinition.java
- streampipes-dataformat-smile/pom.xml
- streampipes-dataformat-smile/src/main/java/org/apache/streampipes/dataformat/smile/SmileDataFormatDefinition.java
- streampipes-dataformat/pom.xml
- streampipes-dataformat/src/main/java/org/apache/streampipes/dataformat/SpDataFormatManager.java
> [#820] Enable checkstyle for streampipes-dataformat-*

- README.md
Adding mailto attribute to the mailing link "dev-subscribe@streampipes.apache.org"
After adding changes, the mailing link successfully shows the pop-up for "Open Mail" upon clicking it.
Screenshot: Clicking the link.
Screenshot: Clicking on "Open Mail"
> [#878] Add mailto link to README.md

- .github/dependabot.yml
Extend the dependabot config with setting for maven and pip
> add maven and pip to denpendabot config

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/doc_website_issue_report.yml
- .github/ISSUE_TEMPLATE/maintainer_fast_track.yml
This pull request is related to issue #858. 
I replaced the checkboxes with dropdown menus as suggested in issue #858.
> Replaced checkboxes with dropdown menus

- .github/release.yml
Extend release notes by a section providing information about dependency updates.
> add section about dependency updates to release notes

- pom.xml
> [#959] Update siddhi version from 5.1.21 to 5.1.26

- .github/workflows/pr-validation.yml
Extend the covered OS for the Python client by Windows.
> extend python unit tests to Windows

- pom.xml
This PR removes the maven profile `java8-doclint-disabled` which has no usage anywhere.
> remove outdated maven profile

- ui/.eslintignore
- ui/.prettierignore
- ui/src/app/profile/components/basic-profile-settings.ts
- ui/src/app/profile/components/general/general-profile-settings.component.html
- ui/src/app/profile/components/general/general-profile-settings.component.scss
- ui/src/app/profile/components/general/general-profile-settings.component.ts
- ui/src/app/profile/components/token/token-management-settings.component.html
- ui/src/app/profile/components/token/token-management-settings.component.scss
- ui/src/app/profile/components/token/token-management-settings.component.ts
- ui/src/app/profile/dialog/change-email/change-email-dialog.component.html
- ui/src/app/profile/dialog/change-email/change-email-dialog.component.scss
- ui/src/app/profile/dialog/change-email/change-email-dialog.component.ts
- ui/src/app/profile/dialog/change-password/change-password-dialog.component.html
- ui/src/app/profile/dialog/change-password/change-password-dialog.component.scss
- ui/src/app/profile/dialog/change-password/change-password-dialog.component.ts
- ui/src/app/profile/profile.component.html
- ui/src/app/profile/profile.component.scss
- ui/src/app/profile/profile.component.ts
- ui/src/app/profile/profile.module.ts
- ui/src/app/profile/profile.service.ts
Apply formatting and linting to `profile` module
> [#877] apply formatting and linting to profile module

- streampipes-client-python/setup.py
Provide some more metadata published along the python client for better appearance and detectability in PyPi.
> Extend metadata for python client publishing

- .github/release.yml
Use the proper comment syntax for YAML
> [hotfix] fix header style in release.yaml

- pom.xml
The purpose of this PR is to upgrade Siddhi dependency version to v5.1.27. This version should work with ANTLR runtime version 4.11.1.
> Upgrade Siddhi version to v5.1.27

- pom.xml
- streampipes-maven-plugin/pom.xml
Update maven version (see PR #996)
> [hotfux] Update maven version to 3.8.7

- docker-compose.yml
> [hotfix] Remove incubator from docker-compose in route directory

- ui/cypress/support/general/login.ts
- ui/package-lock.json
- ui/package.json
Closes https://github.com/apache/streampipes/pull/951
> chore: Bump @auth0/angular-jwt from 5.0.2 to 5.1.2 in /ui

- ui/cypress/tests/apiDocumentation/apiDocumentation.smoke.spec.ts
- ui/src/app/login/components/auth-box/auth-box.component.html
> test: [#955] Add cypress test for api docs

- .github/dependabot.yml
Reduce the possible amount of dependabot PRs per dependency files to not get overwhelmed by dependabot PRs.
> restrict appearance of dependabot PRs

- ui/.eslintignore
- ui/.prettierignore
- ui/src/app/core/components/breadcrumb/breadcrumb.component.html
- ui/src/app/core/components/breadcrumb/breadcrumb.component.scss
- ui/src/app/core/components/breadcrumb/breadcrumb.component.ts
- ui/src/app/core/components/iconbar/iconbar.component.html
- ui/src/app/core/components/iconbar/iconbar.component.scss
- ui/src/app/core/components/iconbar/iconbar.component.ts
- ui/src/app/core/components/streampipes/streampipes.component.html
- ui/src/app/core/components/streampipes/streampipes.component.scss
- ui/src/app/core/components/streampipes/streampipes.component.ts
- ui/src/app/core/components/toolbar/toolbar.component.html
- ui/src/app/core/components/toolbar/toolbar.component.scss
- ui/src/app/core/components/toolbar/toolbar.component.ts
- ui/src/app/core/core.module.ts
Applying UI linting and formatting to the `core` module. Removing the `core` module from `ui/.eslintignore` and `ui/.prettierignore` and fixing formatting and lining.
Fix unused imports in `ui\src\app\core\components\iconbar\iconbar.component.ts`
> [#877] Format and lint core module

- streampipes-client-python/mkdocs.yml
> [hotfix] add stream example to Mkdocs

- .github/workflows/pr-validation.yml
- streampipes-client-python/setup.py
- streampipes-client-python/streampipes_client/client/client.py
- pins dependecies required for development and docs to have a reliable and reproducible environment for linting tools etc. Notifcations about new versions are delivered by @dependabot
- add workflow for checking documentation
> chore: adapt setup of python dependencies

- streampipes-extensions-api/src/main/java/org/apache/streampipes/extensions/api/connect/IAdapter.java
- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/Adapter.java
- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/generic/GenericAdapter.java
- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/generic/GenericDataSetAdapter.java
- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/generic/GenericDataStreamAdapter.java
- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/specific/SpecificAdapter.java
- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/specific/SpecificDataSetAdapter.java
- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/model/specific/SpecificDataStreamAdapter.java
This pr removes the method `isDebug()` from the interface `IAdapter` and all its implementations.
> [hotfix] Remove `isDebug` method from interface `IAdapter`

- .asf.yaml
Better organize mail on the mailing lists by rewriting mail subjects of GitHub mails.
> Update GitHub notification settings (#1162)

- streampipes-client-python/Makefile
- streampipes-client-python/setup.py
Rename the package name of the python client to `streampipes-client`
PR introduces (a) breaking change(s): no (not yet)
PR introduces (a) deprecation(s): no (not yet)
> [#792] rename python client to `streampipes-client`

- .github/dependabot.yml
> [#1197] add github-actions to denpendabot config

- .github/pr-labeler-config.yml
- .github/workflows/pr-labeler.yml
Improve setup of PR labeling workflow
Add config for label `helm`
> chore(gh-actions): improve pr labeling workflow

- .github/dependabot.yml
Configure @dependabot to use custom labels for GitHub actions
> chore(gh-actions): configure custom label for GitHub actions

- .asf.yaml
Add some basic branch protection rules as discussed in #882.
I refrained from requiring successful validation checks at this point in time since we need to streamline our test setup first.
> chore(asf-yaml): add basic branch protection setup

- streampipes-client-python/README.md
- streampipes-client-python/docs/examples/1-introduction-to-streampipes-python-client.ipynb
- streampipes-client-python/docs/examples/2-extracting-data-from-the-streampipes-data-lake.ipynb
- streampipes-client-python/docs/examples/3-getting-live-data-from-the-streampipes-data-stream.ipynb
- streampipes-client-python/docs/examples/4-using-online-machine-learning-on-a-streampipes-data-stream.ipynb
- streampipes-client-python/docs/getting-started/installation.md
- streampipes-client-python/setup.py
- streampipes-client-python/streampipes/__version__.py
> chore(naming): fix some references to `streampipes_client`

- streampipes-data-export/src/main/java/org/apache/streampipes/export/resolver/AbstractResolver.java
- streampipes-data-export/src/main/java/org/apache/streampipes/export/resolver/AdapterResolver.java
- streampipes-data-export/src/main/java/org/apache/streampipes/export/resolver/DataSourceResolver.java
- streampipes-data-export/src/main/java/org/apache/streampipes/export/resolver/PipelineResolver.java
- streampipes-data-export/src/main/java/org/apache/streampipes/export/utils/EventGroundingProcessor.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/execution/provider/StoredPipelineElementProvider.java
When using the Data Import feature, broker settings are only overridden if the original and configured protocol are of the same class. In case of importing e.g., resources using a NatsTransportProtocol into an instance that uses Kafka, protocol settings should be replaced.
> Properly override messaging protocol when importing resources (#1274)

- streampipes-client-python/mkdocs.yml
Prevent mkdocs from loading gfonts which violates ASF policy
> fix(python-docs): prevent mkdocs from loading gfonts

- streampipes-client-python/streampipes/model/common.py
- streampipes-client-python/streampipes/model/resource/data_stream.py
- streampipes-client-python/tests/client/test_endpoint.py
- streampipes-client-python/tests/model/__init__.py
- streampipes-client-python/tests/model/resource/__init__.py
- streampipes-client-python/tests/model/resource/test_data_stream.py
…nding
Provides an ugly workaround for #1245
This is only introduced to keep the compatibility of the Python library with the Kafka broker.
Should be removed as soon as possible.
> [#1245] provide a temporary workaround for inconsistency in eventGrounding

- .github/workflows/pypi-deployment.yml
This PR adds a new GitHub workflow to publish the Python library to PyPi.
> Add workflow to deploy Python library to PyPi (#1230)

- streampipes-client-python/README.md
- streampipes-client-python/docs/examples/3-getting-live-data-from-the-streampipes-data-stream.ipynb
- streampipes-client-python/docs/examples/4-using-online-machine-learning-on-a-streampipes-data-stream.ipynb
- streampipes-client-python/docs/getting-started/quickstart.md
- streampipes-client-python/docs/index.md
- streampipes-client-python/mkdocs.yml
Update minor aspects of the Python docs
> chore: improve python docs and fix some minor inconsistencies

- streampipes-extensions-management/pom.xml
> [#1293] remove extentions management module name from its pom

- ui/src/app/info/about/about.component.html
Extend support section in `About` view in the `info` module of the StreamPipes UI with additional references.
> chore(ui): provide some more references for support in the 'about' view

- streampipes-client-python/streampipes/function_zoo/river_function.py
- streampipes-client-python/streampipes/functions/utils/data_stream_generator.py
- streampipes-client-python/streampipes/model/common.py
- streampipes-client-python/streampipes/model/resource/data_stream.py
> Update data stream generator (#1258)

- ui/README.md
Extend available information about UI development.
> chore(docs): add information on how to develop the UI locally

- streampipes-client/src/main/java/org/apache/streampipes/client/api/DataProcessorApi.java
- streampipes-client/src/main/java/org/apache/streampipes/client/api/DataSinkApi.java
- streampipes-client/src/main/java/org/apache/streampipes/client/api/DataStreamApi.java
- streampipes-client/src/main/java/org/apache/streampipes/client/api/PipelineApi.java
- streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/AbstractPipelineElementResourceManager.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/DataProcessorResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/DataSinkResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/DataStreamResource.java
- ui/projects/streampipes/platform-services/src/lib/apis/pipeline-element.service.ts
- ui/projects/streampipes/platform-services/src/lib/apis/pipeline.service.ts
- ui/src/app/assets/dialog/base-asset-links.directive.ts
- ui/src/app/home/components/status.component.ts
- ui/src/app/notifications/notifications.component.ts
- ui/src/app/pipelines/pipelines.component.ts
> Rename endpoint to fetch all pipelines from API (#1333)

- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/pom.xml
- archetypes/streampipes-archetype-pe-processors-flink/src/main/resources/archetype-resources/pom.xml
- archetypes/streampipes-archetype-pe-sinks-flink/src/main/resources/archetype-resources/pom.xml
- installer/cli/.env
- installer/cli/README.md
- installer/compose/.env
- installer/compose/README.md
- installer/k8s/Chart.yaml
- installer/k8s/README.md
- installer/k8s/values.yaml
- ui/package-lock.json
- ui/package.json
We have upgraded the project version to `0.92.0-SNAPSHOT` in these commit: https://github.com/apache/streampipes/commit/7b3872b84ce332f525e37fb93f0dfcc59535dcca and https://github.com/apache/streampipes/commit/83a5a0c4ebd3074db2bce71bc8f7e6e485845166
There are still some places that haven't been upgraded. This PR updates all version to `0.92.0-SNAPSHOT`
> Update all version to 0.92.0-SNAPSHOT

- streampipes-model/src/main/java/org/apache/streampipes/model/datalake/DataSeries.java
- streampipes-model/src/main/java/org/apache/streampipes/model/datalake/DataSeriesBuilder.java
- streampipes-model/src/main/java/org/apache/streampipes/model/datalake/SpQueryResultBuilder.java
- streampipes-model/src/test/java/org/apache/streampipes/model/datalake/DataSeriesBuilderTest.java
- streampipes-model/src/test/java/org/apache/streampipes/model/datalake/SpQueryResultBuilderTest.java
> [#1336] Add a builder to create SpQueryResult objects

- ui/src/app/profile/components/token/token-management-settings.component.html
- ui/src/app/profile/components/token/token-management-settings.component.scss
- ui/src/app/profile/components/token/token-management-settings.component.ts
This PR resolves issue #793 "Empty string as API token name" by adding a validator to the token name input field that requires it to be at least 3 characters long and contain only alphanumeric characters, hyphens, or underscores. It also includes a form control and error messages for each validator.
To ensure the form is valid, the "Create new API key" button is disabled until the input field is valid. Additionally, the mt-5 class has been used to add a 5 px top margin to the button.
A gif demonstrating the input validation has been added for reference.
Please review the changes and provide feedback or suggestions if there are any further changes I should make.
> feat: Add input validation for API token name (#793)

- streampipes-data-explorer-commons/src/main/java/org/apache/streampipes/dataexplorer/commons/influx/InfluxStore.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/helpers/EpProperties.java
- ui/src/app/data-explorer/components/widgets/base/base-widget-config.ts
- ui/src/app/data-explorer/services/data-explorer-field-provider-service.ts
This fixes #1291.
**Root cause:**  
`InfluxStore` can not correctly storage `EventPropertyPrimitive` with `runtimeType = SO.NUMBER` as a number field in InfluxDB. 
A `EventPropertyPrimitive` with `runtimeType = SO.NUMBER` is stored directly as a `string` type field, which can not be used in some aggregation functions such as `mean`.
Actually, I have checked three possible points which may cause the issue:
1. Processor: wrong output field types of `MathOpProcessor `
2. DataLake: `InfluxStore` converts some field data types before insertion
3. Frontend: wrong number field selection logic in `FieldSelectionPanelComponent`
The check results:
1. fine
2. root cause
3. may have a potential issue: fields with type of `XSD.LONG` may not be shown by the panel. I fixed it.
The field type of …
> [#1291] Can't aggregate calculation results of the Math processing element

- .github/workflows/build.yml
- .github/workflows/cypress-test.yml
- .github/workflows/pr-validation.yml
- .github/workflows/pypi-deployment.yml
- .github/workflows/python-docs.yml
Streamline and simplify usage of caching in our Github workflows.
> chore(ci): improve caching for dependencies in pr-validation workflow

- streampipes-client-python/setup.py
Reify URL provided in package metadata to our Python README on Github.
> chore: reify project url in package metadata

- create-client-model.sh
- streampipes-model/src/main/java/org/apache/streampipes/model/datalake/PageResult.java
This pull request modifies an existing Bash script by adding the Apache license header to the generated TypeScript files `streampipes-model` and `streampipes-model-client`.
> Improve create client model script

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/v4/params/WhereStatementParams.java
- ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.ts
- ui/src/app/data-explorer/components/widgets/base/base-data-explorer-widget.directive.ts
- ui/src/app/data-explorer/components/widgets/table/table-widget.component.html
- ui/src/app/data-explorer/components/widgets/table/table-widget.component.ts
- ui/src/app/data-explorer/components/widgets/time-series-chart/time-series-chart-widget.component.ts
* Quick-fix bug that occurred when filtering for booleans with value `false` in the data explorer
* Add pagination to table widget in data explorer to improve performance
* Add some minor improvements to the  time series widget
> 1391 data explorer filter doesnt work for boolean and false value

- .github/release.yml
> #1261 Modified release.yml file to include Python changes to release notes

- streampipes-client-python/docs/overrides/partials/integrations/analytics/matomo.html
- streampipes-client-python/mkdocs.yml
Add the matomo tracking script provided by the ASF to the Python docs as well.
See instructions of Mkdocs: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#custom-site-feedback
> docs: add matomo tracking to python docs

- streampipes-client-python/mkdocs.yml
Add a search bar to the Python docs that allows users to search the documents
> Add search bar for Python docs

- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/Init.java
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__DataProcessor.java
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__DataSink.java
update archetypes template to make the generated code conform to checkstyle，hoping makes sense.
> update archetypes template

- ui/src/app/dashboard/components/widgets/raw/raw-config.ts
> Fix repeated past data

- pom.xml
- streampipes-service-core/pom.xml
Bump Spring version to 6.0.7 and Spring Boot to 3.0.5
> Dependabot/maven/org.springframework spring core 6.0.7

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/influx/DataExplorerInfluxQueryExecutor.java
> Provide database name in query object (#1479)

- ui/cypress/support/utils/PrepareTestDataUtils.ts
- ui/cypress/tests/datalake/configuration.smoke.spec.ts
> [#1289] Fix cypress test for data lake configuration

- streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/kafka/KafkaPublishSink.java
- streampipes-messaging-kafka/src/main/java/org/apache/streampipes/messaging/kafka/SpKafkaProducer.java
> Refactor method name in Kafka messaging layer

- streampipes-data-export/src/main/java/org/apache/streampipes/export/resolver/PipelineResolver.java
> [SP-1504] Do not remove streams on pipeline export

- .github/workflows/python-docs.yml
Since we released the first actual version of StreamPipes Python (`0.91.0`), the regular workflow creating the docs for the current development state shouldn't use the `latest` alias anymore.
Therefore, we adapt the corresponding `mike` commands and update the workflow accordingly.
From now on the workflow should only update the version `dev` of the Python documentation.
> [hotfix] remove latest alias for dev python docs

- .github/workflows/stale-bot.yml
This PR introduces a GitHub workflow that marks PRs after 21 days without any update as stale.
After another 7 days the PR is closed but the branch is preserved so that one can come up with the PR at any time again.
> feature: add workflow that stales PRs

- ui/src/app/connect/dialog/edit-event-property/components/edit-schema-transformation/edit-schema-transformation.component.html
Fixes for #1199 with below proposed changes
* Pop up a tooltip (with full term value) while hovering on dropdown value.
* Increased dropdown width from 300px to 400px.
Please find the proposed fixes layout in below image
> [#1199] Semantic type Dropdown Fixes for showing full term

- .github/workflows/osv-scanner.yml
Improve OSV scanner workflow:
* add header to VULNERABILITY.file
* update PR title and commit message
* refine reviewers
> chore: add header to file & refine reviewers

- .github/workflows/python-docs.yml
Exclude the `versions.json` file when updatig the current development docs of Python because this would overwrite the existing versions and aliases.
> [hotfix] exclude versions file from pydocs update

- streampipes-mail/src/main/java/org/apache/streampipes/mail/template/AccountActiviationMailTemplate.java
- streampipes-mail/src/main/java/org/apache/streampipes/mail/template/part/LogoPart.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/UserResource.java
Fix the logo URL of email templates
> Fix logo url of email templates (#1527)

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/UserResource.java
This PR fixes a bug which prevented non-admin users from changing their password due to an incorrectly fetched user id.
> Fetch principalId instead of username when changing user password (#655)

- streampipes-client-python/setup.py
- streampipes-client-python/streampipes/py.typed
Add `py.typed`  file to `streampipes`  package to fulfill [PEP 561](https://peps.python.org/pep-0561/).
Thereby, adapted the `setup.py`  file to exclude test files from the released package
> [1475] fulfill PEP 561 & exclude test files from package

- ui/projects/streampipes/platform-services/src/lib/apis/labels.service.ts
- ui/projects/streampipes/platform-services/src/lib/model/labels/labels.model.ts
- ui/projects/streampipes/platform-services/src/public-api.ts
- ui/projects/streampipes/shared-ui/src/lib/components/sp-label/sp-label.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/sp-label/sp-label.component.scss
- ui/projects/streampipes/shared-ui/src/lib/components/sp-label/sp-label.component.ts
- ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
- ui/projects/streampipes/shared-ui/src/public-api.ts
- ui/src/app/configuration/configuration-tabs.ts
- ui/src/app/configuration/configuration.module.ts
- ui/src/app/configuration/label-configuration/edit-label/edit-label.component.html
- ui/src/app/configuration/label-configuration/edit-label/edit-label.component.scss
- ui/src/app/configuration/label-configuration/edit-label/edit-label.component.ts
- ui/src/app/configuration/label-configuration/label-configuration.component.html
- ui/src/app/configuration/label-configuration/label-configuration.component.scss
- ui/src/app/configuration/label-configuration/label-configuration.component.ts
Add a new page in the configuration section to create and edit labels, which will be later used to better organize StreamPipes resources.
> Add configuration view to create labels (#1564)

- ui/cypress/support/utils/DashboardUtils.ts
- ui/cypress/tests/dashboard/standaloneDashboardTest.spec.ts
- ui/src/app/dashboard/components/standalone/standalone-dashboard.component.html
- ui/src/app/dashboard/components/standalone/standalone-dashboard.component.ts
Allow the standalone dashboard to fetch required measurements and add an e2e test to check functionality of the standalone dashboard.
> Fix input of standalone dashboard component (#1547)

- streampipes-client-python/docs/overrides/404.html
- streampipes-client-python/mkdocs.yml
This PR introduces a custom error page for the Python docs.
Here you can see a screenshot:
fixes #1411 
> 1411 create custom error page for python docs

- .asf.yaml
> Add custom subjects for discussions (#1616)

- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/Init.java
- archetypes/streampipes-archetype-pe-processors-flink/src/main/resources/archetype-resources/src/main/java/Init.java
- archetypes/streampipes-archetype-pe-sinks-flink/src/main/resources/archetype-resources/src/main/java/Init.java
- streampipes-extensions/streampipes-connectors-influx/src/main/java/org/apache/streampipes/extensions/connectors/influx/InfluxConnectorsInit.java
- streampipes-extensions/streampipes-pipeline-elements-all-flink/src/main/java/org/apache/streampipes/pe/flink/AllFlinkPipelineElementsInit.java
- streampipes-extensions/streampipes-pipeline-elements-all-jvm/src/main/java/org/apache/streampipes/pe/jvm/AllPipelineElementsInit.java
- streampipes-extensions/streampipes-processors-aggregation-flink/src/main/java/org/apache/streampipes/processors/aggregation/flink/AggregationFlinkInit.java
- streampipes-extensions/streampipes-processors-change-detection-jvm/src/main/java/org/apache/streampipes/processors/changedetection/jvm/ChangeDetectionJvmInit.java
- streampipes-extensions/streampipes-processors-enricher-flink/src/main/java/org/apache/streampipes/processors/enricher/flink/EnricherFlinkInit.java
- streampipes-extensions/streampipes-processors-enricher-jvm/src/main/java/org/apache/streampipes/processors/enricher/jvm/EnricherJvmInit.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/FiltersJvmInit.java
- streampipes-extensions/streampipes-processors-filters-siddhi/src/main/java/org/apache/streampipes/processors/siddhi/FiltersSiddhiInit.java
- streampipes-extensions/streampipes-processors-geo-flink/src/main/java/org/apache/streampipes/processor/geo/flink/GeoFlinkInit.java
- streampipes-extensions/streampipes-processors-geo-jvm/src/main/java/org/apache/streampipes/processors/geo/jvm/GeoJvmInit.java
- streampipes-extensions/streampipes-processors-image-processing-jvm/src/main/java/org/apache/streampipes/processors/imageprocessing/jvm/ImageProcessingJvmInit.java
- streampipes-extensions/streampipes-processors-pattern-detection-flink/src/main/java/org/apache/streampipes/processors/pattern/detection/flink/PatternDetectionFlinkInit.java
- streampipes-extensions/streampipes-processors-statistics-flink/src/main/java/org/apache/streampipes/processors/statistics/flink/StatisticsFlinkInit.java
- streampipes-extensions/streampipes-processors-text-mining-flink/src/main/java/org/apache/streampipes/processors/textmining/flink/TextMiningFlinkInit.java
- streampipes-extensions/streampipes-processors-text-mining-jvm/src/main/java/org/apache/streampipes/processors/textmining/jvm/TextMiningJvmInit.java
- streampipes-extensions/streampipes-processors-transformation-flink/src/main/java/org/apache/streampipes/processors/transformation/flink/TransformationFlinkInit.java
- streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/TransformationJvmInit.java
- streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/BrokersJvmInit.java
- streampipes-extensions/streampipes-sinks-databases-flink/src/main/java/org/apache/streampipes/sinks/databases/flink/DatabasesFlinkInit.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/DatabasesJvmInit.java
- streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/SinksInternalJvmInit.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/SinksNotificationsJvmInit.java
Adds missing support for NATS as messaging protocol.
Relates to #1584.
> chore: add missing support of NATS as messaging protocol

- ui/package.json
Sync version with java components.
The UI component uses version 0.92.0-SNAPSHOT but other component use 0.93.0-SNAPSHOT
> Use same version as in java components

- installer/compose/docker-compose.full.yml
Fix #1597 by remove `sources-vehicle-simulator` from full deployment
> [#1597]: Remove sources-vehicle-simulator from full deployment

- streampipes-client-python/docs/img/interrogate_badge.svg
- streampipes-client-python/streampipes/functions/broker/nats/nats_consumer.py
- streampipes-client-python/streampipes/functions/broker/nats/nats_publisher.py
React to a API change in `nats-py`'s latest release and pass a list of brokers in the `connect()` function instead of an individual string.
> fix(1656): adapt to API change in nats-py (pass list instead of single string)

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/ConnectAdapterIiotInit.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/adapter/OpcUaAdapter.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/adapter/configuration/SpOpcUaConfigBuilder.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/adapter/utils/OpcUaUtil.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/sink/OpcUaSink.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/utils/OpcUaLabels.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/resources/org.apache.streampipes.sinks.databases.jvm.opcua/strings.en
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/helpers/Labels.java
- streampipes-sdk/src/test/java/org/apache/streampipes/sdk/helpers/LabelsTest.java
Fixes #1664 by  unifiing the labels for OPC UA adapter & sink.
> [#1664] Extract all opc labels into an enum class

- installer/upgrade_versions.sh
Fix #1659 
- Get the old version value from old files (`./cli/.env` here)
- Replace each of them with new version
> [#1659]: Update upgrade_version.sh for selectively updating versions

- streampipes-extensions-management/pom.xml
- streampipes-extensions/streampipes-processors-transformation-jvm/pom.xml
- streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/processor/value/change/ChangedValueDetectionProcessor.java
- streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/value/change/TestChangedValueDetectionProcessor.java
Store state for each dimension
> [#1672] Make processor dimension sensitive.

- README.md
- streampipes-client-python/README.md
- streampipes-client-python/setup.py
Improve metadata at some points in the repository (READMEs, PyPI metadata, etc.)
> chore: improve metadata for repository

- archetypes/streampipes-archetype-extensions-jvm/pom.xml
- archetypes/streampipes-archetype-pe-processors-flink/pom.xml
- archetypes/streampipes-archetype-pe-sinks-flink/pom.xml
- streampipes-extensions/streampipes-extensions-all-iiot/pom.xml
- streampipes-extensions/streampipes-extensions-all-jvm/pom.xml
- streampipes-extensions/streampipes-pipeline-elements-all-jvm/pom.xml
- streampipes-extensions/streampipes-processors-change-detection-jvm/pom.xml
- streampipes-extensions/streampipes-processors-enricher-jvm/pom.xml
- streampipes-extensions/streampipes-processors-filters-jvm/pom.xml
- streampipes-extensions/streampipes-processors-filters-siddhi/pom.xml
- streampipes-extensions/streampipes-processors-geo-jvm/pom.xml
- streampipes-extensions/streampipes-processors-image-processing-jvm/pom.xml
- streampipes-extensions/streampipes-processors-text-mining-jvm/pom.xml
- streampipes-extensions/streampipes-sinks-brokers-jvm/pom.xml
- streampipes-extensions/streampipes-sinks-databases-jvm/pom.xml
- streampipes-extensions/streampipes-sinks-internal-jvm/pom.xml
- streampipes-extensions/streampipes-sinks-notifications-jvm/pom.xml
- streampipes-extensions/streampipes-sources-watertank-simulator/pom.xml
- streampipes-integration-tests/pom.xml
- streampipes-model/pom.xml
- streampipes-sdk/pom.xml
- streampipes-wrapper-distributed/pom.xml
- streampipes-wrapper-flink/pom.xml
- streampipes-wrapper-kafka-streams/pom.xml
- streampipes-wrapper-python/pom.xml
- streampipes-wrapper-siddhi/pom.xml
- streampipes-wrapper/pom.xml
Set a variable which points to the location of the checkstyle configuration files.
See #1518
> Set value for checkstyle base path in more modules.

- streampipes-data-export/src/main/java/org/apache/streampipes/export/dataimport/PerformImportGenerator.java
- streampipes-data-export/src/main/java/org/apache/streampipes/export/dataimport/PreviewImportGenerator.java
- streampipes-data-export/src/main/java/org/apache/streampipes/export/utils/ImportAdapterMigrationUtils.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/GenericAdapterConverter.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/IAdapterConverter.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/MigrationHelpers.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/SpecificAdapterConverter.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/format/CsvFormatMigrator.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/format/EmptyFormatMigrator.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/format/FormatMigrator.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/format/JsonFormatMigrator.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/format/XmlFormatMigrator.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/utils/AdapterModels.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/utils/DocumentKeys.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/utils/FormatIds.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/adapter/migration/utils/GenericAdapterUtils.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v093/AdapterBackupWriter.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v093/AdapterMigration.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v093/migrator/GenericAdapterMigrator.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v093/migrator/SpecificAdapterMigrator.java
Currently, the data import in 0.93.0 fails when trying to import an adapter model that was exported prior to v0.93.0.  This PR adds support to auto-migrate older adapter models when importing.
> Support migration of adapters in data import

- streampipes-messaging-kafka/src/main/java/org/apache/streampipes/messaging/kafka/config/ConsumerConfigFactory.java
The `AUTO_OFFSET_RESET_CONFIG_DEFAULT` needs to be `latest` by default as otherwise the live preview of pipelines is broken and old events are replayed.
> [hotfix] Use latest offset setting as kafka consumer default

- ui/deployment/prebuild.js
Fix some variables in the prebuild script for UI customization
> [hotfix] Fix environment variable in prebuild script

- installer/k8s/templates/core/backend-pvc.yaml
- installer/k8s/templates/core/ui-configmap.yaml
- installer/k8s/templates/external/consul/consul-pv-pvc.yaml
- installer/k8s/templates/external/couchdb/couchdb-pv-pvc.yaml
- installer/k8s/templates/external/influxdb/influxdb-pvc.yaml
- installer/k8s/templates/external/influxdb/influxdb2-pvc.yaml
- installer/k8s/values.yaml
Add a configuration option to configure the storage sizes of all pvcs.
> [hotfix] Make storage sizes in helm charts configurable

- ui/package.json
- ui/src/app/core-ui/static-properties/static-free-input/static-free-input.component.scss
- ui/src/scss/sp/colors.scss
Disable the execution of the prebuild script in the `postinstall` step since it overwrites custom style configurations.
> [hotfix] Disable prebuild run on postinstall

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/DataProcessorResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/DataSinkResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/DataStreamResource.java
The endpoints to receive data processors, streams and sinks return a 400 status code in case the resource is not present, but should return a 404 to indicate the element cannot be found.
> [hotfix] Return 404 instead of 400 when requesting resources over client

- installer/k8s/values.yaml
See https://github.com/apache/streampipes/issues/1546
PR introduces (a) breaking change(s):  no
PR introduces (a) deprecation(s):  no
> Fix Helm Chart Upgrade Failure (#1546)

- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/Dockerfile
- archetypes/streampipes-archetype-pe-processors-flink/src/main/resources/archetype-resources/Dockerfile
- archetypes/streampipes-archetype-pe-sinks-flink/src/main/resources/archetype-resources/Dockerfile
> Use java 17 Docker base image in archetypes (#1770)

- ui/src/app/core-ui/data-download-dialog/components/select-data/select-data-range/select-data-range.component.ts
> Fix assignment of default time range in data download dialog (#1642)

- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/PipelineManager.java
- streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/NotificationsResourceManager.java
- streampipes-storage-api/src/main/java/org/apache/streampipes/storage/api/INotificationStorage.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/NotificationStorageImpl.java
- ui/src/app/notifications/notifications.component.html
- ui/src/app/notifications/service/notifications.service.ts
See #1533 
If a pipeline that is deleted includes a notification sink, related notifications are also deleted.
> Delete pipeline-related notifications upon pipeline deletion (#1533)

- ui/src/app/data-explorer/components/designer-panel/data-settings/field-selection/field-selection.component.html
- ui/src/app/data-explorer/components/designer-panel/data-settings/filter-selection-panel/filter-selection-panel.component.html
- ui/src/scss/sp/sp-theme.scss
> Fix width of aggregation box in data explorer (#1794)

- ui/src/app/core/components/toolbar/toolbar.component.html
- ui/src/app/core/core.module.ts
- ui/src/app/core/pipes/shorten.pipe.ts
- ui/src/app/data-explorer/components/designer-panel/data-settings/filter-selection-panel/filter-selection-panel.component.html
- ui/src/app/data-explorer/components/overview/data-explorer-dashboard-overview.component.ts
- ui/src/app/data-explorer/dialogs/edit-dashboard/data-explorer-edit-data-view-dialog.component.html
- ui/src/scss/sp/layout.scss
Fix several minor layout issues:
* Shorten username in profile menu
* Extend size of selections in data explorer filter panel
* Validate form input in data explorer data view dialog
> [hotfix] Fix layout issues and validation in data explorer

- streampipes-client-python/README.md
Add poetry badge to our README.
> chore: add Poetry badge to our README

- .github/workflows/pr-validation.yml
- .github/workflows/python-docs.yml
This PR addresses to fix the build failure that appeared in https://github.com/apache/streampipes/actions/runs/5982202856/job/16230994191.
The root cause is a missing  `poetry run` command.
In addition, the parameters for the poetry action are adapted, since some where not recognized.
> ci: add missing poetry statement & correct action parameter

- .asf.yaml
This PR adds the label `hacktoberfest` to our GitHub repo to indicate our participation in this years event as described [here](https://hacktoberfest.com/participation/#maintainers).
Willingness to participate was agreed on the PMC mailing list.
We can remove the label again once the event is done in November.
> add repo label 'hacktoberfest' to indicate participation

- installer/cli/README.md
Please refer to Issue #1866 & PR [here](https://github.com/apache/streampipes-website/pull/105) for context.
> Updating CLI Documentation

- .github/pr-labeler-config.yml
Adapt config for PR labeling action to recent changes in Python dependency management (switch to poetry).
> ci: adapt pr labeling config to Poetry

- .github/workflows/pypi-deployment.yml
- streampipes-client-python/Makefile
In some places, we have missed adding a `poetry run` command when migrating to poetry.
This PR makes up for this 
> fix: add missing `poetry run` command

- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v093/ConsulConfigMigration.java
- streampipes-service-discovery-api/src/main/java/org/apache/streampipes/svcdiscovery/api/SpConfig.java
- streampipes-service-discovery-consul/src/main/java/org/apache/streampipes/svcdiscovery/consul/ConsulSpConfig.java
> fix(#1956): Check Pulsar URL in consul migration runner

- pom.xml
- streampipes-rest/pom.xml
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/EmailResource.java
- ui/src/app/configuration/email-configuration/email-configuration.component.html
- ui/src/app/configuration/email-configuration/email-configuration.component.scss
- ui/src/app/configuration/email-configuration/email-configuration.component.ts
Fix a dependency issue causing a missing class when sending emails.
> [hotfix] Fix dependency conflict of mail components

- ui/src/app/assets/dialog/manage-asset-links/manage-asset-links-dialog.component.html
> fix: typo in asset management caption

- ui/src/app/connect/components/existing-adapters/existing-adapters.component.html
- ui/src/app/connect/components/existing-adapters/existing-adapters.component.scss
- ui/src/app/connect/components/existing-adapters/existing-adapters.component.ts
This PR extends the adapter overview by also showing the datetime of the last message and the number of messages produced by the adapter.
> style: Add last message info to adapter overview

- streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/textfilter/TextFilterProcessor.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/test/java/org/apache/streampipes/processors/filters/jvm/processor/textfilter/TestTextFilterProcessor.java
- implementation of unit test case for TextFilterProcessor.java class
- see [issue-1902](https://github.com/apache/streampipes/issues/1902)
> [1902] Implement unit tests for pipeline element 'TextFilterProcessor' 

- streampipes-model/pom.xml
This PR removes a duplicated dependency in `streampipes-model` and resolves the following warning by Maven:
> Warning:  
Warning:  Some problems were encountered while building the effective model for org.apache.streampipes:streampipes-model:jar:0.[9](https://github.com/apache/streampipes/actions/runs/6516195022/job/17727394655?pr=2025#step:4:10)3.0-SNAPSHOT
Warning:  'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.mockito:mockito-core:jar -> duplicate declaration of version (?) @ line 79, column 21
Warning:  
Warning:  It is highly recommended to fix these problems because they threaten the stability of your build.
Warning:  
Warning:  For this reason, future Maven versions might no longer support building such malformed projects.
Warning:
PR introduces …
> chore: remove duplicate dependency

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataExplorerQueryManagement.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/influx/DataLakeMeasurementCount.java
- streampipes-platform-services/src/main/java/org/apache/streampipes/ps/DataLakeMeasureResourceV4.java
- ui/projects/streampipes/platform-services/src/lib/apis/datalake-rest.service.ts
- ui/src/app/configuration/datalake-configuration/datalake-configuration.component.html
- ui/src/app/configuration/datalake-configuration/datalake-configuration.component.ts
> feat(#2023): Provide REST endpoint to fetch measurement counts

- README.md
Improve the README by using GitHub's admonitions
> docs: use GitHub admonitions for README

- pom.xml
- streampipes-maven-plugin/pom.xml
- tools/maven/installer.xml
> feat(#2061): Extend maven-assembly-plugin to generate installer zip file

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/WorkerRestClient.java
> refactor: rename logger to convention 'LOG'

- streampipes-model/src/main/java/org/apache/streampipes/model/extensions/svcdiscovery/SpServiceRegistration.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/health/ServiceHealthCheck.java
- streampipes-service-discovery/src/main/java/org/apache/streampipes/svcdiscovery/SpServiceDiscoveryCore.java
> refactor: introduce convenience method for service url

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/WorkerAdministrationManagement.java
- streampipes-model/src/main/java/org/apache/streampipes/model/message/Notification.java
This PR introduces two minor improvements:
- fix logger configuration
- add string representation for notification
> refactor:minor adaption & improvement

- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__GenericAdapter.java
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__SpecificAdapter.java
- streampipes-vocabulary/src/main/java/org/apache/streampipes/vocabulary/SO.java
Some small improvements that are required for https://github.com/apache/streampipes-website/pull/124
> improve archetypes for adapter tutorial

- pom.xml
Modify settings of `maven-assembly-plugin` so that the plugin is not executed for child modules.
> Fix settings of maven-assembly-plugin

- streampipes-client-api/src/main/java/org/apache/streampipes/client/api/IAdminApi.java
- streampipes-client/src/main/java/org/apache/streampipes/client/api/AdminApi.java
- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterMigrationManager.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/migration/AbstractMigrationManager.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/migration/IMigrationHandler.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/migration/MigrationUtils.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/migration/PipelineElementMigrationManager.java
- streampipes-pipeline-management/src/test/java/org/apache/streampipes/manager/migration/MigrationUtilsTest.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/admin/MigrationResource.java
- streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/ExtensionsModelSubmitter.java
* Introduce management classes which handle the actual migration
* Let the `MigrationResource` delegate requests to the management classes 
* Divide migration code into smaller chunks
* Use only a single request for submitting adapter and pipeline migrations
> Improvements to extension migration

- ui/src/app/configuration/messaging-configuration/broker-config/broker-config.component.html
- ui/src/app/configuration/messaging-configuration/broker-config/broker-config.component.ts
- ui/src/app/configuration/messaging-configuration/messaging-configuration.component.html
Properly update changes in the configuration view's broker settings. (#2112)
> fix(#2112): Properly update broker configs

- ui/projects/streampipes/platform-services/src/lib/apis/adapter.service.ts
The request to delete adapters fails with a 400 when conducting Cypress tests.
> fix(tests): Fix path when deleting adapters

- ui/cypress/support/builder/PipelineElementBuilder.ts
- ui/cypress/tests/adapter/editAdapter.smoke.spec.ts
- ui/cypress/tests/adapter/editAdapterSettingsAndPipeline.spec.ts
- ui/cypress/tests/adapter/editAdapterValuesAndFields.spec.ts
- ui/src/app/connect/dialog/adapter-started/adapter-started-update-migration/adapter-started-update-migration.component.html
- ui/src/app/editor/components/pipeline-element-options/pipeline-element-options.component.html
- ui/src/app/pipelines/components/pipeline-overview/pipeline-overview.component.html
Added two new tests for editing adapters: Testing the functionality of pipelines after editing an adapter and testing if changed fields of property and added properties persist after saving.
https://github.com/https://github.com/apache/streampipes/issues/2017
> Added two new tests for editing adapters and pipelines

- ui/Dockerfile
Use the nginx alpine image as base docker image for the UI to reduce the image size.
> feat: Use alpine-based Docker image for UI

- streampipes-config/src/main/java/org/apache/streampipes/config/backend/BackendConfig.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/health/CoreInitialInstallationProgress.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/health/ServiceHealthCheck.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/setup/AutoInstallation.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/Setup.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/admin/MigrationResource.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/StreamPipesCoreApplication.java
- streampipes-service-discovery/src/main/java/org/apache/streampipes/svcdiscovery/SpServiceDiscoveryCore.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/UserStorage.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/utils/Utils.java
Add some improvements to startup behaviour for new installations and migrations.
> improvement: Optimize startup behaviour

- .github/workflows/build.yml
- pom.xml
- streampipes-extensions/streampipes-extensions-iiot-minimal/pom.xml
- streampipes-extensions/streampipes-extensions-iiot-minimal/src/main/java/org/apache/streampipes/extensions/iiot/minimal/ExtensionsIIoTMinimalInit.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/endpoint/EndpointItemFetcher.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/health/ServiceHealthCheck.java
- streampipes-service-core-minimal/Dockerfile
- streampipes-service-core-minimal/pom.xml
- streampipes-service-core-minimal/src/main/java/org/apache/streampipes/service/core/minimal/StreamPipesCoreApplicationMinimal.java
Harmonize naming of extensions and core minimal module:
* Rename streampipes-service-core-nats to streampipes-service-core-minimal
* Add MQTT as protocol to minimal config
> improvement: Harmonize minimal setup

- pom.xml
- streampipes-service-base/pom.xml
- streampipes-service-core/pom.xml
Remove some obsolete Maven dependencies
> chore: Maven housekeeping

- streampipes-extensions/streampipes-extensions-all-iiot/Dockerfile
- streampipes-extensions/streampipes-extensions-all-iiot/pom.xml
- streampipes-extensions/streampipes-extensions-all-jvm/Dockerfile
- streampipes-extensions/streampipes-extensions-all-jvm/pom.xml
- streampipes-extensions/streampipes-extensions-iiot-minimal/Dockerfile
- streampipes-extensions/streampipes-extensions-iiot-minimal/pom.xml
- streampipes-service-core-minimal/Dockerfile
- streampipes-service-core-minimal/pom.xml
- streampipes-service-core/Dockerfile
- streampipes-service-core/pom.xml
> feat(#2161): Generate layered Docker images

- pom.xml
Upgrade Active MQ due to CVE-2023-46604
> deps: update Active MQ due to CVE

- ui/src/app/assets/components/asset-overview/asset-overview.component.html
> fix: tooltip in asset overview

- ui/src/app/info/about/about.component.html
> ui: add link to LinkedIn in Support section

- installer/cli/README.md
- installer/cli/bin/commands/info
- installer/cli/environments/full
- installer/scripts/epsg/Readme.md
- run-validation-system.sh
- streampipes-extensions/docker-compose.yml
- streampipes-maven-plugin/README.md
Use latest module names in cli installer and some docs.
fixes #2183
PR introduces (a) breaking change: no
PR introduces (a) deprecation: no
> Streamline module names (#2183)

- ui/src/app/editor/components/pipeline-element-options/pipeline-element-options.component.ts
> refactor: remove legacy set reference

- pom.xml
- streampipes-model-client/pom.xml
- streampipes-model/pom.xml
> 2200 include typescript generator maven plugin to plugin managment

- streampipes-model/src/main/java/org/apache/streampipes/model/assets/AssetLinkBuilder.java
- streampipes-model/src/test/java/org/apache/streampipes/model/assets/AssetLinkBuilderTest.java
> feat: create builder for AssetLink

- streampipes-model/src/main/java/org/apache/streampipes/model/base/NamedStreamPipesEntity.java
- streampipes-rest-extensions/src/main/java/org/apache/streampipes/rest/extensions/connect/AdapterWorkerResource.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/stream/StreamBuilder.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/utils/Filter.java
Removing methods from the `NamedStreamPipesEntity` that are marked as deprecated since release `0.90.0`.
The following methods have been deprecated since `0.61.0` and are now removed:
- `String getUri()`
- `void setUri(String uri)`
Both are replaced by the corresponding methods of `elementId`.
> refactor: remove deprecated elements from `NamedStreamPipesEntity`

- streampipes-extensions/streampipes-processors-enricher-jvm/pom.xml
- streampipes-extensions/streampipes-processors-enricher-jvm/src/main/java/org/apache/streampipes/processors/enricher/jvm/processor/sizemeasure/SizeMeasureProcessor.java
- streampipes-extensions/streampipes-processors-enricher-jvm/src/test/java/org/apache/streampipes/processors/enricher/jvm/processor/sizemeasure/TestSizeMeasureProcessor.java
Closes #1888 
Added a test for each size unit. Unsure if that was the expectation, let me know how you would improve it
> 1888 Implemented unit tests for SizeMeasureProcessor

- installer/k8s/README.md
- prometheus-grafana/README.md
> fix: headings in README files

- ui/cypress/tests/assetManagement/createAsset.spec.ts
- ui/src/app/assets/components/asset-overview/asset-overview.component.html
- ui/src/app/assets/components/asset-overview/asset-overview.component.ts
> feat(#2192): add download button in asset management overview

- pom.xml
> fix: change Java version to 17 for maven-javadoc-plugin

- .github/workflows/pypi-deployment.yml
> fix: retrieve release version for Python from GitHub tag

- .github/dependabot.yml
> add docker registry to dependabot config

- ui/package-lock.json
- ui/package.json
- ui/src/app/editor/components/pipeline-element-options/pipeline-element-options.component.ts
- ui/src/app/editor/services/jsplumb-bridge.service.ts
- ui/src/app/editor/services/object-provider.service.ts
Since the nightly e2e tests failed, I added lodash again for the deep copy.
> fix(#2235): Use lodash for deep copy

- .github/dependabot.yml
- installer/cli/deploy/standalone/grafana/docker-compose.yml
Update docker-compose file for Grafana in our installer
> chore: update docker-compose setup for Grafana

- pom.xml
Bump Apache Commons Compress to version `1.25.0` due to [`CVE-2023-42503`](https://osv.dev/vulnerability/CVE-2023-42503)
> deps: update commons-compress due to CVE

- installer/cli/deploy/standalone/prometheus/prometheus.yml
> chore: use service name instead of localhost in prometheus config

- streampipes-extensions/streampipes-connectors-influx/src/main/java/org/apache/streampipes/extensions/connectors/influx/sink/InfluxDbSink.java
- streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/sink/KafkaPublishSink.java
- streampipes-extensions/streampipes-connectors-mqtt/src/main/java/org/apache/streampipes/extensions/connectors/mqtt/sink/MqttPublisherSink.java
- streampipes-extensions/streampipes-connectors-nats/src/main/java/org/apache/streampipes/extensions/connectors/nats/sink/NatsSink.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/sink/OpcUaSink.java
- streampipes-extensions/streampipes-connectors-pulsar/src/main/java/org/apache/streampipes/extensions/connectors/pulsar/sink/PulsarPublisherSink.java
- streampipes-extensions/streampipes-connectors-rocketmq/src/main/java/org/apache/streampipes/extensions/connectors/rocketmq/sink/RocketMQPublisherSink.java
- streampipes-extensions/streampipes-connectors-tubemq/src/main/java/org/apache/streampipes/extensions/connectors/tubemq/sink/TubeMQPublisherSink.java
- streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/bufferrest/BufferRestPublisherSink.java
- streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/jms/JmsPublisherSink.java
- streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/rabbitmq/RabbitMqPublisherSink.java
- streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/rest/RestSink.java
- streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/websocket/WebsocketServerSink.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/couchdb/CouchDbSink.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/ditto/DittoSink.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/iotdb/IotDbSink.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/postgresql/PostgreSqlSink.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/redis/RedisSink.java
- streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/datalake/DataLakeSink.java
- streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/notification/NotificationProducer.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/email/EmailSink.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/msteams/MSTeamsSink.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/onesignal/OneSignalSink.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/slack/SlackNotificationSink.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/telegram/TelegramSink.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/builder/DataSinkBuilder.java
Since #2001, all element descriptions are required to provide a version number.
This PR adds versions to all sinks.
> refactor: include version in all data sink descriptions as required for migrations

- ui/src/app/login/components/auth-box/auth-box.component.html
- ui/src/app/login/components/auth-box/auth-box.component.scss
- ui/src/app/login/components/auth-box/auth-box.component.ts
Fix the target of the documentation link on the login page and give the login page a more modern look.
> chore: Fix docs link on login page, improve layout

- .github/workflows/pr-labeler.yml
Revert the version bump of the PR labeling action as it contains a breaking change (see the release notes)
> revert: version dump vor PR labeling action due to breaking change

- streampipes-commons/src/main/java/org/apache/streampipes/commons/constants/HttpConstants.java
- streampipes-service-base/src/main/java/org/apache/streampipes/service/base/security/UnauthorizedRequestEntryPoint.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/filter/TokenAuthenticationFilter.java
> feat(#2269): Add basic auth to prometheus monitoring endpoint

- installer/cli/environments/lite-monitoring
- streampipes-commons/src/main/java/org/apache/streampipes/commons/prometheus/StreamPipesCollectorRegistry.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/prometheus/adapter/AdapterMetrics.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/prometheus/adapter/AdapterMetricsManager.java
- streampipes-commons/src/test/java/org/apache/streampipes/commons/prometheus/adapter/AdapterMetricsTest.java
- streampipes-commons/src/test/java/org/apache/streampipes/commons/resources/TestResources.java
- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/health/AdapterHealthCheck.java
- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterMasterManagement.java
- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/WorkerAdministrationManagement.java
- streampipes-connect-management/src/test/java/org/apache/streampipes/connect/management/health/AdapterHealthCheckTest.java
- streampipes-connect-management/src/test/java/org/apache/streampipes/connect/management/management/AdapterMasterManagementTest.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/ResetManagement.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/connect/AdapterResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/connect/RuntimeResolvableResource.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/PostStartupTask.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/StreamPipesCoreApplication.java
While we already expose monitoring metrics for pipelines during the pipeline health check, adapter metrics are missing out so far.
This PR introduces the capability to define metrics for adapters (see `AdapterMetrics`) and expose them via Prometheus during the adapter health check.
For now, this supports just one metric (`adapter_events_published_total`) which tracks the total amount of events published for every adapter.
This can be used, for example, to monitor if all adapters are running.
Here is a screenshot of the metric for two adapters in Prometheus:
> extend monitoring by adding metrics for adapters

- streampipes-model-client/src/main/java/org/apache/streampipes/model/client/user/Group.java
> fix(#2292): Rename type identifier in Group model

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/influx/DataExplorerInfluxQueryExecutor.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/ProvidedRestQueryParamConverter.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/SelectQueryParams.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataExplorerQueryExecutor.java
> feat(#2313): Remove count query from data explorer queries

- archetypes/streampipes-archetype-pe-processors-flink/src/main/resources/archetype-resources/pom.xml
- archetypes/streampipes-archetype-pe-sinks-flink/src/main/resources/archetype-resources/pom.xml
- streampipes-data-explorer/pom.xml
- streampipes-service-core/pom.xml
- streampipes-user-management/pom.xml
> fix(#2316): Remove obsolete dependencies to streampipes-config

- streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/ExtensionsModelSubmitter.java
> fix: ensure Spring uses the correct serializer in extensions service

- streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/datalake/migrations/DataLakeSinkMigrationV1.java
Modify the option label in the Data Lake schema migration
> fix: Modify schema update label

- streampipes-commons/src/main/java/org/apache/streampipes/commons/resources/Resources.java
> fix(#2324): Make resource loading more robust

- streampipes-service-core/src/main/resources/application.properties
> fix(#2326): Add max file size for multipart requests

- streampipes-platform-services/src/main/java/org/apache/streampipes/ps/PipelineElementTemplateResource.java
- ui/src/app/editor/dialog/customize/customize.component.html
> fix(#2361): Fix pipeline element template generation

- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/parser/CsvParser.java
- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/parser/xml/XmlParser.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/extractor/AdapterParameterExtractor.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/extractor/StaticPropertyExtractor.java
This PR changes the API of `AdapterParameterExtractor`. It now uses the interface of `StaticPropertyExtractor` instead of the implementation.
> feat: AdapterParameterExtractor now uses IStaticPropertyExtractor

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/GenericStorageResource.java
- streampipes-storage-api/src/main/java/org/apache/streampipes/storage/api/IGenericStorage.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/GenericStorageImpl.java
- ui/projects/streampipes/platform-services/src/lib/apis/generic-storage.service.ts
- ui/projects/streampipes/platform-services/src/lib/query/generic-storage-query-builder.ts
- ui/projects/streampipes/platform-services/src/public-api.ts
See #2376 
The API can be called from the UI's platform service library.
CouchDB find documentation: https://docs.couchdb.org/en/stable/api/database/find.html
> feat(#2376): Add find endpoint to generic storage API

- installer/cli/deploy/standalone/extensions-all-jvm/docker-compose.yml
As @IsaakKrut mentioned  in [1](https://github.com/apache/streampipes/pull/2203#issuecomment-1871514746), using the same key multiple times could lead to errors.
This PR fixes this by define environment variables at a single location.
PR introduces a breaking change: no
PR introduces a deprecation: no
> [#2203] Fix error because of multiple definitions of variables. 

- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/GenericStorageImpl.java
Provides documentation to find the relevant parameters for the method `GenericStorageImpl.find`
> docs: Add documentation to GenericStorageImpl.find

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineResource.java
- ui/projects/streampipes/platform-services/src/lib/apis/pipeline.service.ts
The name of the REST endpoint for pipeline validation was very confusing, so I changed it from "update" to "validate".
> refactor(#2380): Change route of validatePipeline to `validate`

- ui/cypress/tests/datalake/widgets/timeSeriesSave.spec.ts
> fix(#2393): Add timeout to failing time series widget test

- ui/src/app/connect/components/existing-adapters/existing-adapters.component.html
- ui/src/app/connect/components/existing-adapters/existing-adapters.component.ts
- ui/src/app/home/home.component.ts
- ui/src/app/pipelines/pipelines.component.html
- ui/src/app/pipelines/pipelines.component.ts
- ui/src/app/services/tour/shepherd.service.ts
* I modified the home component so that the dialog is only shown once on page load. There was a bug which opened multiple dialogs due to inproper cleanup of subscriptions
* I added a behaviour subject to the `ShepherdService` which notifies consumers about the current tutorial status
* In the pipeline overview and adapter overview, the tutorial icon is disabled if the tutorial is active
@RobertIndie good catch!
> fix(#2396): Disable tutorial button, fix subscription cleanup

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/pe/DataStreamResource.java
Add a missing `RequestBody` annotation to the `DataStreamResource` which was missing after migration to Spring Rest.
> fix: Add RequestBody annotation to Data Stream resource

- installer/compose/docker-compose.full.yml
Flink components are currently not released (#1740), to avoid inconvenience for users  (#2429)  this components should be removed from the compose file.
> Remove Flink pipeline elements from compose file

- streampipes-platform-services/src/main/java/org/apache/streampipes/ps/DataLakeResourceV4.java
- ui/projects/streampipes/platform-services/src/lib/apis/datalake-rest.service.ts
> fix(#2434): Remove the trailing slash from the end point of the measurements

- ui/src/app/data-explorer/components/panel/data-explorer-dashboard-panel.component.ts
- ui/src/app/data-explorer/components/widget-view/grid-view/data-explorer-dashboard-grid.component.ts
- ui/src/app/data-explorer/components/widget-view/slide-view/data-explorer-dashboard-slide-view.component.ts
- ui/src/app/data-explorer/components/widgets/time-series-chart/config/time-series-chart-widget-config.component.html
- ui/src/app/data-explorer/components/widgets/time-series-chart/model/time-series-chart-widget.model.ts
> refactor: Some minor changes and code cleanups

- streampipes-service-core/src/main/resources/application.properties
This PR adds a configuration variable to the Spring configuration to define the timeout time for REST requests
> fix(#2469): Add configuration to increase request timeout time

- streampipes-commons/src/test/java/org/apache/streampipes/commons/parser/BooleanParserTest.java
- streampipes-commons/src/test/java/org/apache/streampipes/commons/parser/FloatParserTest.java
- streampipes-commons/src/test/java/org/apache/streampipes/commons/parser/IntegerParserTest.java
- streampipes-commons/src/test/java/org/apache/streampipes/commons/parser/StringParserTest.java
PR introduces (a) breaking change(s):no
> test: add tests for commons parser

- streampipes-rest/src/main/java/org/apache/streampipes/rest/ResetManagement.java
> fix(#2413): Add clean up for assets and extract methods of deletion steps

- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/convert/ToTransformedSchemaConverter.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/adapter/OpcUaAdapter.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/sink/OpcUaSink.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/utils/OpcUaUtil.java
- ui/src/app/connect/components/configuration-group/configuration-group.component.html
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-tree-input.component.html
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-tree-input.component.ts
> fix(#2491): Keep selected nodes when updating an existing adapter

- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/config/SpOpcUaConfigExtractor.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/utils/OpcUaUtil.java
- streampipes-extensions/streampipes-connectors-opcua/src/test/java/org/apache/streampipes/extensions/connectors/opcua/utils/OpcUaUtilTest.java
> refactor: Remove unused code and minor refactoring

- streampipes-client/src/main/java/org/apache/streampipes/client/api/DataStreamApi.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/zip/ZipFileGenerator.java
- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/transform/schema/MoveTransformationRule.java
- streampipes-data-explorer-commons/src/main/java/org/apache/streampipes/dataexplorer/commons/influx/InfluxStore.java
- streampipes-data-explorer-commons/src/test/java/org/apache/streampipes/dataexplorer/commons/influx/serializer/TestRawFieldSerializer.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/simulator/machine/MachineDataSimulatorUtils.java
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/s7/Plc4xS7Adapter.java
- streampipes-extensions/streampipes-pipeline-elements-experimental-flink/src/main/java/org/apache/streampipes/pe/flink/processor/aggregation/AggregationController.java
- streampipes-extensions/streampipes-processors-geo-jvm/src/main/java/org/apache/streampipes/processors/geo/jvm/jts/helper/SpReprojectionBuilder.java
* Use constants if it applicable
* Remove unnecessary diamond operators
* Use try-with-resources
> Code cleanup

- installer/k8s/templates/core/extensions-all-iiot-deployment.yaml
Signed-off-by: huangyanfeng <huangyanfeng1992@gmail.com>
Chart extension deployment environment missing SP_COUCHDB_USER
no
no
> Chart install extension deployment environment missing SP_COUCHDB_USER

- streampipes-client-api/src/main/java/org/apache/streampipes/client/api/IFileApi.java
- streampipes-client/src/main/java/org/apache/streampipes/client/api/FileApi.java
- streampipes-commons/pom.xml
- streampipes-commons/src/main/java/org/apache/streampipes/commons/file/FileHasher.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/utils/FileProtocolUtils.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/file/FileManager.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineElementFile.java
> refactor(#2520): Add method to check file content in FileProtocolUtils

- ui/cypress/tests/datalake/timeRangeSelectors.spec.ts
- ui/src/app/data-explorer/components/time-selector/timeRangeSelector.component.html
- ui/src/app/data-explorer/components/time-selector/timeRangeSelector.component.ts
> #2442 fixed data explorer time range buttons

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/health/AdapterHealthCheck.java
This PR addresses a critical issue encountered during the restart of StreamPipes, where multiple existing adapters assigned to one worker failed to start and became unmanageable for deletion. The root cause was identified within the `AdapterHealthManagement`, which erroneously utilized an immutable list for grouping adapter instances per worker. Consequently, attempts to add more than one adapter to the list triggered an `UnsupportedOperationException`. 
> fix: restart multiple adapter instances per worker

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/ProvidedRestQueryParams.java
- streampipes-platform-services/src/main/java/org/apache/streampipes/ps/DataLakeResourceV4.java
> fix(#2336): Fixes synchronized query requests for the dashboard

- streampipes-client/src/main/java/org/apache/streampipes/client/api/FileApi.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/file/FileManager.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineElementFile.java
> refactor(#2529): Deprecate isOriginalFileName in FileAPI and remove parameter from REST API

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/admin/ExtensionsServiceEndpointResource.java
> refactor: remove unnecessary parameter 'username'

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/admin/ExtensionsServiceEndpointResource.java
In contrast to the issue description, the problem here is not the created data stream but the handling of data streams in the extensions service endpoint.
> fix(#2550): change handling of data stream in extensions service endpoint

- ui/src/app/dashboard/dashboard.module.ts
> refactor: Remove duplicate import from dashboard module

- ui/src/app/data-explorer/components/panel/data-explorer-dashboard-panel.component.css
- ui/src/app/data-explorer/components/widgets/time-series-chart/config/time-series-chart-widget-config.component.html
- ui/src/app/data-explorer/components/widgets/time-series-chart/config/time-series-chart-widget-config.component.ts
- ui/src/app/data-explorer/components/widgets/time-series-chart/model/time-series-chart-widget.model.ts
- ui/src/app/data-explorer/components/widgets/time-series-chart/sp-timeseries-renderer.service.ts
- ui/src/app/data-explorer/components/widgets/utils/select-axis-options/select-axis-options.component.html
- ui/src/app/data-explorer/components/widgets/utils/select-axis-options/select-axis-options.component.scss
- ui/src/app/data-explorer/components/widgets/utils/select-axis-options/select-axis-options.component.ts
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/select-color-properties.component.html
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/select-color-properties.component.ts
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/time-series-item-config/time-series-item-config.component.html
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/time-series-item-config/time-series-item-config.component.scss
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/time-series-item-config/time-series-item-config.component.ts
- ui/src/app/data-explorer/data-explorer.module.ts
- ui/src/app/data-explorer/echarts-renderer/echarts-dataset-generator.service.ts
- ui/src/app/data-explorer/models/dataview-dashboard.model.ts
- ui/src/app/data-explorer/registry/data-explorer-widget-registry.ts
> feat(#2568): Make time series axes configurable

- ui/cypress/support/utils/PipelineUtils.ts
- ui/cypress/tests/pipelineElement/PipelineElementDocumentation.spec.ts
- ui/src/app/core-ui/help/help.component.ts
- ui/src/app/core-ui/pipeline-element-documentation/pipeline-element-documentation.component.html
- ui/src/app/core-ui/pipeline-element-documentation/pipeline-element-documentation.component.ts
- ui/src/app/editor/components/pipeline-element-icon-stand-row/pipeline-element-icon-stand-row.component.html
Fix  #2574. 
This PR adds a new test to check if the Markdown documentation of the pipeline elements is displayed. It also contains some minor refactoring.
> test(#2574): Add test to validate pipeline element documentation

- streampipes-platform-services/src/main/java/org/apache/streampipes/ps/PipelineElementTemplateResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/ResetManagement.java
- ui/cypress/support/utils/PipelineElementTemplateUtils.ts
- ui/cypress/support/utils/PipelineUtils.ts
- ui/cypress/tests/adapter/connectConfigurationTemplate.spec.ts
- ui/cypress/tests/pipelineElementConfigurationTemplate/connectConfigurationTemplate.spec.ts
- ui/cypress/tests/pipelineElementConfigurationTemplate/pipelineElementConfigurationTemplate.ts
- ui/src/app/connect/components/adapter-configuration/adapter-settings/adapter-settings.component.html
- ui/src/app/connect/dialog/adapter-template/adapter-template-dialog.component.html
- ui/src/app/core-ui/pipeline-element-template-config/pipeline-element-template-config.component.html
- ui/src/app/core-ui/pipeline-element-template-config/pipeline-element-template.pipe.ts
- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly.component.html
- ui/src/app/editor/dialog/customize/customize.component.html
This PR enhances the functionality of pipeline element templates in both connect and pipeline editor. It also includes Cypress end-to-end (E2E) tests covering these scenarios. Moreover, it addresses a bug by removing mapping properties from the template selection, as they necessitate an actual event stream and thus cannot be stored in a template.
> fix(#2577): pipeline element templates do not work

- ui/src/app/data-explorer/components/designer-panel/appearance-settings/data-explorer-widget-appearance-settings.component.html
- ui/src/app/data-explorer/components/designer-panel/appearance-settings/data-explorer-widget-appearance-settings.component.ts
- ui/src/app/data-explorer/components/designer-panel/data-explorer-designer-panel.component.html
- ui/src/app/data-explorer/components/widgets/base/base-widget-config.ts
- ui/src/app/data-explorer/components/widgets/time-series-chart/config/time-series-chart-widget-config.component.html
- ui/src/app/data-explorer/components/widgets/time-series-chart/config/time-series-chart-widget-config.component.ts
- ui/src/app/data-explorer/components/widgets/time-series-chart/sp-timeseries-renderer.service.ts
- ui/src/app/data-explorer/components/widgets/utils/echarts-widget-appearance-config/echarts-widget-appearance-config.component.html
- ui/src/app/data-explorer/components/widgets/utils/echarts-widget-appearance-config/echarts-widget-appearance-config.component.ts
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/select-color-properties.component.html
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/select-color-properties.component.ts
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/time-series-item-config/time-series-item-config.component.html
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/time-series-item-config/time-series-item-config.component.ts
- ui/src/app/data-explorer/data-explorer.module.ts
- ui/src/app/data-explorer/echarts-renderer/base-echarts-renderer.ts
- ui/src/app/data-explorer/echarts-renderer/echarts-basic-options-generator.service.ts
- ui/src/app/data-explorer/models/dataview-dashboard.model.ts
- ui/src/app/data-explorer/registry/data-explorer-widget-registry.ts
> feat(#2579): Add extended appearance panel to data explorer

- pom.xml
> deps: Bump jackson-databind version

- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/src/app/connect/services/rest.service.ts
- ui/src/app/core-services/semantic-type/semantic-type-utils.service.ts
- ui/src/app/core-ui/core-ui.module.ts
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-error/live-preview-error.component.html
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-error/live-preview-error.component.scss
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-error/live-preview-error.component.ts
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-loading/live-preview-loading.component.html
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-loading/live-preview-loading.component.scss
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-loading/live-preview-loading.component.ts
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-table/live-preview-table.component.html
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-table/live-preview-table.component.scss
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-table/live-preview-table.component.ts
- ui/src/app/core-ui/pipeline-element-runtime-info/pipeline-element-runtime-info.component.html
- ui/src/app/core-ui/pipeline-element-runtime-info/pipeline-element-runtime-info.component.scss
- ui/src/app/core-ui/pipeline-element-runtime-info/pipeline-element-runtime-info.component.ts
> refactor(#2583): Remove dataTable from component PipelineElementRuntimeInfo

- pom.xml
Deactivate the Maven dependency check plugin since it causes timeouts when downloading NVD data and lets our builds fail.
> fix: Deactivate dependency check plugin

- ui/src/app/editor/dialog/matching-error/matching-error.component.html
- ui/src/app/editor/dialog/save-pipeline/save-pipeline.component.html
> refactor: Minor code cleanup remove commented out code

- ui/src/app/editor/components/pipeline-element-preview/pipeline-element-preview.component.scss
Fix #2594. 
This PR removes the dataTable dependency from CSS in the PipelineElementPreviewComponent.
> refactor(#2594): Remove dataTable from pipeline-element-preview

- ui/package-lock.json
- ui/package.json
- ui/src/app/app-asset-monitoring/components/create-asset/create-asset.component.ts
- ui/src/app/assets/components/asset-overview/asset-overview.component.ts
- ui/src/app/connect/components/adapter-configuration/schema-editor/event-property-row/event-property-row.component.ts
- ui/src/app/connect/components/adapter-configuration/schema-editor/event-schema/event-schema.component.ts
- ui/src/app/connect/connect.module.ts
- ui/src/app/core-services/id-generator/id-generator.service.ts
- ui/src/app/core-ui/static-properties/static-property-util.service.ts
- ui/src/app/editor/components/output-strategy/user-defined-output/user-defined-output.component.ts
- ui/src/app/editor/components/pipeline/pipeline.component.ts
- ui/src/app/editor/dialog/save-pipeline/save-pipeline.component.ts
- ui/src/app/editor/services/jsplumb.service.ts
Fix: #2606
Harmonization of the locations where an ID is generated and removal of the library UUID.
> refactor(#2606): hamonize random id generation in UI

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/resources/org.apache.streampipes.connect.iiot.adapters.oi4/documentation.md
> docs: add closing tag in description of OI4 adapter

- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/constants/GenericCouchDbConstants.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/utils/CouchDbViewGenerator.java
The variable `VIEW_NAME` was only used in a log message and it has the same value as `DESIGN_DOC_NAME`, so I removed it.
> refactor: Harmonize static variables in GenericCouchDbConstants

- ui/src/app/assets/assets.module.ts
- ui/src/app/pipelines/dialog/import-pipeline/import-pipeline-dialog.component.html
- ui/src/app/pipelines/pipelines.module.ts
This PR fixes two e2e tests which broke due to #2623.
> test: Fix broken e2e tests

- ui/src/app/core-ui/pipeline-element-runtime-info/pipeline-element-runtime-info.component.ts
The live preview did not properly close a subscription when closing the dialog.
> fix: Disable live preview subscription when closing dialog

- ui/cypress/support/utils/datalake/DataLakeUtils.ts
- ui/cypress/tests/datalake/widgets/heatmap.spec.ts
- ui/cypress/tests/datalake/widgets/histogram.spec.ts
- ui/cypress/tests/datalake/widgets/indicator.spec.ts
- ui/cypress/tests/datalake/widgets/map.spec.ts
- ui/cypress/tests/datalake/widgets/timeSeriesSave.spec.ts
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/time-series-item-config/time-series-item-config.component.html
This PR should fix the nightly e2e tests
> fix: Fix the e2e tests for data explorer line charts

- ui/src/app/configuration/configuration.module.ts
> fix(#2648): add missing Material modules

- ui/src/app/configuration/configuration.module.ts
- ui/src/app/configuration/general-configuration/general-configuration.component.html
- ui/src/app/configuration/general-configuration/general-configuration.component.scss
- ui/src/app/configuration/general-configuration/general-configuration.component.ts
Fix imports after removal of `CustomMaterialModule`.
Instead of disabling the checkbox, completely hide self-service registration settings if basic settings or email settings are not valid and show a warning box.
> fix(#2650): Better highlight mandatory settings for self-registration

- ui/src/app/dashboard/components/overview/dashboard-overview.component.html
> feat(#2657): Add tooltips to dashboard icon buttons

- ui/src/app/configuration/extensions-service-management/extensions-service-configuration/service-configs/service-configs.component.ts
Add missing `semanticTypesService` to the UI's service configuration view.
> fix: Inject missing Angular service

- streampipes-client-go/examples/main.go
- streampipes-client-go/streampipes/data_lake_measure_api.go
- streampipes-client-go/streampipes/endpoint.go
- streampipes-client-go/streampipes/internal/serializer/deserializer.go
- streampipes-client-go/streampipes/internal/util/streampipes_api_path_test.go
- streampipes-client-go/streampipes/model/streampipes_version/versions.go
- streampipes-client-go/streampipes/streampipes_client.go
- streampipes-client-go/streampipes/streampipes_version_api.go
> feat : add versionsApi in Go client

- .github/pr-labeler-config.yml
> ci : add a go pr-label 

- streampipes-extensions/streampipes-processors-transformation-jvm/pom.xml
- streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/booloperator/counter/TestBooleanCounterProcessor.java
> #2545 migrated TestBooleanCounterProcessor parameterized test to junit5

- ui/src/app/pipelines/pipelines.module.ts
> fix(#2748): Add mat icon module to pipeline module

- ui/src/app/profile/profile.module.ts
Add the `MatTableModule` to the profile module to properly render existing API keys.
> fix: Add MatTableModule to profile module

- streampipes-model-client/src/main/java/org/apache/streampipes/model/client/user/ChangePasswordRequest.java
- streampipes-model-client/src/main/java/org/apache/streampipes/model/client/user/JwtAuthenticationResponse.java
- streampipes-model-client/src/main/java/org/apache/streampipes/model/client/user/LoginRequest.java
- streampipes-model-client/src/main/java/org/apache/streampipes/model/client/user/PermissionEntry.java
- streampipes-model-client/src/main/java/org/apache/streampipes/model/client/user/RawUserApiToken.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/Authentication.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/UserResource.java
- streampipes-user-management/src/main/java/org/apache/streampipes/user/management/service/TokenService.java
- streampipes-user-management/src/main/java/org/apache/streampipes/user/management/util/TokenUtil.java
- ui/projects/streampipes/platform-services/src/lib/model/gen/streampipes-model-client.ts
- ui/projects/streampipes/platform-services/src/lib/model/gen/streampipes-model.ts
Clean up some model classes by switching from classes to records.
> refactor: convert model classes to records 

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/influx/DataLakeInfluxQueryBuilder.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/querybuilder/FilterCondition.java
- streampipes-data-explorer/src/test/java/org/apache/streampipes/dataexplorer/param/WhereStatementParamsTest.java
> refactor: change `FilterCondition` class to record

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/writer/ConfiguredCsvOutputWriter.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/writer/ConfiguredJsonOutputWriter.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/writer/item/CsvItemGenerator.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/writer/item/JsonItemGenerator.java
- streampipes-data-explorer/src/test/java/org/apache/streampipes/dataexplorer/query/writer/item/TestCsvItemGenerator.java
- streampipes-data-explorer/src/test/java/org/apache/streampipes/dataexplorer/query/writer/item/TestItemGenerator.java
- streampipes-data-explorer/src/test/java/org/apache/streampipes/dataexplorer/query/writer/item/TestJsonItemGenerator.java
Rename classes to better align with their parent class
> refactor: align item generator class names with parent class

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/AutoAggregationHandler.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataExplorerQueryExecutor.java
> refactor: minor code & logging improvements

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/writer/ConfiguredJsonOutputWriter.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/writer/item/JsonItemGenerator.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/writer/item/JsonItemWriter.java
- streampipes-data-explorer/src/test/java/org/apache/streampipes/dataexplorer/query/writer/item/TestJsonItemWriter.java
> refactor: replace gson by jackson

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataExplorerQueryExecutor.java
> fix: add proper logger usage

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/influx/DataExplorerInfluxQueryExecutor.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/DeleteQueryParams.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/ProvidedRestQueryParamConverter.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/SelectQueryParams.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/model/LimitClauseParams.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/model/OffsetClauseParams.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/model/SelectClauseParams.java
> refactor: convert param classes into records

- .github/workflows/pr-validation.yml
> ci: use macos13 to have all python versions available

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataExplorerQueryManagement.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/influx/DataExplorerInfluxQueryExecutor.java
> refactor: move influx specific implementations to `DataExplorerInfluxQueryExecutor`

- streampipes-data-explorer-commons/pom.xml
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataExplorerSchemaManagement.java
> refactor: remove direct usage of couchDB client

- .github/workflows/pr-validation.yml
> ci: enable `macos-latest` for Python unit tests again

- streampipes-ts-store-iotdb/src/main/java/org/apache/streampipes/ts/store/iotdb/MeasureNameSanitizerIotDb.java
- streampipes-ts-store-iotdb/src/test/java/org/apache/streampipes/ts/store/iotdb/sanitize/MeasureNameSanitizerIotDbTest.java
> feat: add measurement sanitizer for IoTDB

- ui/src/app/connect/components/adapter-configuration/adapter-settings/adapter-deployment-settings/adapter-deployment-settings.component.ts
- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly.component.ts
- ui/src/app/editor/components/pipeline-element-options/pipeline-element-options.component.html
- ui/src/app/editor/components/pipeline-element-options/pipeline-element-options.component.ts
- ui/src/app/editor/components/pipeline/pipeline.component.ts
- ui/src/app/editor/dialog/compatible-elements/compatible-elements.component.ts
- ui/src/app/editor/model/editor.model.ts
- ui/src/app/editor/services/jsplumb.service.ts
- ui/src/app/editor/services/object-provider.service.ts
> fix(#2815): Fix pipeline validation in UI

- streampipes-extensions/streampipes-connectors-opcua/src/main/resources/org.apache.streampipes.sinks.databases.jvm.opcua/documentation.md
> docs: fix OPC-UA sink documentation

- streampipes-extensions/streampipes-processors-filters-siddhi/pom.xml
- streampipes-extensions/streampipes-processors-filters-siddhi/src/test/java/org/apache/streampipes/processors/siddhi/trend/TestTrendProcessor.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/generator/SiddhiAppGenerator.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/model/EventPropertyDef.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/utils/SiddhiUtils.java
> fix(#2836): Sanitize blank space in Siddhi queries

- streampipes-client-python/mkdocs.yml
While browsing the StreamPipes Python client documentation site, I noticed that the favicon wasn't showing up right. I discovered that outdated image hyperlinks in the MkDocs configuration file were the cause.
I updated the config and rebuilt the site locally, and now the favicon displays properly.
no
no
> fix: Fix streampipes client python site config

- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/generator/StatelessTransformationRuleGeneratorVisitor.java
> fix StatelessTransformationRuleGeneratorVisitor set rule mode

- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/convert/ToTransformedSchemaConverter.java
step1
mark as timestamp and value transformation se Data Number seconds
step2
timestamp fileder scope is header
step3
edit adapter 
timestamp fileder scope becames measurement
no
no
> fix ToTransformedSchemaConverter set HEADER_PROPERTY

- streampipes-client-python/mkdocs.yml
This pull request enhances the python client documentation site by displaying inherited methods along with their respective docstrings. This improvement aims to provide users with a more comprehensive understanding of the library's functionality without needing to navigate away to parent class documentation.
Additional changes include linting the YAML configuration files to improve readability and maintain coding standards.
- Current Display:
- Updated Display:
no
no
> feat(#963): Display inherited methods and docstrings in client python

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/FileReplayAdapter.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/resources/org.apache.streampipes.connect.iiot.adapters.oi4/documentation.md
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/resources/org.apache.streampipes.connect.iiot.protocol.stream.file/documentation.md
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/resources/org.apache.streampipes.connect.iiot.protocol.stream.file/strings.en
- ui/cypress/README.md
- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/cypress/tests/adapter/rules/schemaRules.smoke.spec.ts
- ui/cypress/tests/adapter/rules/streamRules.spec.ts
- ui/cypress/tests/adapter/rules/valueRules.ts
> fix(#2856): improve handling of invalid UNIX timestamps

- streampipes-client-python/mkdocs.yml
The `docs/scripts/gen_ref_pages.py` script should not be directly configured in the docs directory. Because MKDocs creates web pages for all content in the docs directory by default, and the mkdocs-jupyter plugin recognizes and converts it into a notebook page.
This results in the gen_ref_pages.py script content being inappropriately displayed in the official documentation.
We can currently view the script converted into a web page by manually accessing the following link:
<https://streampipes.apache.org/docs/docs/python/latest/scripts/gen_ref_pages/>
Additionally, this page is not indexed in the navigation bar and can only be accessed by manually entering the link.
I believe displaying this script in the official documentation is not the intended outcome. After PR fixes the build results …
> fix: remove gen_ref_pages page from python client docs

- installer/k8s/README.md
> Docs: Modify the UI sample port of K8S

- streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/DataLakeMeasurementCounterInflux.java
- streampipes-data-explorer-iotdb/src/main/java/org/apache/streampipes/dataexplorer/iotdb/DataExplorerIotDbQueryExecutor.java
- streampipes-data-explorer-iotdb/src/main/java/org/apache/streampipes/dataexplorer/iotdb/DataExplorerManagerIotDb.java
- streampipes-data-explorer-iotdb/src/main/java/org/apache/streampipes/dataexplorer/iotdb/DataLakeMeasurementCounterIotDb.java
- streampipes-data-explorer-iotdb/src/main/java/org/apache/streampipes/dataexplorer/iotdb/IotDbPropertyConverter.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataLakeMeasurementCounter.java
Implement the ability to count the number of events for a measurement.
This is used within StreamPipes' UI.
> feat: implement measurement counting for IoTDB

- pom.xml
Remove OWASP dependency plugin in favor of our regular GitHub Actions check. See #2267 and #2604 
> chore: remove OWASP plugin dependency

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineElementAsset.java
fixes #376 
Enables the option to view the adapter documentation in the detail view.
Previous:
Now:
> fix: correctly retrieve documentation for asset overview

- .github/ISSUE_TEMPLATE/doc_website_issue_report.yml
- Updated the broken link in the Documentation/Website issue template <https://streampipes.apache.org/docs/index.html>
- Added a new option `StreamPipes Python Documentation`
no
no
> fix: Correct broken link in the issue report template

- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/convert/ToTransformedSchemaConverter.java
step1
step2
step3
update adapter
Wrong parameter additionalMetadata result from /streampipes-backend/api/v2/connect/master/guess/schema api return
no
no
> fix timestampTranfsformationRuleDescription metadata map

- streampipes-client-python/mkdocs.yml
This pull request includes one fix and two features. I have combined these all three improvements into this single PR for submission. Please let me know if there are any suggested changes~
I noticed that although `edit_uri` is set in the configuration file, the `content.action.edit` function is not enabled, which means the edit document button is not displayed.
Additionally, the `content.action.view` (https://squidfunk.github.io/mkdocs-material/upgrade/?h=content+action+view#contentaction) function often appears alongside the `edit` function. I have not enabled this view feature yet, as I am unsure if it aligns with the original intent.
Enabling this feature will allow users to copy code snippets from the document with a single click. This facilitates execution or further editing. …
> feats: add more convenient features for python client docs

- .github/pr-labeler-config.yml
> ci: improve PR labeler config for documentation

- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/extractor/AbstractParameterExtractor.java
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-tree-input.component.html
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-tree-input.component.scss
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-tree-input.component.ts
Fix #2862 so that direct children of each node can be selected as well when working with the OPC-UA adapter and other components supporting the tree static properties.
In addition, add a minor layout improvement so that the tree view can be expanded.
> fix(#2862): Support children selection in tree view

- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/SupportsNestedTransformationRule.java
- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/transform/schema/DeleteTransformationRule.java
- streampipes-connect-shared/src/test/java/org/apache/streampipes/connect/shared/preprocessing/transform/schema/DeleteTransformationRuleTest.java
- ui/cypress/tests/adapter/rules/deleteTransformationRule.spec.ts
> fix(#2886): Fix the deletion of nested properties in connect

- pom.xml
- streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/projection/ProjectionProcessor.java
- streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/websocket/SocketServer.java
- streampipes-extensions/streampipes-sinks-brokers-jvm/src/main/java/org/apache/streampipes/sinks/brokers/jvm/websocket/WebsocketServerSink.java
- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/runtime/StandaloneEventProcessorRuntime.java
- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/runtime/StandaloneEventSinkRuntime.java
> fix(#2890): Properly cleanup WS connection

- streampipes-client-python/Makefile
- streampipes-client-python/streampipes/endpoint/api/version.py
```
mypy.....................................................................Failed
- hook id: mypy
- duration: 5.81s
- exit code: 1
Success: no issues found in 5 source files
Success: no issues found in 5 source files
Success: no issues found in 5 source files
Success: no issues found in 5 source files
Success: no issues found in 5 source files
Success: no issues found in 5 source files
Success: no issues found in 5 source files
tests\client\test_versions.py:47: error: "Resource" has no attribute
"backend_version"  [attr-defined]
self.assertEqual("development", result.backend_version)
^~~~~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 5 source files)
Success: no issues found in 5 source files
Success: no issues found in 5 source files
Success: no issues found in 5 source files …
```
> fix: Resolve python client mypy failed in pre-commit

- ui/src/app/data-explorer/components/designer-panel/visualisation-settings/data-explorer-visualisation-settings.component.ts
- ui/src/app/data-explorer/components/widget-view/abstract-widget-view.directive.ts
- ui/src/app/data-explorer/components/widget-view/grid-view/data-explorer-dashboard-grid.component.ts
- ui/src/app/data-explorer/components/widget-view/slide-view/data-explorer-dashboard-slide-view.component.ts
- ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.ts
- ui/src/app/data-explorer/components/widgets/base/echarts-widget.component.ts
- ui/src/app/data-explorer/components/widgets/time-series-chart/config/time-series-chart-widget-config.component.ts
- ui/src/app/data-explorer/components/widgets/time-series-chart/sp-timeseries-renderer.service.ts
- ui/src/app/data-explorer/components/widgets/utils/data-zoom-config/data-zoom-config.component.ts
- ui/src/app/data-explorer/components/widgets/utils/select-axis-options/select-axis-options.component.ts
- ui/src/app/data-explorer/registry/data-explorer-widget-registry.ts
Improve widget rendering to ensure that 0.93.0 widgets are properly displayed in the new release.
> fix: Improve backwards compatibility of data explorer widgets

- ui/projects/streampipes/shared-ui/src/lib/components/sp-label/sp-label.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/sp-label/sp-label.component.scss
- ui/projects/streampipes/shared-ui/src/lib/components/sp-label/sp-label.component.ts
Improve styling of the label component and add a `small` input property to render labels in a smaller size.
> style: Improve layout of label UI component

- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/Init.java
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__GenericAdapter.java
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__SpecificAdapter.java
- streampipes-sdk-bundle/pom.xml
Generating an jvm extension with the current archetype leads to a project with some import errors.
The missing pulsar dependency is added and some imports are changed.
Closes #2906 
PR introduces a breaking change: no
PR introduces a deprecation: no
> [#2906] Fix some imports in jvm archetype

- ui/cypress/tests/adapter/editAdapterSettingsAndPipeline.spec.ts
> fix: Add wait time to cypress adapter modification test

- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/msteams/MSTeamsSink.java
In the MS Teams sink, support a proxy configuration provided via the `http.proxyHost` JVM flag
> feat: Support proxy settings in MS Teams sink

- ui/src/app/editor/components/pipeline/pipeline.component.ts
> fix(#2916): Fix pipeline validation

- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/locales/LabelGenerator.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/NotificationsExtensionModuleExport.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/migrations/MsTeamsSinkMigrationV1.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/msteams/MSTeamsSink.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/resources/org.apache.streampipes.sinks.notifications.jvm.msteams/strings.en
- streampipes-model/src/main/java/org/apache/streampipes/model/graph/DataProcessorInvocation.java
- streampipes-model/src/main/java/org/apache/streampipes/model/graph/DataSinkInvocation.java
> feat(#2914): Add proxy configuration to Teams sink

- streampipes-platform-services/src/main/java/org/apache/streampipes/ps/DataLakeImageResource.java
- ui/src/app/data-explorer/components/widgets/image/image-bar/image-bar-preview/image-bar-preview.component.html
- ui/src/app/data-explorer/components/widgets/image/image-bar/image-bar-preview/image-bar-preview.component.scss
- ui/src/app/data-explorer/components/widgets/image/image-bar/image-bar.component.html
- ui/src/app/data-explorer/components/widgets/image/image-container/image-container.component.html
- ui/src/app/data-explorer/components/widgets/image/image-container/image-container.component.scss
- ui/src/app/data-explorer/components/widgets/image/image-container/image-container.component.ts
- ui/src/app/data-explorer/components/widgets/image/image-viewer/image-viewer.component.html
- ui/src/app/data-explorer/components/widgets/image/image-widget.component.ts
- ui/src/app/data-explorer/data-explorer.module.ts
Fix a bug which prevented images in the data explorer to be displayed.
> fix: Image rendering in data explorer

- streampipes-extensions/streampipes-processors-image-processing-jvm/src/main/java/org/apache/streampipes/processors/imageprocessing/jvm/ImageProcessingExtensionModuleExport.java
- streampipes-extensions/streampipes-processors-image-processing-jvm/src/main/java/org/apache/streampipes/processors/imageprocessing/jvm/processor/commons/ImageTransformer.java
- streampipes-extensions/streampipes-processors-image-processing-jvm/src/main/java/org/apache/streampipes/processors/imageprocessing/jvm/processor/imageenrichment/ImageEnrichmentProcessor.java
- streampipes-extensions/streampipes-processors-image-processing-jvm/src/main/java/org/apache/streampipes/processors/imageprocessing/jvm/processor/migration/ImageEnrichmentProcessorMigrationv1.java
Fix the image enrichment processor to avoid a StackOverflowError and add the current timestamp to the output event.
> fix: Add timestamp to Image enricher, fix SO error

- RELEASE_NOTES.md
Add missing release notes to RELEASE_NOTES.md on dev
> Add versions 0.93.0 and 0.95.0 to release notes

- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/serializer/CouchDbJsonSerializer.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/serializer/GsonSerializer.java
> refactor(#2933): Rename class JsonLdSerializer to CouchDbJsonSerializer

- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/serializer/GsonSerializer.java
- streampipes-storage-couchdb/src/test/java/org/apache/streampipes/storage/couchdb/serializer/TestGsonSerializer.java
This PR removes some methods in the `GsonSerializer` that are no longer used.
> refactor: Remove unused methods from the GsonSerializer

- streampipes-extensions/streampipes-connectors-plc/pom.xml
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/PlcConnectorsModuleExport.java
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/GenericAdapterGenerator.java
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/generic/GenericPlc4xAdapter.java
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/generic/config/AdapterConfigurationProvider.java
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/generic/connection/ContinuousPlcRequestReader.java
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/generic/connection/OneTimePlcRequestReader.java
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/s7/Plc4xS7Adapter.java
> chore: Improve connection handling of PLC adapters

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/FileReplayAdapter.java
> refactor: Add exception message to adapter exception

- streampipes-service-core-minimal/pom.xml
- streampipes-service-core/pom.xml
Skip deployment of fat jars to Maven for the `streampipes-service-core` and `streampipes-service-core-minimal` modules.
> feat: Skip deployment of core services fat jars

- .github/workflows/go-client.yml
- streampipes-client-go/examples/main.go
- streampipes-client-go/streampipes/data_lake_dashboard_api.go
- streampipes-client-go/streampipes/data_lake_measure_api.go
- streampipes-client-go/streampipes/data_lake_widget_api.go
- streampipes-client-go/streampipes/endpoint.go
- streampipes-client-go/streampipes/functions_api.go
- streampipes-client-go/streampipes/internal/serializer/deserializer.go
- streampipes-client-go/streampipes/model/data_lake/data_series.go
- streampipes-client-go/streampipes/pipeline_api.go
- streampipes-client-go/streampipes/streampipes_client.go
- streampipes-client-go/streampipes/streampipes_version_api.go
- streampipes-client-go/streampipes/user_api.go
Introduce the GoImports tool to automatically update and organize import statements, and format the code according to the gofmt standard style.
no
no
> feat: Add GoImports to go client in CI

- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/modbus/Plc4xModbusAdapter.java
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/s7/config/ConfigurationParser.java
> fix(#2976): Support PLC4X datatypes

- ui/src/app/connect/components/adapter-configuration/adapter-configuration.component.html
- ui/src/app/connect/components/adapter-configuration/adapter-configuration.component.ts
- ui/src/app/connect/components/data-marketplace/adapter-description/adapter-description.component.html
- ui/src/app/connect/components/data-marketplace/adapter-description/adapter-description.component.scss
- ui/src/app/connect/components/data-marketplace/adapter-description/adapter-description.component.ts
- ui/src/app/connect/components/data-marketplace/data-marketplace.component.html
- ui/src/app/connect/connect.module.ts
- ui/src/app/connect/dialog/adapter-documentation/adapter-documentation-dialog.component.html
- ui/src/app/connect/dialog/adapter-documentation/adapter-documentation-dialog.component.ts
> feat(#2979): Add documentation buttons to adapter view

- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/DatatypeUtils.java
- streampipes-connect-shared/src/test/java/org/apache/streampipes/connect/shared/preprocessing/transform/DatatypeUtilsTest.java
- ui/cypress/tests/adapter/fileStream.smoke.spec.ts
This PR fixes the unit timestamp conversion rule within adapters.
Therefore, it changed the implementation of `DatatypeUtils` convertValue.
> refactor(#2964): Fix unix timestamp conversion for integer values

- ui/cypress/tests/adapter/fileStream.smoke.spec.ts
- ui/src/app/connect/dialog/edit-event-property/components/edit-value-transformation/edit-timestamp-property/edit-timestamp-property.component.html
- ui/src/app/connect/dialog/edit-event-property/components/edit-value-transformation/edit-timestamp-property/edit-timestamp-property.component.ts
Activates the e2e test and fixes the error that the timestamp rule is not preselected in the UI.
> fix(#2997): Fix default selection for timestamp rule

- .github/workflows/extensions-docs.yml
- .github/workflows/pypi-deployment.yml
- .github/workflows/python-docs.yml
`actions/upload-artifact@v4` <https://github.com/actions/upload-artifact>
> actions/upload-artifact@v3 is scheduled for deprecation on **November 30, 2024**. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) Similarly, v1/v2 are scheduled for deprecation on **June 30, 2024**. Please update your workflow to use v4 of the artifact actions. This deprecation will not impact any existing versions of GitHub Enterprise Server being used by customers.
no
no
> fix: Update GitHub Actions artifact

- ui/src/app/configuration/general-configuration/general-configuration.component.ts
Properly initialize general config in UI.
> fix: Use link settings from config

- ui/projects/streampipes/shared-ui/src/lib/components/sp-table/sp-table.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/sp-table/sp-table.component.scss
- ui/projects/streampipes/shared-ui/src/lib/components/sp-table/sp-table.component.ts
- ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
- ui/projects/streampipes/shared-ui/src/public-api.ts
- ui/src/app/assets/assets.module.ts
- ui/src/app/assets/components/asset-overview/asset-overview.component.html
- ui/src/app/assets/components/asset-overview/asset-overview.component.scss
- ui/src/app/connect/components/existing-adapters/existing-adapters.component.html
- ui/src/app/connect/components/existing-adapters/existing-adapters.component.scss
- ui/src/app/connect/components/existing-adapters/existing-adapters.component.ts
- ui/src/app/dashboard/components/overview/dashboard-overview.component.html
- ui/src/app/dashboard/components/overview/dashboard-overview.component.scss
- ui/src/app/data-explorer/components/overview/data-explorer-dashboard-overview.component.html
- ui/src/app/data-explorer/components/overview/data-explorer-dashboard-overview.component.scss
- ui/src/app/files/components/file-overview/file-overview.component.html
- ui/src/app/files/components/file-overview/file-overview.component.ts
- ui/src/app/files/files.component.html
- ui/src/app/pipelines/components/functions-overview/functions-overview.component.html
- ui/src/app/pipelines/components/pipeline-overview/pipeline-overview.component.html
- ui/src/app/pipelines/components/pipeline-overview/pipeline-overview.component.scss
- ui/src/app/pipelines/components/pipeline-overview/pipeline-overview.component.ts
- ui/src/app/pipelines/pipelines.component.html
Harmonize the style of the resource overview tables across all views by introducing a reusable table component.
> Harmonize overview tables

- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/exception-details-dialog/exception-details-dialog.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/exception-details-dialog/exception-details-dialog.component.ts
- ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/exception-details/exception-details.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/exception-details/exception-details.component.scss
- ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/exception-details/exception-details.component.ts
- ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
- ui/projects/streampipes/shared-ui/src/public-api.ts
- ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.html
- ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.ts
- ui/src/app/connect/dialog/adapter-started/adapter-started-success/adapter-started-success.component.html
- ui/src/app/connect/dialog/adapter-started/adapter-started-success/adapter-started-success.component.ts
rendering of adapter errors
Fixes #3010 
> fix(#3010): Add exception details component to harmonize error

- .github/workflows/osv-scanner.yml
1. Fix incorrect configuration about OSV Scanner workflow committer
- Previous: https://github.com/apache/streampipes/pull/2909
- After correction:
2. Update the GitHub Action `peter-evans/create-pull-request` version.
3. Fix `echo -e` command to allow for newline output.
4. Add workflow_dispatch trigger to OSV Scanner workflow.
no
no
> fix: Fix OSV Scanner commit workflow 

- ui/cypress/tests/connect/fileStream.spec.ts
- ui/src/app/core-ui/static-properties/static-file-input/static-file-input.component.html
- ui/src/app/core-ui/static-properties/static-file-input/static-file-input.component.ts
> fix(#3014): Add test and fix edit of file static property

- ui/cypress/tests/userManagement/testGroupManagement.spec.ts
> fix: fix e2e test for group management

- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/builder/AbstractConfigurablePipelineElementBuilder.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/builder/AbstractProcessingElementBuilder.java
> refactor(#3023): Remove deprecated API that does not use the Label class

- streampipes-pipeline-management/src/test/java/org/apache/streampipes/manager/selector/TestSelectorUtils.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/helpers/Labels.java
- streampipes-sdk/src/test/java/org/apache/streampipes/sdk/helpers/LabelsTest.java
> refactor(#3021): Clean up class Labels

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/oi4/Oi4Adapter.java
The OI4 adapter should support multiple sensors of the same type from a single source ID.
> fix: Support multiple sensors of the same type in OI4 adapter

- streampipes-client-python/streampipes/function_zoo/river_function.py
- streampipes-client-python/streampipes/functions/utils/data_stream_generator.py
- streampipes-client-python/tests/functions/test_function_handler.py
- streampipes-client-python/tests/functions/test_river_function.py
- Fixes #3040 
- A stream ID is now required when creating a data stream.
- The topic name is now fixed and includes the stream ID, ensuring data is sent correctly on function restart.
> fix(#3040): Change random topic to fixed with stream id

- streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/stringoperator/counter/TestStringCounterProcessor.java
Fix #2778.
Merge this branch into the branch `2779-teststringtostateprocessor` before this is merged to `dev`
> refactor(#2778): Fix junit test TestStringCounterProcessor

- streampipes-commons/src/main/java/org/apache/streampipes/commons/constants/DefaultEnvValues.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/constants/GlobalStreamPipesConstants.java
> refactor: Remove unused environment variables

- streampipes-extensions/streampipes-processors-enricher-jvm/pom.xml
- streampipes-extensions/streampipes-processors-enricher-jvm/src/main/java/org/apache/streampipes/processors/enricher/jvm/processor/sizemeasure/SizeMeasureProcessor.java
- streampipes-extensions/streampipes-processors-enricher-jvm/src/test/java/org/apache/streampipes/processors/enricher/jvm/processor/sizemeasure/TestSizeMeasureProcessor.java
> refactor(#2754): Fix test for SizeMeasureProcessor

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/model/WhereClauseParams.java
- streampipes-data-explorer/src/test/java/org/apache/streampipes/dataexplorer/param/WhereStatementParamsTest.java
- ui/src/app/data-explorer/components/widgets/table/table-widget.component.html
- ui/src/app/data-explorer/components/widgets/table/table-widget.component.ts
- ui/src/app/data-explorer/echarts-renderer/echarts-dataset-generator.service.ts
> fix(#3055): Fix widget rendering in grouping mode

- streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/processor/stringoperator/timer/StringTimerProcessor.java
- streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/stringoperator/timer/TestStringTimerProcessor.java
- streampipes-test-utils-executors/src/main/java/org/apache/streampipes/test/executors/Approx.java
- streampipes-test-utils-executors/src/main/java/org/apache/streampipes/test/executors/ProcessingElementTestExecutor.java
> refactor(#2764): Fix unit test case for StringTimerProcessor

- streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/datetime/TestDateTimeFromStringProcessor.java
> refactor(#2777): Fix test case for DateTimeFromStringProcessor

- installer/cli/deploy/standalone/opcua/docker-compose.yml
> refactor: Remove unused configuration option for opc ua server

- docker-compose.yml
- ui/cypress/support/builder/AdapterBuilder.ts
- ui/cypress/tests/thirdparty/Mqtt.spec.ts
> refactor: Reactivate mqtt cypress test

- docker-compose.yml
Remove duplicate `logging` configuration in docker-compose.yml.
Mapping keys must be unique.
no
no
> fix: remove duplicate logging config in docker-compose

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataLakeMeasurementCounter.java
- streampipes-data-explorer/src/test/java/org/apache/streampipes/dataexplorer/query/DataLakeMeasurementCounterTest.java
- streampipes-data-explorer/src/test/java/org/apache/streampipes/dataexplorer/query/DataLakeMeasurementCounterTestImpl.java
- streampipes-platform-services/src/main/java/org/apache/streampipes/ps/DataLakeMeasureResourceV4.java
- ui/projects/streampipes/platform-services/src/lib/apis/datalake-rest.service.ts
- Fixes a NullPointerException when the provided measurement name does not exist
- Adds unit tests to cover this scenario
- Renames the REST API endpoint for retrieving event counts of measurements for better clarity
- Updates the documentation to reflect the functionality in the REST endpoint
```
GET /api/v4/datalake/measure
```
**Parameters:**
- `filter` (optional): List of measurement names
```
GET /api/v4/datalake/measure/count
```
**Parameters:**
- `measurementNames`: List of measurement names to return the count
> fix(#3072): nullpointer in datalakemeasureresourcev4getdatalakeinfos

- ui/projects/streampipes/shared-ui/src/lib/dialog/base-dialog/base-dialog.service.ts
> fix(#3076): Correctly close dialogs when use clicks somewhere on the screen

- ui/.gitignore
- ui/.prettierignore
- ui/deployment/app-routing.module.mst
- ui/deployment/app.module.mst
- ui/deployment/modules.yml
- ui/deployment/prebuild.js
- ui/src/bootstrap.ts
Fix #3080 by removing the prefix `ng5`.
> fix(#3080): Remove ng5 prefix in ui prebuild script

- ui/projects/streampipes/platform-services/src/lib/apis/adapter-monitoring.service.ts
- ui/projects/streampipes/platform-services/src/lib/apis/adapter.service.ts
> refactor: Remove unused code

- streampipes-commons/src/main/java/org/apache/streampipes/commons/environment/parser/OAuthConfigurationParser.java
- streampipes-commons/src/test/java/org/apache/streampipes/commons/environment/parser/OAuthConfigurationParserTest.java
This PR is based on the branch 3074-support-third-party-sign-in and refactors the parser for environment variables.
> refactor(#3074): Refactor OAuthConfigurationParser

- streampipes-client/src/main/java/org/apache/streampipes/client/api/FileApi.java
> refactor(#3084): Remove deprecated method getFileContent

- .github/workflows/cypress-test.yml
- .github/workflows/pr-validation.yml
Fix the docker compose commands in the Github Actions workflows.
> fix: Modify docker compose command in workflow

- streampipes-model/src/main/java/org/apache/streampipes/model/graph/DataProcessorInvocation.java
- streampipes-model/src/main/java/org/apache/streampipes/model/graph/DataSinkInvocation.java
Fix a bug which caused the pipeline element version to get lost when transforming the model description to an invocable element.
> fix(#3097): Avoid that pipeline element version gets lost

- ui/deployment/apps.ts
> fix(#3109): Remove asset dashboards from available apps service

- streampipes-messaging-kafka/src/main/java/org/apache/streampipes/messaging/kafka/SpKafkaConsumer.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/operations/Operations.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/preview/ActivePipelinePreviews.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/preview/PipelinePreview.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/runtime/DataStreamRuntimeInfoProvider.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/runtime/RateLimitedRuntimeInfoProvider.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineElementPreview.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineElementRuntimeInfo.java
- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/src/app/connect/dialog/adapter-started/adapter-started-preview/adapter-started-preview.component.html
- ui/src/app/connect/dialog/adapter-started/adapter-started-preview/adapter-started-preview.component.ts
- ui/src/app/connect/services/rest.service.ts
- ui/src/app/core-ui/pipeline-element-runtime-info/pipeline-element-runtime-info.component.ts
- ui/src/app/editor/components/pipeline-element-preview/pipeline-element-preview.component.html
- ui/src/app/editor/components/pipeline-element-preview/pipeline-element-preview.component.scss
- ui/src/app/editor/components/pipeline-element-preview/pipeline-element-preview.component.ts
- ui/src/app/editor/components/pipeline/pipeline.component.html
- ui/src/app/editor/components/pipeline/pipeline.component.ts
- ui/src/app/editor/services/editor.service.ts
- ui/src/app/services/live-preview.service.ts
Replace the polling-based provision of stream and pipeline preview with a streaming approach to improve performance and avoid that data gets lost when connections are opened and closed multiple times.
> chore: Provide adapter and pipeline preview as stream

- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/generic/connection/OneTimePlcRequestReader.java
- streampipes-model/src/main/java/org/apache/streampipes/model/monitoring/SpLogMessage.java
- streampipes-model/src/test/java/org/apache/streampipes/model/monitoring/SpLogMessageTest.java
> fix(#3117): Remove connection after plc data is read

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineMonitoring.java
- ui/cypress/tests/connect/editAdapterSettingsAndPipeline.spec.ts
- ui/projects/streampipes/platform-services/src/lib/apis/pipeline-monitoring.service.ts
- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly-drawing-area/pipeline-assembly-drawing-area.component.ts
- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly.component.ts
- ui/src/app/editor/components/pipeline-element-options/pipeline-element-options.component.html
- ui/src/app/editor/components/pipeline-element-options/pipeline-element-options.component.ts
- ui/src/app/editor/components/pipeline/dropped-pipeline-element/dropped-pipeline-element.component.html
- ui/src/app/pipeline-details/components/pipeline-details-toolbar/pipeline-details-toolbar.component.html
- ui/src/app/pipeline-details/components/pipeline-details-toolbar/pipeline-details-toolbar.component.ts
- ui/src/app/pipeline-details/components/preview/pipeline-preview.component.html
- ui/src/app/pipeline-details/components/preview/pipeline-preview.component.ts
- ui/src/app/pipeline-details/pipeline-details.component.html
- ui/src/app/pipeline-details/pipeline-details.component.ts
- ui/src/app/pipelines/components/pipeline-overview/pipeline-overview.component.html
The live preview can be opened in the pipeline details section as well.
@tenthe I also addressed your comments from PR #3114 and fixed one failing e2e test.
> feat(#3121): Add live preview to pipeline details

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/simulator/machine/MachineDataSimulator.java
Fixes an issue which caused the machine simulator to randomly crash due to inproper reuse of the event map.
> fix: Avoid machine simulator crash

- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/monitoring/pipeline/ExtensionsLogProvider.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/AdapterMonitoringResource.java
- ui/projects/streampipes/platform-services/src/lib/apis/adapter-monitoring.service.ts
- ui/src/app/connect/components/existing-adapters/existing-adapters.component.ts
Load adapter metrics in the adapter overview section in a single request to improve performance.
> chore: Load adapter metrics in a single request

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterMigrationManager.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/migration/AbstractMigrationManager.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/migration/PipelineElementMigrationManager.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/admin/MigrationResource.java
- streampipes-storage-api/src/main/java/org/apache/streampipes/storage/api/IDataProcessorStorage.java
- streampipes-storage-api/src/main/java/org/apache/streampipes/storage/api/IDataSinkStorage.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/DataProcessorStorageImpl.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/DataSinkStorageImpl.java
> fix(#3131): Perform description migration only for installed extensions

- streampipes-client-python/.pre-commit-config.yaml
- streampipes-client-python/streampipes/client/config.py
- streampipes-client-python/streampipes/endpoint/api/data_lake_measure.py
- streampipes-client-python/streampipes/function_zoo/river_function.py
- streampipes-client-python/streampipes/functions/utils/data_stream_generator.py
- streampipes-client-python/tests/functions/test_function_handler.py
- streampipes-client-python/tests/functions/test_river_function.py
- Bump pre-commit rev.
- Added the `check-toml` hook to verify the configuration file of the Python client.
- Revised the code based on the results from the pre-commit linting.
no
no
> Update pre-commit hooks

- ui/src/app/editor/components/pipeline/pipeline.component.ts
Fix a bug which caused the pipeline editor cache to incorrectly update in case a pipeline element got deleted.
> fix: Properly delete elements from pipeline cache in editor

- ui/projects/streampipes/platform-services/src/lib/apis/pipeline-monitoring.service.ts
- ui/src/app/pipeline-details/pipeline-details.component.ts
Remove the loading bar dependecy from `platform-services`
> Fix loading bar import

- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/transform/schema/CreateNestedTransformationRule.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/rules/schema/CreateNestedRuleDescription.java
- ui/src/app/connect/components/adapter-configuration/schema-editor/event-schema/event-schema.component.html
- ui/src/app/connect/components/adapter-configuration/schema-editor/event-schema/event-schema.component.ts
- ui/src/app/connect/components/adapter-configuration/schema-editor/schema-editor-header/schema-editor-header.component.html
- ui/src/app/connect/components/adapter-configuration/schema-editor/schema-editor-header/schema-editor-header.component.ts
This PR removes the ability to add nested properties in the schema editor of Connect, as well as deprecates this feature on the backend. This change will be removed in our next release, providing users with a transition period to migrate their instances.
> feat(#3151): Remove add nested property button

- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/cypress/support/utils/userInput/StaticPropertyUtils.ts
Previously, all e2e tests included a 2-second wait before starting adapter configuration to ensure correct rendering of static properties.
This PR removes the fixed wait time and implements a dynamic wait for the static property selectors, improving test execution speed.
As most tests involve an adapter, this change is expected to reduce overall execution time. 
However, this change may introduce flakiness in the tests, so it must be monitored. If issues arise, we will fix the flaky tests in the future.
> refactor: Remove wait for 2 seconds in adapter creation

- ui/cypress/support/utils/ErrorMessageUtils.ts
- ui/cypress/tests/connect/opcua/opcAdapterConfiguration.spec.ts
- ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/sp-exception-message.component.html
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-runtime-resolvable-tree-input.component.ts
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-tree-input-button-menu/static-tree-input-button-menu.component.html
This PR ensures that the OPC UA nodes are only loaded with a full configuration.
> fix(#3163): Nodes are only reloaded with a full configuration

- ui/src/app/connect/services/static-value-transform.service.ts
> fix(#3160): Change logic of service static-value-transform

- ui/cypress/support/utils/datalake/DataLakeUtils.ts
- ui/cypress/tests/datalake/timeRangeSelectors.spec.ts
…ance in timeRangeSelector test
Add timeout to prevent timeOrderDataView.spec.ts from failing and extend time tolerance in timeRangeSelector.spec.ts.
> Add timeout to selectVisualizationType-function and extend time tolerance in timeRangeSelector test

- ui/cypress/support/utils/datalake/DataLakeUtils.ts
- ui/cypress/tests/datalake/timeOrderDataView.spec.ts
- ui/src/app/data-explorer/components/dashboard/data-explorer-dashboard-panel.component.ts
- ui/src/app/data-explorer/components/data-view/data-explorer-data-view.component.ts
- ui/src/app/data-explorer/data-explorer-panel.can-deactivate.guard.ts
- ui/src/app/data-explorer/data-explorer.module.ts
- ui/src/app/data-explorer/models/dataview-dashboard.model.ts
- ui/src/app/data-explorer/services/data-explorer-detect-changes.service.ts
This change introduces a confirmation dialog that prompts users when they attempt to navigate away from a dashboard or data view in the Data Explorer after making changes. If a user makes changes and tries to leave without saving, the dialog will appear, asking whether they want to discard or save their changes. Conversely, if no changes have been made, the dialog will not be triggered.
To ensure this functionality works as expected, the timeOrderDataView.spec.ts has been updated with new tests that verify the dialog's appearance under the appropriate conditions.
> feat: Add dialog window to confirm that unsaved changes will be discarded

- ui/cypress/support/utils/connect/OpcUaUtils.ts
- ui/cypress/tests/connect/opcua/opcAdapterConfiguration.spec.ts
- ui/cypress/tests/connect/opcua/startAndEditOpcAdapters.spec.ts
- ui/cypress/tests/connect/opcua/staticPropertyTreeNodesTest.ts
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-runtime-resolvable-tree-input.component.ts
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-tree-input-browse-nodes/static-tree-input-browse-nodes.component.ts
This PR optimizes performance for the `RuntimeResolvableTreeInputStaticProperty` in the UI by no longer storing the available nodes in CouchDB.
- Removes nodes from the configuration before sending the adapter description to the backend.
- Cypress tests have been updated to validate the removal of nodes as expected.
- Improved performance by reducing unnecessary data storage in CouchDB.
> fix(#3188): Do not store nodes for RuntimeResolvableTreeInputStaticProperty anymore

- ui/cypress/support/utils/configuration/SiteUtils.ts
- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/cypress/tests/assetManagement/createAsset.spec.ts
- ui/cypress/tests/connect/allAdapterActions.smoke.spec.ts
- ui/cypress/tests/connect/createAdapterWithoutStarting.spec.ts
- ui/src/app/assets/dialog/create-asset/create-asset-dialog.component.html
- ui/src/app/core-ui/pipeline-element-runtime-info/live-preview-table/live-preview-table.component.html
Fix three cypress tests which were failing on dev.
> fix: Various cypress tests

- streampipes-client-python/.pre-commit-config.yaml
- streampipes-client-python/pyproject.toml
- streampipes-client-python/streampipes/endpoint/api/data_lake_measure.py
- streampipes-client-python/streampipes/functions/utils/data_stream_generator.py
- streampipes-client-python/streampipes/model/common.py
- streampipes-client-python/streampipes/model/resource/data_stream.py
1. Migrate command-line tool configurations to `pyproject.toml`. 
This consolidation purpose is to improve the maintainability and DevOps practices by centralizing the configuration.
2. Fix `pyupgrade` command to use `--py38-plus` instead of `--py38`.
Align with the latest version, as the updated README no longer provides the `--py38` option.
no
no
> fix: Migrate command-line tool config to pyproject.toml

- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/PipelineModificationGenerator.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/PipelineVerificationHandlerV2.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/v2/pipeline/AbstractPipelineValidationStep.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/v2/pipeline/IPipelineValidationStep.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/v2/pipeline/PipelineValidationSteps.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/v2/pipeline/PipelineValidator.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/preview/PipelinePreview.java
- ui/projects/streampipes/platform-services/src/lib/model/gen/streampipes-model.ts
- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly-drawing-area/pipeline-assembly-drawing-area.component.ts
- ui/src/app/editor/components/pipeline-element-preview/pipeline-element-preview.component.ts
- ui/src/app/editor/components/pipeline/dropped-pipeline-element/dropped-pipeline-element.component.html
- ui/src/app/services/live-preview.service.ts
Ensure that pipeline elements used in the preview receive their own ID so that running pipelines aren't affected by a preview.
> fix: Assign new elementIds in pipeline preview

- ui/src/app/data-explorer/components/data-view/data-explorer-data-view.component.html
- ui/src/app/data-explorer/components/data-view/data-explorer-data-view.component.scss
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/appearance-settings/data-explorer-widget-appearance-settings.component.html
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-explorer-designer-panel.component.html
- ui/src/app/data-explorer/components/data-view/data-view-toolbar/data-explorer-data-view-toolbar.component.html
- ui/src/app/data-explorer/components/data-view/data-view-toolbar/data-explorer-data-view-toolbar.component.ts
Facilitates modification of the widget name in the Data Explorer by moving the input field for the data view name to the toolbar. Additionally, the appearance of the Data Explorer is simplified by removing duplicate data view names. The toolbar in view mode now also includes a time range selector.
https://github.com/apache/streampipes/issues/3174
> Move data view name input field to toolbar and simplified data explorer appearance

- streampipes-client-go/streampipes/adapter_api.go
- streampipes-client-go/streampipes/internal/serializer/deserializer.go
- streampipes-client-go/streampipes/internal/serializer/serializer.go
- streampipes-client-go/streampipes/model/adapter/adapter_description.go
- streampipes-client-go/streampipes/model/common.go
- streampipes-client-go/streampipes/streampipes_client.go
> feat: add more support for adapter API to Go client

- ui/src/app/data-explorer/components/data-view/data-view-toolbar/data-explorer-data-view-toolbar.component.html
- ui/src/app/data-explorer/components/widgets/traffic-light/config/traffic-light-widget-config.component.html
- ui/src/app/data-explorer/components/widgets/traffic-light/config/traffic-light-widget-config.component.scss
- ui/src/app/data-explorer/components/widgets/traffic-light/config/traffic-light-widget-config.component.ts
- ui/src/app/data-explorer/components/widgets/traffic-light/model/traffic-light-widget.model.ts
- ui/src/app/data-explorer/components/widgets/traffic-light/traffic-light-widget.component.html
- ui/src/app/data-explorer/components/widgets/traffic-light/traffic-light-widget.component.scss
- ui/src/app/data-explorer/components/widgets/traffic-light/traffic-light-widget.component.ts
- ui/src/app/data-explorer/data-explorer.module.ts
- ui/src/app/data-explorer/registry/data-explorer-widget-registry.ts
This commit adds the traffic light widget to the data explorer. While based on the existing dashboard widget, its logic, settings, and design have been adapted. New settings include an option to display the value of the currently selected field within the traffic light. Additionally, the warning range interval is now shown to the user when adjusting settings. Furthermore, the data view toolbar is slightly adjusted.
> Add new traffic light widget to data explorer

- ui/src/app/data-explorer/components/widgets/status/config/status-widget-config.component.html
- ui/src/app/data-explorer/components/widgets/status/config/status-widget-config.component.scss
- ui/src/app/data-explorer/components/widgets/status/config/status-widget-config.component.ts
- ui/src/app/data-explorer/components/widgets/status/model/status-widget.model.ts
- ui/src/app/data-explorer/components/widgets/status/status-widget.component.html
- ui/src/app/data-explorer/components/widgets/status/status-widget.component.scss
- ui/src/app/data-explorer/components/widgets/status/status-widget.component.ts
- ui/src/app/data-explorer/components/widgets/traffic-light/traffic-light-widget.component.ts
- ui/src/app/data-explorer/data-explorer.module.ts
- ui/src/app/data-explorer/registry/data-explorer-widget-registry.ts
This commit introduces a status widget to the data explorer, allowing users to verify data reception within an adjustable time interval. It supports both numerical and boolean data streams: for numerical streams, it indicates if data is being received, while for boolean streams, it shows whether the stream delivers true or false values. Users can configure the time interval for numerical streams and opt to display the last seen timestamp. For boolean streams, they can select fields and customize the status light mapping. Moreover, minor adjustments to the traffic light widget ensure consistency.
> Add status widget to data explorer

- ui/src/app/assets/components/asset-overview/asset-overview.component.ts
Adds a dialog window that prompts confirmation from user when deleting an asset.
> feat: Add dialog window for deletion of assets

- ui/src/app/data-explorer/components/widgets/pie/config/pie-chart-widget-config.component.html
- ui/src/app/data-explorer/components/widgets/pie/config/pie-chart-widget-config.component.ts
- ui/src/app/data-explorer/components/widgets/pie/model/pie-chart-widget.model.ts
- ui/src/app/data-explorer/components/widgets/pie/pie-renderer.service.ts
Adds a slider to the pie chart settings and lets the user transform the pie chart into a doughnut chart by selecting the inner radius with the slider.
> feat: Add option to make doughnut chart out of pie chart

- streampipes-client-python/.pre-commit-config.yaml
Corrected the regular expression in the pre-commit configuration to ensure proper detection of the Python client and prevent unintended checks on other files.
After this correction, we can run pre-commit from the root directory using: `pre-commit run --all-files --config ./streampipes-client-python/.pre-commit-config.yaml`.
It can also use `pre-commit run --all-files` to run it in the `streampipes-client-python` directory.
In addition, I believe that the generic checks like `trailing-whitespace` are beneficial for other files as well. We could consider applying such generic detection pre commit rules to other files to improve overall code quality from the DevOps perspective.
no
no
> fix: Correct regex in pre commit config

- streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/function/StreamPipesFunctionHandler.java
Fix #3257 by making the function deregistration call synchronous.
> fix(#3257): Synchronously trigger deregistration handler

- .github/workflows/osv-scanner.yml
- streampipes-extensions-api/src/main/java/org/apache/streampipes/extensions/api/extractor/IParameterExtractor.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/remote/ContainerProvidedOptionsHandler.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/StaticProperties.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/extractor/AbstractParameterExtractor.java
- streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/function/StreamPipesFunctionHandler.java
- ui/cypress/support/utils/datalake/DataLakeUtils.ts
- ui/cypress/tests/datalake/timeRangeSelectors.spec.ts
- ui/src/app/core-ui/static-properties/static-property.component.html
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-any-input/static-runtime-resolvable-any-input.component.html
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-any-input/static-runtime-resolvable-any-input.component.ts
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-runtime-resolvable-tree-input.component.ts
> fix: Improve handling of runtime-resolved selections

- ui/.lintstagedrc.json
> fix(#3253): Change linting back to check instead of write

- streampipes-model/src/main/java/org/apache/streampipes/model/dashboard/DashboardItem.java
- ui/projects/streampipes/platform-services/src/lib/model/dashboard/dashboard.model.ts
- ui/projects/streampipes/platform-services/src/lib/model/datalake/DateRange.ts
- ui/projects/streampipes/platform-services/src/lib/model/gen/streampipes-model.ts
- ui/src/app/data-explorer/components/time-selector/time-selector-menu/custom-time-range-selection/custom-time-range-selection.component.html
- ui/src/app/data-explorer/components/time-selector/time-selector-menu/time-selector-menu.component.html
- ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.html
- ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.ts
- ui/src/app/data-explorer/components/widgets/base/base-data-explorer-widget.directive.ts
- ui/src/app/data-explorer/dialogs/edit-dashboard/data-explorer-edit-dashboard-dialog.component.html
- ui/src/app/data-explorer/models/dataview-dashboard.model.ts
- ui/src/app/data-explorer/services/time-selection.service.ts
This commit introduces functionality for selecting time ranges for individual widgets on the dashboard. Users can now select different time ranges for their widgets through a time range selector. This feature is available only when the global time settings checkbox is not selected in the dashboard's edit window, ensuring that widget-specific settings can be managed separately from global settings.
> feat: Add time selection menu for single widgets in dashboard

- installer/k8s/README.md
> docs:Modify the README file of K8S and note that the port does not match the document use case

- streampipes-data-explorer-api/src/main/java/org/apache/streampipes/dataexplorer/api/IDataExplorerManager.java
- streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/DataExplorerManagerInflux.java
- streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/PropertyDuplicateFilter.java
- streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/PropertyHandler.java
- streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/TimeSeriesStorageInflux.java
- streampipes-data-explorer-influx/src/test/java/org/apache/streampipes/dataexplorer/influx/PropertyDuplicateFilterTest.java
- streampipes-data-explorer-iotdb/src/main/java/org/apache/streampipes/dataexplorer/iotdb/DataExplorerManagerIotDb.java
- streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/datalake/DataLakeSink.java
- streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/datalake/migrations/DataLakeSinkMigrationV2.java
- streampipes-extensions/streampipes-sinks-internal-jvm/src/main/resources/org.apache.streampipes.sinks.internal.jvm.datalake/documentation.md
- streampipes-extensions/streampipes-sinks-internal-jvm/src/main/resources/org.apache.streampipes.sinks.internal.jvm.datalake/strings.en
- streampipes-extensions/streampipes-sinks-internal-jvm/src/test/java/org/apache/streampipes/sinks/internal/jvm/datalake/migrations/DataLakeSinkMigrationV2Test.java
- ui/src/app/core-ui/static-properties/static-slide-toggle/static-slide-toggle.component.html
- ui/src/app/core-ui/static-properties/static-slide-toggle/static-slide-toggle.component.ts
> feat(#3259): Add duplicate filter to timeseries storage

- ui/src/app/editor/dialog/save-pipeline/save-pipeline-settings/save-pipeline-settings.component.html
- ui/src/app/editor/dialog/save-pipeline/save-pipeline-settings/save-pipeline-settings.component.ts
Add an error message to the pipeline name and description input fields showing the minimum and maximum supported lengths.
> fix(#3252): Add validation error message

- streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/function/FunctionRegistrationHandler.java
> refactor: Add javadoc to class FunctionRegistrationHandler

- streampipes-connect-shared/src/test/java/org/apache/streampipes/connect/shared/preprocessing/transform/value/CorrectionValueTest.java
- streampipes-connect-shared/src/test/java/org/apache/streampipes/connect/shared/preprocessing/transform/value/UnitTransformRuleTest.java
- streampipes-connect-shared/src/test/java/org/apache/streampipes/connect/shared/preprocessing/transform/value/ValueEventTransformerTest.java
> refactor: Refactor unit tests for transformation rules

- ui/src/app/connect/dialog/edit-event-property/components/edit-value-transformation/edit-correction-value/edit-correction-value.component.html
- ui/src/app/connect/dialog/edit-event-property/components/edit-value-transformation/edit-correction-value/edit-correction-value.component.ts
This PR cleans up some code in the component `EditCorrectionValueComponent`
> refactor: Remove unused event emitter from `EditCorrectionValueComponent`

- ui/src/app/assets/components/asset-details/base-asset-details.directive.ts
- ui/src/app/assets/components/asset-details/edit-asset/asset-details-panel/asset-details-basics/asset-details-labels/asset-details-labels.component.html
- ui/src/app/assets/components/asset-details/edit-asset/asset-details-panel/asset-details-basics/asset-details-labels/asset-details-labels.component.ts
- ui/src/app/assets/components/asset-details/edit-asset/asset-details-panel/asset-details-basics/asset-details-site/asset-details-site.component.html
Fix asset location handling to ensure added sites in Configuration/Sites are available for assets. Add a "Manage Sites" button that links directly to site management from asset management. Also, provide an indication that users must create a label before assigning it (#3178).
> fix: Display location for sites in asset management

- ui/cypress/fixtures/connect/compact/machineDataSimulator.yml
- ui/cypress/support/builder/CompactAdapterBuilder.ts
- ui/cypress/support/utils/ProcessingElementTestUtils.ts
- ui/cypress/support/utils/ThirdPartyIntegrationUtils.ts
- ui/cypress/support/utils/connect/CompactAdapterUtils.ts
- ui/cypress/support/utils/connect/ConnectBtns.ts
- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/cypress/support/utils/pipeline/PipelineBtns.ts
- ui/cypress/support/utils/pipeline/PipelineUtils.ts
- ui/cypress/tests/connect/compact/addCompactAdapter.ts
- ui/cypress/tests/connect/deleteAdapterWithMultipleUsers.smoke.spec.ts
- ui/cypress/tests/connect/editAdapterSettingsAndPipeline.spec.ts
- ui/cypress/tests/connect/persistInDataLake.smoke.spec.ts
- ui/cypress/tests/datalake/configuration.smoke.spec.ts
- ui/cypress/tests/experimental/restartStreamPipes/restartStreamPipes1.ts
- ui/cypress/tests/experimental/testJvmArchetype/testJvmArchetype.ts
- ui/cypress/tests/pipeline/pipelineTest.smoke.spec.ts
- ui/cypress/tests/pipeline/updatePipelineTest.smoke.spec.ts
- ui/cypress/tests/pipelineElement/PipelineElementDocumentation.spec.ts
- ui/cypress/tests/pipelineElementConfigurationTemplate/pipelineElementConfigurationTemplate.ts
- ui/cypress/tests/userManagement/testGroupManagement.spec.ts
- ui/cypress/tests/userManagement/testUserRolePipeline.spec.ts
This PR introduces minor refactoring in the testing library for improved code clarity and maintainability. It also adds new tests to validate the correct addition of compact adapters.
> feat(#3298): Add test to validate success path of add compact adapters

- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly-options/pipeline-assembly-options.component.html
- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly-options/pipeline-assembly-options.component.ts
- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly.component.ts
Fix a bug which caused pipeline templates in the pipeline editor to not fully be deleted.
> fix: Properly delete pipeline templates from canvas

- ui/src/app/data-explorer/components/widgets/pie/config/pie-chart-widget-config.component.html
- ui/src/app/data-explorer/components/widgets/pie/config/pie-chart-widget-config.component.ts
- ui/src/app/data-explorer/components/widgets/pie/model/pie-chart-widget.model.ts
- ui/src/app/data-explorer/components/widgets/pie/pie-renderer.service.ts
- ui/src/app/data-explorer/services/color-mapping.service.ts
Adds color mapping functionality for pie charts through a dedicated service, which assigns colors to values to improve chart readability. The service manages adding, removing, and resetting color mappings, and dynamically assigns colors based on a predefined palette. The user is able to change the color palette by using a provided color picker.
> Add color mapping for pie chart

- streampipes-client-go/docs/content/en/docs/getting-started/first-steps.md
- streampipes-client-go/docs/content/en/docs/tutorials/ManageAdapter.md
- streampipes-client-go/docs/content/en/docs/tutorials/ManagePipeline.md
1. Fix the missing front matter in the new added documents. Without the yaml front matter, hugo cannot make the sidebar work correctly.
2. Fixed language markup for code blocks. Provided correct go syntax highlighting for documents.
3. Fixed the title level.
no
no
> Fix: add missing front matter in newly added go client docs

- streampipes-extensions/streampipes-processors-enricher-jvm/src/main/java/org/apache/streampipes/processors/enricher/jvm/processor/math/MathOpProcessor.java
- streampipes-extensions/streampipes-processors-enricher-jvm/src/test/java/org/apache/streampipes/processors/enricher/jvm/processor/math/MathOpProcessorTest.java
> Test:Implement unit tests for pipeline element 'MathOpProcessor'

- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/generic/config/MetadataOptionGenerator.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/CompactPipelineConverter.java
- ui/src/app/core-ui/static-properties/static-one-of-input/static-one-of-input.component.html
fix a minor layout issue when rendering static property groups.
> chore: Fix layout of static property groups

- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.ts
- ui/projects/streampipes/shared-ui/src/lib/services/time-selection.service.ts
- ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.html
- ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.ts
This commit addresses an issue with the time selection menu for configured widgets in the dashboard. The implementation is updated to align with recent changes introduced during the restructuring of the time selection menu, ensuring consistency and improved functionality.
> fix: Time selector menu for widgets in dashboard

- ui/cypress/tests/datalake/widgetDataConfiguration.smoke.spec.ts
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-explorer-designer-panel.component.html
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.html
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.ts
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/field-selection-panel/field-selection-panel.component.ts
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/order-selection-panel/order-selection-panel.component.ts
This changes the default widget in the data view to the table widget. Moreover, the pipeline and measurement names are sorted alphabetically and the order is set to descending by default.
> fix: Set table as default widget type

- ui/cypress/support/utils/connect/OpcUaUtils.ts
> fix(#3369): Add timeout to select node

- ui/package.json
Feat #3376: This updates the package.json scripts for test-cypress-open, test-cypress-smoke, and test-cypress-all to include the necessary environment variables directly. 
> feat(#3376): Add env variables to cypress scripts

- streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/KafkaConnectorsModuleExport.java
- streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/adapter/KafkaProtocol.java
- streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/migration/KafkaAdapterMigrationV2.java
- streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/migration/KafkaSinkMigrationV2.java
- streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/shared/kafka/KafkaConfigExtractor.java
- streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/shared/kafka/KafkaConfigProvider.java
- streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/sink/KafkaPublishSink.java
- streampipes-extensions/streampipes-connectors-kafka/src/main/resources/org.apache.streampipes.connect.iiot.protocol.stream.kafka/strings.en
- streampipes-extensions/streampipes-connectors-kafka/src/main/resources/org.apache.streampipes.sinks.brokers.jvm.kafka/documentation.md
- streampipes-extensions/streampipes-connectors-kafka/src/main/resources/org.apache.streampipes.sinks.brokers.jvm.kafka/strings.en
- streampipes-integration-tests/src/test/java/org/apache/streampipes/integration/adapters/KafkaAdapterTester.java
- streampipes-messaging-kafka/src/main/java/org/apache/streampipes/messaging/kafka/config/SimpleConfigAppender.java
- streampipes-messaging-kafka/src/main/java/org/apache/streampipes/messaging/kafka/security/KafkaSecurityProtocolConfigAppender.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/template/PipelineElementTemplateVisitor.java
- streampipes-rest-extensions/src/main/java/org/apache/streampipes/rest/extensions/connect/RuntimeResolvableResource.java
To further customize the Kafka connectors, add an additional configuration option which can be used to provide custom producer/consumer configs. Also improve logging of the Kafka connector.
> feat: Add additional properties to Kafka connectors, improve logging

- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.ts
> fix(#3380): Fix editing of data views

- streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/TransformationExtensionModuleExport.java
- streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/migrations/StaticMetadataEnrichmentProcessorMigrationV1.java
- streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/processor/staticmetadata/StaticMetaDataEnrichmentProcessor.java
- streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/datalake/migrations/DataLakeSinkMigrationV1.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/migrations/INotificationDataSinkMigrator.java
Fix a problem which caused the migration to set an invalid version in release 0.95.0.
> fix: Avoid invalid migration when updating from 0.95.0 to 0.97.0

- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.html
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.scss
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/data-explorer-widget-data-settings.component.ts
Restructure of the data configuration panel in the data view. The panel for selecting the data source and query has been updated, including the addition of descriptive information to improve user guidance. Furthermore, an expandable panel feature has been introduced, allowing users to toggle visibility of additional options.
In case no data is available, a warning box is now displayed, alerting the user that a pipeline or adapter needs to be connected in order to select a data source. The warning box includes a button that provides a direct link to the relevant section for connecting an adapter or pipeline.
> feat: Restructure data source selection and query selection

- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/Dockerfile
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__DataProcessor.java
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__DataSink.java
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__GenericAdapter.java
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/main/java/pe/__packageName__/__classNamePrefix__SpecificAdapter.java
This PR updates the Maven archetypes to align with the new version interface. 
> fix(#3407): Update processing element api for archetypes

- streampipes-service-core/pom.xml
> fix: Remove platform-services from pom.xml

- ui/cypress/tests/datalake/timeOrderDataView.spec.ts
> fix: Change time range to fix test timeOrderDataView.spec.ts

- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly-options/pipeline-assembly-options.component.ts
- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly.component.html
- ui/src/app/editor/components/pipeline-assembly/pipeline-assembly.component.ts
This PR is a frst try to fix the broken pipline templates. Still WIP
> wip(#3460): Fix broken pipeline templates

- ui/package.json
- ui/src/app/core-ui/core-ui.module.ts
- ui/src/app/core-ui/monitoring/simple-metrics/simple-metrics.component.html
- ui/src/app/core-ui/status/status-widget.component.html
- ui/src/app/core-ui/status/status-widget.component.scss
- ui/src/app/core-ui/status/status-widget.component.ts
- ui/src/app/dashboard/dashboard.module.ts
- ui/src/app/data-explorer-shared/data-explorer-shared.module.ts
- ui/src/app/data-explorer/data-explorer.module.ts
Remove the `ngx-charts` module which is no longer needed after dashboard migration. All charts depend on Apache Echarts now.
> chore: Remove obsolete ngx-charts module

- pom.xml
- streampipes-commons/pom.xml
- streampipes-service-base/pom.xml
- streampipes-service-base/src/main/java/org/apache/streampipes/service/base/ServiceBaseConfig.java
> chore(deps): Bump Spring Boot and Spring dependencies

- streampipes-maven-plugin/pom.xml
- streampipes-maven-plugin/src/test/java/org/apache/streampipes/smp/generator/TestMarkdownTitleRemover.java
> chore(deps): Update test dependencies in maven plugin
