apache/streampipes

- streampipes-connect-container-master/src/test/java/org/streampipes/connect/container/master/DescriptionManagementTest.java
- streampipes-connect-container-master/src/test/java/org/streampipes/connect/container/master/management/SourcesManagementTest.java
- streampipes-connect-container-master/src/test/java/org/streampipes/connect/container/master/management/UnitMasterManagementTest.java
- streampipes-connect-container-master/src/test/java/org/streampipes/connect/container/master/management/WorkerRestClientTest.java
- streampipes-connect-container-worker/src/test/java/org/streampipes/connect/container/worker/management/AdapterWorkerManagementTest.java
- streampipes-rest/src/test/java/org/streampipes/rest/impl/ConsulConfigTest.java
When building with Java 12 I encountered test-failures. A little research pointed out this is a problem of PowerMock which isn't compatible with Java 11 and above. There are options to avoid these problems. One is to add annotations (As I did in this PR) the other is to create a file on the classpath: org/powermock/extensions/configuration.properties with the following content:
`powermock.global-ignore=com.sun.org.apache.xerces.*,javax.xml.*,org.xml.*,javax.management.*`
Unfortunately there is no globally used "test-utils" module and therefore I used the Annotations.
> Added PowerMock annotations to avoid problems with Java 11 and above.

- ui/src/app/core-ui/linechart/lineChart.component.html
- ui/src/app/core-ui/linechart/lineChart.component.ts
Hi there,
I have extended the time series data labeling tool in such a way that the labeling mode now remains activated after clicking the 'Labeling'-button - until it gets deactivated by clicking the button again or by switching to the plotly-specific 'Pan' or 'Zoom' mode.
The activation of the labeling mode is highlighted by color adjustment of the 'Labeling'-button icon (see also: attached screenshot).
> Time Series Data Labeling Tool - Keeping labeling mode active

- LICENSE-binary
- pom.xml
- streampipes-wrapper-siddhi/pom.xml
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/SiddhiDebugCallback.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/SiddhiEventEngine.java
- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/manager/SpSiddhiManager.java
Hi there,
This PR will upgrade Siddhi dependency to v5.1.12. There are no breaking changes to the from 4.x to 5.x. However, the org names have changed from `org.wso2` to `io.siddhi`, and there's lot of other improvements.
Fixes: https://issues.apache.org/jira/projects/STREAMPIPES/issues/STREAMPIPES-106
Regards,
Grainier
> [STREAMPIPES-106] Upgrade Siddhi dependency to v5.1.12

- pom.xml
- tools/maven/owasp-dependency-check-suppression.xml
Purpose of this pull request is to integrate the CVE maven plugin for StreamPipes to check security vulnerabilities found in dependencies during build time. This will help to detect publicly disclosed vulnerabilities contained within StreamPipes dependencies (and the dependencies of all child modules).
This plugin configuration is attached to the `mvn verify` phase. Therefore, this will run automatically when we perform a `mvn clean verify`. Once the `mvn` process is completed, the plugin will create a `dependency-check-report.html` report in `target/` dir with the detect vulnerabilities.
In case if you need to skip this plugin, use `owasp.check.skip=true` property (i.e `mvn clean verify -Dowasp.check.skip=true`).
- Fixes https://issues.apache.org/jira/browse/STREAMPIPES-108
- …
> [STREAMPIPES-108] Integrate CVE maven plugin

- streampipes-wrapper-siddhi/src/main/java/org/apache/streampipes/wrapper/siddhi/engine/SiddhiEventEngine.java
1. Currently, there is only one list of event keys (attributes), which gets expanded with the keys from all streams: `sortedEventKeys`. When connecting multiple streams to a Siddhi processing element, this leads to a `NullPointerException` and duplicate keys in the stream definition clause. This PR adds a HashMap containing a separate list of event keys for each stream.
2. If both connected streams had the same attribute name, a Siddhi exception was raised. This PR changes attribute naming to that the second stream is prefixed "s1", the third "s2", etc. So if using the integrated Flow Rate 1 and Flow Rate 2 adapters, this would mean the mass_flow attribute is called `s0mass_flow` for the first and `s1mass_flow` for the second stream.
1. Adds the `listOfEventKeys` HashMap. Keys are the …
> Add list of event keys to allow for Siddhi PEs with multiple streams

- streampipes-backend/src/main/java/org/apache/streampipes/backend/StreamPipesResourceConfig.java
- streampipes-backend/src/main/resources/shiro.ini
- streampipes-model/src/main/java/org/apache/streampipes/model/labeling/Category.java
- streampipes-model/src/main/java/org/apache/streampipes/model/labeling/Label.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/api/ILabel.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/LabelResource.java
- streampipes-storage-api/src/main/java/org/apache/streampipes/storage/api/ILabelStorage.java
- streampipes-storage-api/src/main/java/org/apache/streampipes/storage/api/INoSqlStorage.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/CouchDbStorageManager.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/LabelStorageImpl.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/utils/Utils.java
Implementation of `Label` and `Category` classes for the labeling-tool in the data explorer
- Hierarchical Labels - each label belongs to a certain category 
- Each category has a superlabel which it depends on
- TODO: Category-API and storing of Categories, managing labels of a category
Fixes: https://issues.apache.org/jira/projects/STREAMPIPES/issues/STREAMPIPES-234
> [WIP][Streampipes-234] API for Hierarchical Labels

- streampipes-connect/src/test/java/org/apache/streampipes/connect/adapter/format/json/xml/XmlTest.java
This PR is to fix 2 flaky tests issue.
2 tests are failed when running the following commandlines:
```
mvn -pl streampipes-connect edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.streampipes.connect.adapter.format.json.xml.XmlTest#parseEventCarPark
mvn -pl streampipes-connect edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.streampipes.connect.adapter.format.json.xml.XmlTest#parseEventParkingFaciltyStatus
```
The reason is because in `XmlParser.java`, it uses `Map` and `gson()` to convert which produces non-deterministic results that mess up the order of returned string. The fix compares if the returned string's length equals to the desired string's length, which get rid of the wrong order issues. 
```
[ERROR] Failures:
[ERROR]   XmlTest.parseEventCarPark:49 …
```
> [STREAMPIPES-Unknown] Fixed 2 flaky tests

- streampipes-container-base/pom.xml
Add 
<dependency>
<groupId>org.springframework</groupId>
<artifactId>spring-context-support</artifactId>
</dependency>
to  streampipes-container-base
> [STREAMPIPES-479] Add spring-context-support dependency

- ui/src/app/data-explorer/components/widgets/correlation-chart/correlation-chart-widget.component.ts
- ui/src/app/data-explorer/components/widgets/heatmap/heatmap-widget.component.ts
- ui/src/app/data-explorer/components/widgets/time-series-chart/time-series-chart-widget.component.ts
- ui/src/app/data-explorer/components/widgets/utils/select-color-properties/select-color-properties.component.html
Data-explorer widgets such as heatmaps or time series charts display time-dependent information. Some widgets always calculate and display UCT instead of the respective local time.
> [STREAMPIPES-506] Fix wrong default time zones in data-explorer widgets

- ui/src/app/data-explorer/components/panel/data-explorer-dashboard-panel.component.ts
A data-explorer widget should not be updated when the auth token is being renewed
> [STREAMPIPES-554] Only reload data-explorer widget if configuration is changed

- tools/maven/checkstyle-header.txt
- tools/maven/checkstyle.xml
This PR adds a check for license headers to the checkstyle plugin as discussed in [1]
Fixes: [STREAMPIPES-648]
[1] https://lists.apache.org/thread/6o8xsdvky78h7mfs0dy18pl6dh3mfbyv
> [STREAMPIPES-648] Add license header check to checkstyle.xml

- pom.xml
Fix https://github.com/apache/streampipes/issues/820#issuecomment-1339663188
The root cause is that the plugin configuration of the submodule is inherited from the parent project. We have skipped `failOnViolation` in the parent pom. Therefore the submodule also skips that.
This PR makes the checkstyle configuration of the parent module not be inherited to the submodule.
After we complete this issue: https://github.com/apache/streampipes/issues/820, we can turn it back and let the checkstyle configuration of the parent module apply to the whole project.
> Fix the checkstyle plugin doesn't fail on violation

- streampipes-config/pom.xml
- streampipes-config/src/main/java/org/apache/streampipes/config/backend/BackendConfig.java
- streampipes-config/src/main/java/org/apache/streampipes/config/backend/MessagingSettings.java
- tools/maven/checkstyle.xml
Master Issue: #820 
* Enable checkstyle for streampipes-config
* Add suppress support for checkstyle, now we can use this way to suppress the style check before the code:
```java
@SuppressWarnings("checkstyle:{Rule-name}")
...
```
I found that there is an issue in the IDEA: https://youtrack.jetbrains.com/issue/IDEA-80495/Settings-Operation-sign-on-next-line-does-not-work-for-automatically-breaking-strings.
Therefore, we seem couldn't reformat the code according to the `OperatorWrap` rule automatically. Haven't found a good solution yet. We could only format it manually.
> [#820] Enable checkstyle for streampipes-config and add suppress support for checkstyle

- streampipes-security-jwt/pom.xml
- streampipes-security-jwt/src/main/java/org/apache/streampipes/security/jwt/JwtTokenGenerator.java
- streampipes-security-jwt/src/main/java/org/apache/streampipes/security/jwt/JwtTokenUtils.java
- streampipes-security-jwt/src/main/java/org/apache/streampipes/security/jwt/JwtTokenValidator.java
- streampipes-security-jwt/src/main/java/org/apache/streampipes/security/jwt/KeyGenerator.java
- streampipes-security-jwt/src/main/java/org/apache/streampipes/security/jwt/KeyUtils.java
> [#820] add checkstyle to streampipes-security-jwt

- ui/.husky/pre-commit
I think there is an issue with the pre-commit hook on windows, because the Shebang should be on the first line of the script. Because of the apache header it could not be interpreted correctly.
> fix: fix shebang with apache header

- .github/dependabot.yml
- ui/README.md
- ui/package-lock.json
- ui/package.json
The two libraries "@streampipes/platform-services" and "@streampipes/shared-ui" are only available locally. So we can not use `npm install` without the flag `--legacy-peer-dependency`. Unfortunatelly dependabot uses `npm install` without this flag and therefore can not be used.
I think a good approach to manage these local libraries would be to use [Nx](https://nx.dev/) which brings support for angular monorepos (https://nx.dev/angular-tutorial/1-code-generation) But to use Nx we need to do some refactoring, I will open a discussion for this.
As a quick workaround I removed the two peer dependencies and added a "postinstall" Scrips which builds and installs the libraries after running `npm install`.
> chore: remove peer dependencies and use postinstall

- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/Dockerfile
- archetypes/streampipes-archetype-pe-processors-flink/src/main/resources/archetype-resources/Dockerfile
- archetypes/streampipes-archetype-pe-sinks-flink/src/main/resources/archetype-resources/Dockerfile
- streampipes-backend/Dockerfile
- streampipes-commons/src/main/java/org/apache/streampipes/commons/constants/DefaultEnvValues.java
- streampipes-commons/src/main/java/org/apache/streampipes/commons/constants/Envs.java
- streampipes-extensions/streampipes-connect-adapters-iiot/Dockerfile
- streampipes-extensions/streampipes-connect-adapters/Dockerfile
- streampipes-extensions/streampipes-extensions-all-iiot/Dockerfile
- streampipes-extensions/streampipes-extensions-all-jvm/Dockerfile
- streampipes-extensions/streampipes-pipeline-elements-all-flink/Dockerfile
- streampipes-extensions/streampipes-pipeline-elements-all-jvm/Dockerfile
- streampipes-extensions/streampipes-sinks-internal-jvm/Dockerfile
- streampipes-extensions/streampipes-sources-watertank-simulator/Dockerfile
- streampipes-service-discovery-consul/src/main/java/org/apache/streampipes/svcdiscovery/consul/ConsulProvider.java
> Improve handling of Consul env variables (#953)

- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/pom.xml
- archetypes/streampipes-archetype-extensions-jvm/src/main/resources/archetype-resources/src/test/java/InitTest.java
To reduce effort to write unit tests for new processors.
Do you prefere JUnit 4 ?
> Add example junit test to archetype extensions-jvm

- streampipes-client-python/streampipes_client/endpoint/endpoint.py
Introduce a new, more general level of abstraction for endpoints in the Python client which allows for future extensions.
This prepares some functionalities where the client is not only interacting with the StreamPipes API.
> chore: introduce another layer of abstraction for endpoints

- installer/cli/bin/commands/env
Issue: https://github.com/apache/streampipes/issues/964
For the CLI installer's command, in case of an error, it should exit with a message on the console output.
PR introduces (a) breaking change(s): <yes/no> no
PR introduces (a) deprecation(s): <yes/no> no
> Validate CLI commands and exit with message if any error's.

- ui/.eslintignore
- ui/.prettierignore
- ui/src/app/services/auth.service.ts
- ui/src/app/services/available-roles.service.ts
- ui/src/app/services/get-element-icon-text.service.ts
- ui/src/app/services/jwt-token-storage.service.ts
- ui/src/app/services/notification-count-service.ts
- ui/src/app/services/property-selector.service.ts
- ui/src/app/services/rest-api.service.ts
- ui/src/app/services/secure.pipe.ts
- ui/src/app/services/services.module.ts
- ui/src/app/services/tour/adapter-tour-2.constants.ts
- ui/src/app/services/tour/adapter-tour-3.constants.ts
- ui/src/app/services/tour/adapter-tour.constants.ts
- ui/src/app/services/tour/create-pipeline-tour.constants.ts
- ui/src/app/services/tour/dashboard-tour.constants.ts
- ui/src/app/services/tour/shepherd.service.ts
- ui/src/app/services/tour/tour-provider.service.ts
Apply formatting and linting to `services` module
> [#877] apply formatting and linting to services module

- streampipes-extensions-api/src/main/java/org/apache/streampipes/extensions/api/connect/IProtocol.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/set/FileProtocol.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/set/HttpProtocol.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/BrokerProtocol.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/FileStreamProtocol.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/HttpServerProtocol.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/HttpStreamProtocol.java
> [#1077] Remove legacy method getNElements

- ui/.eslintignore
- ui/.prettierignore
- ui/src/app/core-model/base/UserErrorMessage.ts
- ui/src/app/core-model/coco/Annotation.ts
- ui/src/app/core-model/coco/Category.ts
- ui/src/app/core-model/coco/Coco.format.ts
- ui/src/app/core-model/coco/Image.ts
Applying UI linting and formatting to the `core-model` module. Removing the `core-model` module from `ui/.eslintignore` and `ui/.prettierignore` and fixing formatting and lining.
> [#877] Format and lint core-model module

- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/format/csv/CsvParser.java
- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/util/DatatypeUtils.java
- streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/connect/adapter/format/csv/CsvParserTest.java
- streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/connect/adapter/util/DatatypeUtilsTest.java
- ui/src/app/connect/components/adapter-configuration/schema-editor/event-schema-preview/event-schema-preview.component.html
This PR fixes the failing e2e tests. 
There were two problems:
- The data-cy tag `data-cy="schema-preview-original-event"` was missing for the format tests.
- The behavior of the CSV parser has been changed. Now it uses Double as default type to ensure that the values do not change during parsing.
> [hotfix] Fix failing e2e tests

- ui/.eslintignore
- ui/.prettierignore
- ui/src/app/core-services/semantic-type/semantic-type-utils.service.ts
- ui/src/app/core-services/template/PipelineInvocationBuilder.ts
Applying UI linting and formatting to the `core-services` module. Removing the `core-services` module from `ui/.eslintignore` and `ui/.prettierignore` and fixing formatting.
> [#877] Format and lint core-services module

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterMasterManagement.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/FileStreamProtocol.java
- ui/cypress/support/utils/connect/ConnectBtns.ts
- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/cypress/tests/adapter/createAdapterWithoutStarting.spec.ts
- ui/cypress/tests/adapter/editAdapter.smoke.spec.ts
- ui/projects/streampipes/platform-services/src/lib/apis/adapter.service.ts
- ui/src/app/connect/components/adapter-configuration/start-adapter-configuration/adapter-options-panel/adapter-options-panel.component.html
- ui/src/app/connect/components/adapter-configuration/start-adapter-configuration/adapter-options-panel/adapter-options-panel.component.ts
- ui/src/app/connect/components/adapter-configuration/start-adapter-configuration/start-adapter-configuration.component.html
- ui/src/app/connect/components/adapter-configuration/start-adapter-configuration/start-adapter-configuration.component.ts
- ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.html
- ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.ts
Fix #1114. Adapters can now be added without having to be started.
This PR also includes a fix for the FileStreamAdapter. When the adapter is stopped, the running replays are now interrupted.
> [#1114] Adapters can now be added without starting them

- ui/.eslintignore
- ui/.prettierignore
- ui/src/app/login/components/activate-account/activate-account.component.html
- ui/src/app/login/components/activate-account/activate-account.component.ts
- ui/src/app/login/components/auth-box/auth-box.component.ts
- ui/src/app/login/components/login/login.component.html
- ui/src/app/login/components/login/login.component.scss
- ui/src/app/login/components/login/login.component.ts
- ui/src/app/login/components/login/login.model.ts
- ui/src/app/login/components/register/register.component.html
- ui/src/app/login/components/register/register.component.ts
- ui/src/app/login/components/register/registration.model.ts
- ui/src/app/login/components/restore-password/restore-password.component.html
- ui/src/app/login/components/restore-password/restore-password.component.ts
- ui/src/app/login/components/set-new-password/set-new-password.component.html
- ui/src/app/login/components/set-new-password/set-new-password.component.ts
- ui/src/app/login/components/setup/setup.component.html
- ui/src/app/login/components/setup/setup.component.scss
- ui/src/app/login/components/setup/setup.component.ts
- ui/src/app/login/components/startup/startup.component.html
- ui/src/app/login/components/startup/startup.component.scss
- ui/src/app/login/components/startup/startup.component.ts
- ui/src/app/login/login.module.ts
- ui/src/app/login/services/account-activation.service.ts
- ui/src/app/login/services/login.service.ts
- ui/src/app/login/services/restore-password.service.ts
- ui/src/app/login/utils/check-password.ts
Apply linting and formatting to the login module.
> [#877] apply formatting and linting to login module

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/FileStreamProtocol.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/resources/org.apache.streampipes.connect.iiot.protocol.stream.file/strings.en
- ui/cypress/tests/adapter/fileStream.smoke.spec.ts
- ui/cypress/tests/adapter/persistInDataLake.smoke.spec.ts
- ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.ts
- Fixes #1121
- Implements the ability for the `FileStreamAdapter` to replay a file only once
- Additional parameter added to the `FileStreamAdapter` configuration to enable this feature
- Default behavior set to continuously replay the file
@dominikriemer do we need an update script for old adapters using the `FileStreamAdapters`?
Since we will update the connection API, should we implement this update now or later for the new data model?
> [#1121] Add replay once option to FileStreamProtocol

- ui/.eslintignore
- ui/.prettierignore
- ui/src/app/CustomMaterial/custom-material.module.ts
Applying UI linting and formatting to the `CustomMaterial` module. Removing the `CustomMaterial` module from `ui/.eslintignore` and `ui/.prettierignore` and fixing formatting.
> [#877] Format and lint CustomMaterial module

- installer/cli/deploy/standalone/iotdb/docker-compose.dev.yml
- installer/cli/deploy/standalone/iotdb/docker-compose.yml
- pom.xml
- streampipes-extensions/streampipes-sinks-databases-jvm/pom.xml
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/iotdb/IotDb.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/iotdb/IotDbController.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/iotdb/IotDbParameters.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/jdbcclient/model/DbDataTypeFactory.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/jdbcclient/model/DbDataTypes.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/jdbcclient/model/SupportedDbEngines.java
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/resources/org.apache.streampipes.sinks.databases.jvm.iotdb/documentation.md
- streampipes-extensions/streampipes-sinks-databases-jvm/src/main/resources/org.apache.streampipes.sinks.databases.jvm.iotdb/strings.en
- streampipes-extensions/streampipes-sinks-databases-jvm/src/test/java/org/apache/streampipes/sinks/databases/jvm/iotdb/TestIotDbParameters.java
Recently, I was trying to play around streampipes and found that iotdb sink could not work properly.
I checked the source code and found that the current JDBC based implementation of iotdb sink is outdated, especially for the current production versions of iotdb (0.13.x and 1.0.x).
I‘d like to contribute a brand new iotdb sink implementation, which has the following features:
- Support production ready versions of IoTDB (version >= 0.13.0)
- Support by iotdb-session API, which can provide higher throughput and lower latency
- Support schema-less write: no need to create storage group (database) before insertion
See #1146 for more detail :D
Old versions (< v0.13) of IoTDB are no longer supported.
I setup a …
> [#1146] Session based implementation of IoTDB sink (fix issues in current JDBC based implementation)

- .github/workflows/python-docs.yml
This PR introduces a new GitHub workflow that runs on a weekly basis at Saturday `00:00:00`.
It builds the Python docs and uploads the created files as [GitHub artifact.](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts)
This artifact is only kept for ten days.
> feature(gh-actions): create workflow that provides python docs as artifact weekly

- .github/workflows/pr-labeler.yml
This fixes #1308.
PR introduces (a) breaking change(s): <yes/no> no
PR introduces (a) deprecation(s): <yes/no> no
There are some discussions about this failure:
- https://github.com/actions/labeler/issues/12#issuecomment-1095272652
- https://github.com/actions/labeler/issues/136#issuecomment-1357839196
Let's see how other projects deal with this problem:
- Spark: https://github.com/apache/spark/blob/master/.github/workflows/labeler.yml
- Beam: https://github.com/apache/beam/blob/master/.github/workflows/label_prs.yml
> [#1308][CI] label-pr workflow fails on fork-based PRs

- streampipes-extensions/streampipes-processors-geo-jvm/src/main/java/org/apache/streampipes/processors/geo/jvm/jts/processor/latlngtojtspoint/LatLngToJtsPointProcessor.java
- streampipes-extensions/streampipes-processors-geo-jvm/src/main/java/org/apache/streampipes/processors/geo/jvm/jts/processor/reprojection/ReprojectionProcessor.java
- streampipes-extensions/streampipes-processors-geo-jvm/src/main/java/org/apache/streampipes/processors/geo/jvm/jts/processor/trajectory/TrajectoryFromPointsProcessor.java
- streampipes-extensions/streampipes-processors-geo-jvm/src/main/java/org/apache/streampipes/processors/geo/jvm/latlong/processor/distancecalculator/haversine/HaversineDistanceCalculatorProcessor.java
- streampipes-extensions/streampipes-processors-geo-jvm/src/main/java/org/apache/streampipes/processors/geo/jvm/latlong/processor/speedcalculator/SpeedCalculatorProcessor.java
- streampipes-extensions/streampipes-processors-geo-jvm/src/main/resources/org.apache.streampipes.processors.geo.jvm.jts.processor.reprojection/strings.en
#1040  improve naming of runtime names and add missing epsg field in trajectory
tested with all changes according to 
https://cwiki.apache.org/confluence/x/QZBbDg
https://cwiki.apache.org/confluence/x/RpBbDg
https://cwiki.apache.org/confluence/x/SZBbDg
https://cwiki.apache.org/confluence/x/U5BbDg
https://cwiki.apache.org/confluence/x/XJBbDg
* `LatLngToJtsPointProcessor`: Rename schema field `WKT_RUNTIME` to `GEOMETRY_RUNTIME`
* `ReprojectionProcessor`: Rename schema field `GEOM_RUNTIME` to `GEOMETRY_RUNTIME`
* `TrajectoryFromPointsProcessor`: Introduce schema field `TRAJECTORY_GEOMETRY_RUNTIME` and rename `TRAJECTORY_RUNTIME` to  `TRAJECTORY_EPSG_RUNTIME`
* `HaversineDistanceCalculatorProcessor`: Rename schema …
> [#1040] rework schema definitions in geo processors

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/v4/query/DataExplorerQueryV4.java
1. Use try-with-resource way to fix the potential InfluxDB connection leak in `DataExplorerQueryV4#executeQuery`
2. Remove the unused `executeQuery` method in `DataExplorerQueryV4`
3. Use `LOG.isDebugEnabled()` before logging to avoid performance issues
PR introduces (a) breaking change(s): <yes/no> 
no
PR introduces (a) deprecation(s): <yes/no> 
no
> [hotfix] Use try-with-resource way to fix the potential InfluxDB connection leak in `DataExplorerQueryV4#executeQuery`

- streampipes-client-python/docs/index.md
Add disclaimer for missing doc versioning
> chore: fix example code & add disclaimer for doc versioning

- .github/workflows/pypi-deployment.yml
- .github/workflows/python-docs.yml
- streampipes-client-python/mkdocs.yml
- streampipes-client-python/setup.py
This PR introduces versioning for the Python documentation.
This includes the following adaptions:
* use make as versioning provider
* adapt Python doc publishing workflow to make use of mike
* include publishing of docs in Python deployment workflow
> [#1375] add versioning to python docs

- streampipes-client-python/setup.py
- streampipes-client-python/streampipes/functions/broker/__init__.py
- streampipes-client-python/streampipes/functions/broker/broker_handler.py
- streampipes-client-python/streampipes/functions/broker/kafka_broker.py
- streampipes-client-python/streampipes/functions/broker/kafka_message_fetcher.py
- streampipes-client-python/streampipes/model/common.py
- streampipes-client-python/streampipes/model/resource/data_lake_measure.py
This PR introduces support for the Kafka broker within StreamPipes Python.
With this a user is able to implement StreamPipes functions that interact with Kafka as a message broker.
> Add support for the Kafka broker in Python

- streampipes-data-explorer/src/test/java/org/apache/streampipes/dataexplorer/sdk/DataLakeQueryBuilderTest.java
This PR adds a unit test for the `DataLakeQueryBuilder`.
> [hotfix] Add test for DataLakeQueryBuilder

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/influx/DataExplorerInfluxQueryExecutor.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/ProvidedRestQueryParamConverter.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/SelectQueryParams.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/model/LimitClauseParams.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataExplorerQueryExecutor.java
- ui/src/app/data-explorer/components/widgets/table/table-widget.component.html
This PR improves handling of count queries in the data explorer query module by finding the max count value of all field values.
In addition, there is a minor improvement to the table widget to avoid showing pagination controls in case no data is present.
> [hotfix] Improve handling of count queries, improve table widget

- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/param/model/SelectColumn.java
- streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/query/DataExplorerQueryExecutor.java
- ui/src/app/connect/services/rest.service.ts
- ui/src/app/data-explorer/components/widgets/table/table-widget.component.html
- ui/src/app/editor/services/editor.service.ts
- ui/src/app/login/services/login.service.ts
- ui/src/app/notifications/service/notifications.service.ts
- ui/src/app/services/rest-api.service.ts
Fix a bug that wrongly parsed count queries in the data explorer after query refactoring.
> [hotfix] Fix handling of count queries in data explorer

- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/connect/adapter/preprocessing/transform/value/CorrectionValueTransformationRule.java
- streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/connect/adapter/transform/value/CorrectionValueTest.java
- ui/README.md
- ui/src/app/connect/dialog/edit-event-property/components/edit-value-transformation/edit-correction-value/edit-correction-value.component.ts
- ui/src/app/connect/dialog/edit-event-property/edit-event-property.component.ts
When creating an adapter in StreamPipes Connect, we allow to add some transformation rules that directly modify modify data when ingesting. Hereby, we support basic mathematic operations.
This PR extends this functionality by the division operator.
> [FEATURE] add division as operation for data harmonization rules

- streampipes-client-python/streampipes/client/client.py
- streampipes-client-python/streampipes/endpoint/api/__init__.py
- streampipes-client-python/streampipes/endpoint/api/data_lake_measure.py
- streampipes-client-python/streampipes/endpoint/api/data_stream.py
- streampipes-client-python/streampipes/endpoint/api/version.py
- streampipes-client-python/streampipes/model/container/__init__.py
- streampipes-client-python/streampipes/model/container/versions.py
- streampipes-client-python/streampipes/model/resource/version.py
- streampipes-client-python/tests/client/test_client.py
- streampipes-client-python/tests/client/test_data_lake_series.py
- streampipes-client-python/tests/client/test_endpoint.py
- streampipes-client-python/tests/functions/test_function_handler.py
- streampipes-client-python/tests/functions/test_river_function.py
This PR introduces a direct API call for the `StreamPipesClient` when initialized. This API call is introduced for the reasons:
1) it requires authentication and therefore allows to provide immediate feedback whether the passed credentials are valid or not.
2) it retrieves the version the connected StreamPipes instance is running on. This will be used in subsequent work, so the client can assess which of it's features are compatible with the connected StreamPipes instance.
fixes #1259 
> [1259] verify authentication on startup of python client

- streampipes-wrapper-python/README.md
- streampipes-wrapper-python/setup.py
- streampipes-wrapper-python/streampipes/api/rest.py
- streampipes-wrapper-python/streampipes/core.py
- streampipes-wrapper-python/streampipes/declarer.py
- streampipes-wrapper-python/streampipes/instances.py
- streampipes-wrapper-python/streampipes/manager.py
- streampipes-wrapper-python/streampipes/model/base/abstract_streampipes_entity.py
- streampipes-wrapper-python/streampipes/model/base/consumable_streampipes_entity.py
- streampipes-wrapper-python/streampipes/model/base/named_streampipes_entity.py
- streampipes-wrapper-python/streampipes/model/base/unnamed_streampipes_entity.py
- streampipes-wrapper-python/streampipes/model/config_item.py
- streampipes-wrapper-python/streampipes/model/graph/data_processor_description.py
- streampipes-wrapper-python/streampipes/model/pipeline_element_config.py
- streampipes-wrapper-python/streampipes/model/staticproperty/free_text_StaticProperty.py
- streampipes-wrapper-python/streampipes/model/staticproperty/static_property.py
- streampipes-wrapper-python/streampipes/submitter.py
- streampipes-wrapper-python/streampipes/utils/register.py
This marks the streampipes-wrapper-python as deprecated from `0.92.0` on.
The wrapper only contains a prototypical implementation of running pipeline elements in Python, which will be integrated into the python module.
> chore: mark streampipes-wrapper-python as deprecated

- streampipes-client-python/docs/getting-started/quickstart.md
- streampipes-client-python/docs/index.md
- streampipes-client-python/docs/tutorials/1-introduction-to-streampipes-python-client.ipynb
- streampipes-client-python/docs/tutorials/2-extracting-data-from-the-streampipes-data-lake.ipynb
- streampipes-client-python/docs/tutorials/3-getting-live-data-from-the-streampipes-data-stream.ipynb
- streampipes-client-python/docs/tutorials/4-using-online-machine-learning-on-a-streampipes-data-stream.ipynb
- streampipes-client-python/setup.py
- streampipes-client-python/streampipes/client/credential_provider.py
- streampipes-client-python/tests/client/test_credential_provider.py
This PR allows to retrieve credentials for the Python client directly from the environment variables without the need to call an additional method (previously: `from_env()`).
The credential chain applied here looks the following:
1) keyword arguments passed to `StreamPipesApiKeyCredentials()`
if not passed:
2) environment variables `SP_API_KEY` and `SP_USERNAME` are checked.
> feature: retrieve credentials from SP environment variables

- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/locales/LabelGenerator.java
Fix https://github.com/apache/streampipes/issues/1700
We use UTF-8 encoding for the locale files. It's better to specify the encoding when reading those files.
I have tested it, and it works fine now:
```
curl  http://admin:admin@localhost:5984/adapterdescription/sp:xxx.my.adapter | jq .   | grep label
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  9964  100  9964    0     0  21336      0 --:--:-- --:--:-- --:--:-- 21660
"label": "Broker 地址",
"label": "不进行认证",
"label": "用户名",
"label": "密码",
"label": "用户组",
"label": "用户名/密码",
"label": "访问模式",
"label": "主题",
```
> Use UTF_8 as the encoding when generating the label

- streampipes-model/src/main/java/org/apache/streampipes/model/file/GenericStorageAttachment.java
- streampipes-storage-api/src/main/java/org/apache/streampipes/storage/api/IGenericStorage.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/GenericStorageImpl.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/utils/Utils.java
This adds the possibility to create attachments for images in CouchDB.
> Enable creating CouchDB attachments for images 

- streampipes-client-python/docs/index.md
- streampipes-client-python/setup.py
This PR introduces the usage of [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) in our Python docs.
Admonitions are small UI elements that are designed to highlight certain statements, e.g.:
Admonitions can also be collapsed:
See some more supported admonitions: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
In addition, all base dependencies are now pinned to their current major versions.
PR introduces (a) breaking change(s):no
> feature: introduce admonitions to warn about dependency issue in docs

- streampipes-model/src/main/java/org/apache/streampipes/model/datalake/DataLakeMeasure.java
- streampipes-platform-services/src/main/java/org/apache/streampipes/ps/DataLakeMeasureResourceV4.java
- streampipes-rest-shared/src/main/java/org/apache/streampipes/rest/shared/impl/AbstractSharedRestInterface.java
- streampipes-storage-couchdb/src/main/java/org/apache/streampipes/storage/couchdb/impl/DataLakeStorageImpl.java
Improve the handling of data lake measures when using the API:
* Keep document ID if present
* Return 404 if the requested measure is not present
> [hotfix] Improve handling of data lake measures in API

- streampipes-client-python/streampipes/endpoint/api/data_lake_measure.py
- streampipes-client-python/tests/endpoint/test_data_lake_measure.py
resolves #1374 
The parameter `columns` when querying data lake measures expects now a list of strings:
```python
client.dataLakeMeasureApi.get(identifier="flow-rate", columns=["mass_flow", "temperature"])
```
Single strings are no longer allowed.
> #1374: Convenient columns query parameter for data lake measure

- installer/k8s/templates/core/backend-deployment.yaml
- installer/k8s/templates/core/ui-deployment.yaml
- installer/k8s/templates/extensions/pipeline-elements/extensions-all-iiot-deployment.yaml
- installer/k8s/templates/external/consul/consul-deployment.yaml
- installer/k8s/templates/external/couchdb/couchdb-deployment.yaml
- installer/k8s/templates/external/influxdb/influxdb-deployment.yaml
- installer/k8s/templates/external/kafka/kafka-deployment.yaml
- installer/k8s/templates/external/nats/nats-deployment.yaml
- installer/k8s/templates/external/zookeeper/zookeeper-deployment.yaml
- installer/k8s/values.yaml
Completion of the discussion (#1781) 
> add probes to Streampipes' kubernetes deployment ( #1781 )

- ui/src/app/core-ui/object-permission-dialog/object-permission-dialog.component.html
Refactor MDC chip input in the permission dialog after Angular update.
> [hotfix] Fix MDC layout issue in permission dialog

- installer/cli/environments/full
As discoussed in #1597  sources-vehicle-simulator should be remove from default installers.
Not supported containers removed from installer environment profile.
PR introduces a breaking change: no
PR introduces a deprecation: no
> Remove sources-vehicle-simulator from cli-installer full env.

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/resources/org.apache.streampipes.connect.iiot.adapters.plc4x.modbus/documentation.md
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/resources/org.apache.streampipes.connect.iiot.adapters.plc4x.s7/documentation.md
Add documentation for the PLC4X S7 and Modbus adapters.
> Add documentation for S7 and Modbus adapters

- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/template/PipelineTemplateGenerator.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineTemplate.java
- ui/src/app/connect/components/adapter-configuration/adapter-settings/adapter-settings.component.html
- ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.html
- ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.scss
- ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.ts
- ui/src/app/core-ui/static-properties/static-runtime-resolvable-tree-input/static-tree-input.component.html
> Improve dialog in StreamPipes connect (#1934)

- streampipes-storage-couchdb/pom.xml
- streampipes-user-management/src/main/java/org/apache/streampipes/user/management/util/PasswordUtil.java
- streampipes-user-management/src/test/java/org/apache/streampipes/user/management/util/TestPasswordUtil.java
This PR replaces the logic behind the default password generation when no password is provided for a new user.
So far we have been using the `randomAscii()` method of `RandomStringUtils` from `apache.commons.lang3`.
However, this is not a good choice for password generation because it is only a weak pseudorandom generation. Therefore, its documentation recommends using the `RandomStringGenerator` of `apache.commons.text`.
> refactor: replace random password generation logic

- installer/k8s/README.md
- installer/k8s/templates/core/backend-deployment.yaml
- installer/k8s/templates/monitor/grafana/grafana-deployment.yml
- installer/k8s/templates/monitor/grafana/grafana-pv.yml
- installer/k8s/templates/monitor/grafana/grafana-pvc.yml
- installer/k8s/templates/monitor/grafana/grafana-service.yml
- installer/k8s/templates/monitor/prometheus/prometheus-configmap.yaml
- installer/k8s/templates/monitor/prometheus/prometheus-deployment.yml
- installer/k8s/templates/monitor/prometheus/prometheus-pv.yml
- installer/k8s/templates/monitor/prometheus/prometheus-pvc.yml
- installer/k8s/templates/monitor/prometheus/prometheus-service.yml
- installer/k8s/templates/monitor/prometheus/token-pvc.yml
- installer/k8s/values.yaml
- streampipes-extensions/streampipes-extensions-all-jvm/Dockerfile
Add deployment of Prometheus and Grafana to K8s
> Add deployment of Prometheus and Grafana to K8s

- streampipes-extensions/streampipes-pipeline-elements-shared/src/main/java/org/apache/streampipes/pe/shared/config/kafka/kafka/KafkaConnectUtils.java
Avoid problems if configuration from old instances is used.
Fixes #1992
> Set default Kafka auto offset explicitly if it is not defined (#1992)

- streampipes-client-python/streampipes/client/client.py
- streampipes-client-python/tests/client/test_client.py
> fix(#1670): validate client config and create proper error message

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/iolink/IfmAlMqttAdapter.java
This PR makes the data retrieval within the IOLink adapter more robust. Prior to it, an error occurring for one port stopped the processing of all subsequent ports. This means, that in case the processing fails for port 2, e.g., since this port is not connected to a sensor and therefore does not deliver any data, parsing for port 3 and 4 is skipped. 
From now on, only the affected port will be skipped.
> fix: make data retrieval of IOLink sensor more robust

- streampipes-client-python/docs/tutorials/1-introduction-to-streampipes-python-client.ipynb
`%export ENVIRONMENT_VARIABLE ` could led to "UsageError: Line magic function `%export` not found." error.
`os.environ` dictionary seems to be more generic and reuses the approach from other StreamPipes Python tutorials.
> Use os.environ dictionary to set environment variables.

- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v093/AdapterMigration.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v093/migrator/SpecificAdapterMigrator.java
Fixes #2165.
This PR addresses issues encountered during the migration from adapter version 0.92.0 to 0.93.0. The problem arose due to the removal of the _rev during the backup creation in CouchDB, leading to complications in the adapter model migration.
**Changes:**
Create a deep copy of the adapter instance backup object before writing it to CouchDB.
> bug(#2165): Fix migration for adapter instances

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/iolink/IfmAlMqttAdapter.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/ros/RosBridgeAdapter.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/simulator/machine/MachineDataSimulatorAdapter.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/FileReplayAdapter.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/HttpServerProtocol.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/protocol/stream/HttpStreamProtocol.java
- streampipes-extensions/streampipes-connect-adapters/src/main/java/org/apache/streampipes/connect/adapters/image/stream/ImageStreamAdapter.java
- streampipes-extensions/streampipes-connect-adapters/src/main/java/org/apache/streampipes/connect/adapters/iss/IssAdapter.java
- streampipes-extensions/streampipes-connect-adapters/src/main/java/org/apache/streampipes/connect/adapters/netio/NetioMQTTAdapter.java
- streampipes-extensions/streampipes-connect-adapters/src/main/java/org/apache/streampipes/connect/adapters/netio/NetioRestAdapter.java
- streampipes-extensions/streampipes-connectors-influx/src/main/java/org/apache/streampipes/extensions/connectors/influx/adapter/InfluxDbStreamAdapter.java
- streampipes-extensions/streampipes-connectors-kafka/src/main/java/org/apache/streampipes/extensions/connectors/kafka/adapter/KafkaProtocol.java
- streampipes-extensions/streampipes-connectors-mqtt/src/main/java/org/apache/streampipes/extensions/connectors/mqtt/adapter/MqttProtocol.java
- streampipes-extensions/streampipes-connectors-nats/src/main/java/org/apache/streampipes/extensions/connectors/nats/adapter/NatsProtocol.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/adapter/OpcUaAdapter.java
- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/modbus/Plc4xModbusAdapter.java
- streampipes-extensions/streampipes-connectors-pulsar/src/main/java/org/apache/streampipes/extensions/connectors/pulsar/adapter/PulsarProtocol.java
- streampipes-extensions/streampipes-connectors-rocketmq/src/main/java/org/apache/streampipes/extensions/connectors/rocketmq/adapter/RocketMQProtocol.java
- streampipes-extensions/streampipes-connectors-tubemq/src/main/java/org/apache/streampipes/extensions/connectors/tubemq/adapter/TubeMQProtocol.java
Added a value for the version parameter in the AdapterDescriptions which is required since #2077
> refactor: add value for version parameter in adapter description

- ui/angular.json
This config change avoids a reset of the browser cache when updating to a new StreamPipes version.
> build: change `outputHashing` in Angular to avoid caching issue after new release

- ui/src/app/files/components/file-overview/file-overview.component.html
- ui/src/app/files/components/file-overview/file-overview.component.ts
This pull request addresses issue #2107 by enhancing the File Overview component to include color-coded file types. The goal is to improve the user experience by providing a visual distinction between different file types.
- Modified the HTML code within the file overview component to dynamically set the background color of the file type container using the `getFileColor` method.
- Added a new private property `fileTypeColors` (map) to store the generated colors for each file type.
- Added a new method `getFileColor` to check if the color for the given file type is already stored in the map; if not, it generates a new color using the `generateColorHash` method.
- Added a new private method `generateColorHash` to generate a color code.
Please feel free to provide feedback or suggest any …
> feat: Add color display for file types in File Management (#2107)

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/ResetResource.java
- ui/cypress/support/utils/UserUtils.ts
- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/cypress/tests/adapter/enhancedDeleteAdapter.smoke.spec.ts
- ui/cypress/tests/adapter/machineDataSimulator.smoke.spec.ts
- ui/src/app/connect/dialog/delete-adapter-dialog/delete-adapter-dialog.component.html
See #2151 
Added E2E tests for these 3 cases:
- An adapter and >1 pipelines are created by a non-admin user, the non-admin user should be able to delete the adapter and associated pipelines.
- A public adapter and >1 pipelines are created by a non-admin user, the admin should be able to delete the adapter and associated pipelines.
- A public adapter and >1 pipelines are created by admin (or any other users), the non-admin user should not be able to delete the adapter and the associated pipelines. After checking this, switch to admin's account to clean up (delete adapter, associated pipelines, non-admin user).
NOTE: I modified the logic of roles in `addUser()` of `UserUtil.ts` because I need the non-admin user to …
> #2151 & #2223: Implement E2E tests for enhanced adapter deletion and Extend reset REST endpoint to remove users

- .github/dependabot.yml
- installer/cli/.env
- installer/cli/deploy/standalone/backend/docker-compose.yml
- installer/cli/deploy/standalone/extensions-all-jvm/docker-compose.yml
- installer/cli/deploy/standalone/prometheus-alertmanager/alertmanager.yml
- installer/cli/deploy/standalone/prometheus-alertmanager/docker-compose.dev.yml
- installer/cli/deploy/standalone/prometheus-alertmanager/docker-compose.yml
- installer/cli/deploy/standalone/prometheus/docker-compose.dev.yml
- installer/cli/deploy/standalone/prometheus/docker-compose.yml
- installer/cli/deploy/standalone/prometheus/prometheus.yml
- installer/cli/environments/full-monitoring
- installer/cli/environments/lite-monitoring
With #1950 StreamPipes has capabilities to expose Prometheus metrics and with #1978 our Helm chart allows us to easily configure them.
This PR introduces support for the monitoring stack for the CLI as well.
Therefore, we introduce two new environments (`full-monitoring` and `lite-monitoring`) that extend the corresponding existing ones by the monitoring stack.
I'm planning to write a blogpost on how to setup all together and utilize the monitoring stack.
> extend CLI by monitoring stack

- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/helpers/Labels.java
This PR removes the method `fromResources` of the `Labels` class that has been marked for deprecated since `0.90.0`.
The following methods have been deprecated since `0.90.0` and are now removed:
- Label fromResources(String resourceIdentifier, String resourceName)
This can be replaced by working with the `withLocales()` method of processing element builders.
> refactor: remove deprecated method `fromResources`

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/health/AdapterHealthCheck.java
Fix a bug which caused the `AdapterHealthCheck` to crash when unhealthy adapters were present.
> fix: update of metrics in AdapterHealthCheck

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/health/AdapterHealthCheck.java
- streampipes-connect-management/src/test/java/org/apache/streampipes/connect/management/health/AdapterHealthCheckTest.java
#2328 introduced a bug where monitoring metrics were not exposed anymore for running adapters due to a side effect of `getAdaptersToRecover()`.
This PR introduces a fix so that metrics are exposed again for all adapters running and makes metric emitting more robust. However, parts of the introduced changes are only to be seen as a workaround.
> fix: orchestrate adapter health check such that monitoring of adapters works as expected

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/resources/org.apache.streampipes.connect.iiot.protocol.stream.httpserver/documentation.md
Inspired by #2299
Extend the adapter documentation.
> Update HTTP Server adapter documentation.md

- streampipes-extensions-management/src/main/java/org/apache/streampipes/extensions/management/locales/LabelGenerator.java
- streampipes-extensions-management/src/test/java/org/apache/streampipes/extensions/management/locales/LabelGeneratorTest.java
- streampipes-rest-extensions/src/main/java/org/apache/streampipes/rest/extensions/html/page/WelcomePageGenerator.java
Fixes #2353.
The two API methods `.getElementTitle` & `.getElementDescription` of the `LabelGenerator` class have been provided with a check if the files exist.
> fix(#2353): Add exception with detailed description for missing resources

- streampipes-client-python/Makefile
- streampipes-client-python/streampipes/endpoint/endpoint.py
- streampipes-client-python/streampipes/model/resource/version.py
- streampipes-client-python/tests/client/test_endpoint.py
- streampipes-client-python/tests/client/test_versions.py
Fix #2329 
This PR fixes the bug reported in #2329 which was caused by trailing slashes are no longer allowed since #2276.
In addition, the Python client is now able to connect to StreamPipes instances started only in development mode.
> fix(#2329): python client throws exception on connection

- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineResource.java
- ui/projects/streampipes/platform-services/src/lib/apis/pipeline.service.ts
- ui/src/app/editor/services/editor.service.ts
- Renames pipeline validation methods for clarity.
- Transfers pipeline API calls from the editor service to the dedicated pipeline service.
> feat(#2379): Move pipeline rest calls to pipeline service

- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/function/StreamPipesFunction.java
> fix(#2462): Use unique stream identifier for functions

- streampipes-mail/src/main/java/org/apache/streampipes/mail/template/generation/MailTemplateBuilder.java
When building the email template, make sure that placeholders are present before they are accessed.
> fix(#2461): Check for available placeholders when sending email

- ui/src/app/core-ui/object-permission-dialog/object-permission-dialog.component.html
- ui/src/app/core-ui/object-permission-dialog/object-permission-dialog.component.ts
> fix(#2493): Trigger filter when deselecting users

- streampipes-extensions/streampipes-connectors-opcua/src/test/java/org/apache/streampipes/extensions/connectors/opcua/adapter/OpcUaAdapterMigrationTest.java
- streampipes-extensions/streampipes-connectors-opcua/src/test/java/org/apache/streampipes/extensions/connectors/opcua/adapter/config/OpcUaAdapterVersionedConfig.java
Update to PR 2443 based on the discussion there
https://github.com/apache/streampipes/pull/2443
> #2144 Enhance Static Properties by UI validation V2 update

- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/NotificationsExtensionModuleExport.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/migrations/INotificationDataSinkMigrator.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/migrations/OneSignalSinkMigrationV1.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/migrations/SlackNotificationSinkMigrationV1.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/migrations/TelegramSinkMigrationV1.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/onesignal/OneSignalSink.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/slack/SlackNotificationSink.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/main/java/org/apache/streampipes/sinks/notifications/jvm/telegram/TelegramSink.java
- streampipes-extensions/streampipes-sinks-notifications-jvm/src/test/java/org/apache/streampipes/sinks/notifications/jvm/migrations/INotificationDataSinkMigratorTest.java
- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/StreamPipesNotificationSink.java
Purpose
For the following sinks: OneSignalSink, SlackSink, TelegramSink
Refactored to extend StreamPipesNotificationSink interface
Implemented migrations with the use of a common interface INotificationDataSinkMigrator
Added a unit test for INotificationDataSinkMigrator
Remarks
> 2312 Extend Notification sinks by silent period

- docker-compose.yml
- ui/Dockerfile
- ui/docker-entrypoint.sh
Fix Nginx startup problems because of missing configuration in case of a auto generated configuration.
Copy the missing template file to the correct location from a second locaton (/etc/opt/nginx/)
Could be removed in future versions.
PR introduces a breaking change: no
PR introduces a deprecation: no
fixes  #2473
> [#2473] Nginx configuration migraton to version 0.93.0+

- streampipes-client-python/streampipes/endpoint/endpoint.py
- streampipes-client-python/streampipes/functions/function_handler.py
- streampipes-client-python/streampipes/model/resource/data_stream.py
As for now, a function always creates a new data stream entity at the backend when starting a Python function with an output stream. This is not how it should behave because this prevents one from restarting a Python-based function.
With this PR, the identifier of the function is deterministically created and therefore reusable. If the data stream already exists, an info statement is logged and the function uses the existing stream.
The identification of a stream is based on its name. As long as one provides a consistent name for a data stream, the same stream will be used.
> fix(#2551): prevent Python functions from creating multiple output streams 

- streampipes-model/src/main/java/org/apache/streampipes/model/staticproperty/RemoteOneOfStaticProperty.java
- streampipes-model/src/main/java/org/apache/streampipes/model/staticproperty/StaticProperty.java
- ui/projects/streampipes/platform-services/src/lib/model/gen/streampipes-model.ts
- ui/src/app/core-ui/static-properties/input.validator.ts
- ui/src/app/core-ui/static-properties/static-free-input/static-free-input.component.html
- ui/src/app/core-ui/static-properties/static-free-input/static-free-input.component.ts
Allow to mark free text static properties as `optional` so that fields in the adapter and pipeline element configuration panels can be left empty if the `optional` flag is set.
We had a field `valueRequired` in the model definition which I have removed since it wasn't used anywhere and defaulted to false, although we currently regard all static properties as required.
> feat(#232): Support optional free text properties

- streampipes-commons/src/test/java/org/apache/streampipes/commons/file/FileHasherTest.java
- streampipes-data-export/src/main/java/org/apache/streampipes/export/generator/ExportPackageGenerator.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/utils/FileProtocolUtils.java
- streampipes-model/src/main/java/org/apache/streampipes/model/file/FileMetadata.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/file/FileManager.java
- streampipes-pipeline-management/src/test/java/org/apache/streampipes/manager/file/TestFileManager.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/ResetManagement.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/AssetDashboardResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/PipelineElementFile.java
> refactor(#2708): Make all methods of FileManager none static

- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/matching/v2/pipeline/CheckCompletedVisitor.java
Using mqtt Adapter, when there is a timestamp field in the data, the original timestamp field is not deleted. New timestamp added. Then checked the Persist events option, and an error occurred when saving.
no
no
> Fix：CheckCompletedVisitor outOfBounds

- streampipes-extensions/streampipes-processors-filters-jvm/src/test/java/org/apache/streampipes/processors/filters/jvm/processor/booleanfilter/TestBooleanFilterProcessor.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/test/java/org/apache/streampipes/processors/filters/jvm/processor/compose/TestComposeProcessor.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/test/java/org/apache/streampipes/processors/filters/jvm/processor/merge/TestMergeByTimeProcessor.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/test/java/org/apache/streampipes/processors/filters/jvm/processor/numericalfilter/NumericalFilterProcessorTest.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/test/java/org/apache/streampipes/processors/filters/jvm/processor/numericalfilter/ProcessingElementTestExecutor.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/test/java/org/apache/streampipes/processors/filters/jvm/processor/sdt/TestSwingingDoorTrendingFilterProcessor.java
- streampipes-extensions/streampipes-processors-filters-jvm/src/test/java/org/apache/streampipes/processors/filters/jvm/processor/textfilter/TestTextFilterProcessor.java
Added a couple of features to the test executor.
1. Option to provide custom configuration. TestComposeProcessor required to set output strategies and TestMergeByTimeProcessor required to set output key selectors.
2. Mocked mockParams.getModel(). Required for processors of type StreamPipesDataProcessor, which generate their own extractor based on the graph provided
3. Updated event creation to detect the prefix in the map keys and parse it properly
Refactored all tests in streampipes-processors-filters-jvm to use the executor
> test(#2374): provide a framework to easily unit test processing elements

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/oi4/Oi4Adapter.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/oi4/model/DataSetMessage.java
Adapt OI4 adapter such that it is able to process multiple sensor measurements collected in one event.
> fix: OI4 adapter can only read one sensor measurement per event

- installer/cli/deploy/standalone/iotdb/docker-compose.dev.yml
- installer/cli/deploy/standalone/iotdb/docker-compose.yml
Update docker-compose file based on https://iotdb.apache.org/UserGuide/latest/Deployment-and-Maintenance/Docker-Install.html#have-a-try
> chore: update docker-compose of IoTDB

- streampipes-ts-store-iotdb/src/main/java/org/apache/streampipes/ts/store/iotdb/IotDbMeasurementRecord.java
- streampipes-ts-store-iotdb/src/main/java/org/apache/streampipes/ts/store/iotdb/IotDbPropertyConverter.java
- streampipes-ts-store-iotdb/src/test/java/org/apache/streampipes/ts/store/iotdb/IotDbPropertyConverterTest.java
This PR introduces a property converter for the IoTDB, which extracts the required information from an event property to persist it in the IoTDB.
> [!IMPORTANT]  
> The current implementation does not apply a special handling for dimension properties.
> We need to further discuss if and how we want to support this having IoTDB as time series backend
> feat: add property converter for IoTDB

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/GuessManagement.java
- streampipes-extensions-api/src/main/java/org/apache/streampipes/extensions/api/connect/exception/WorkerAdapterException.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/oi4/Oi4Adapter.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/oi4/model/DataSetMessage.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/java/org/apache/streampipes/connect/iiot/adapters/oi4/serializer/PayloadDeserializer.java
- streampipes-extensions/streampipes-connect-adapters-iiot/src/test/java/org/apache/streampipes/connect/iiot/adapters/oi4/model/DataSetMessageDeserializationTest.java
- streampipes-extensions/streampipes-connectors-mqtt/src/main/java/org/apache/streampipes/extensions/connectors/mqtt/adapter/MqttProtocol.java
- streampipes-extensions/streampipes-connectors-mqtt/src/main/java/org/apache/streampipes/extensions/connectors/mqtt/shared/MqttConsumer.java
- streampipes-rest-extensions/src/main/java/org/apache/streampipes/rest/extensions/connect/GuessResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/connect/GuessResource.java
- streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/StreamPipesExtensionsServiceBase.java
Add some improvements to the MQTT and OI4 adapters:
* Error messages don't get lost and are sent to the UI
* Avoid infinite loops in case schema retrieval fails
* Support two different formats as OI4 payload
> fix: Add error handling to OI4 and MQTT adapters

- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/template/PipelineElementTemplateVisitor.java
When the adapter uses templates, the Secret Static Property value should be encrypted
Now after importing the template, it becomes an object
`{
"@class" : "org.apache.streampipes.model.staticproperty.SecretStaticProperty",
"valueRequired" : false,
"staticPropertyType" : "SecretStaticProperty",
"index" : 1,
"label" : "Password",
"description" : "The password for the InfluxDB Server",
"internalName" : "db_password",
"predefined" : false,
"value" : "{encrypted=false, value=test}",
"encrypted" : true
} `
no
no
> fix PipelineElementTemplateVisitor SecretStaticProperty value

- streampipes-client-python/streampipes/client/credential_provider.py
- streampipes-client-python/streampipes/model/resource/function_definition.py
While building the StreamPipes client python documentation site locally, I noticed several warnings being logged in the console. I made adjustments to the relevant sections of the code to eliminate these warnings.
I have also reviewed the issues tagged with `documentation` or `website` and found no existing issues related to these warnings, ensuring that this PR does not duplicate any previously reported issues.
Detailed console output:
```
INFO    -  Doc file 'reference/client/credential_provider.md' contains an unrecognized relative link '../../../', it was
left as is. Did you mean '../../index.md'?
WARNING -  griffe: streampipes\model\resource\function_definition.py:65: No types or annotations for parameters
['consumed_streams']
WARNING -  griffe: …
```
> fix: Fix client python docs site build warning

- streampipes-client-python/streampipes/endpoint/api/version.py
- streampipes-client-python/tests/client/test_versions.py
The `get` method in the `VersionEndpoint` class internally hard-codes the `identifier` parameter to an empty string `""`, which can be misleading.
When users call the `get` method and pass any identifier, the method always uses an empty string as the identifier. This may lead users to mistakenly believe that their incorrect get request has successfully returned the correct result.
With this fix, when users provide an invalid identifier, the method will now throw an appropriate error, ensuring that users can promptly detect the issue and make corrections.
Additionally, I also added tests to ensure that the new error handling behaves as expected.
no
no
> fix: Replace hard-coded identifier in VersionEndpoint.get() method

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/GuessManagement.java
The encrypted secretValue should be decrypted when used
no
no
> guessSchema the encrypted secretValue should be decrypted when used

- streampipes-extensions/streampipes-connect-adapters-iiot/src/main/resources/org.apache.streampipes.connect.iiot.adapters.simulator.machine/documentation.md
> docs: document machine data simulator properly

- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/convert/ToTransformedSchemaConverter.java
- streampipes-model/src/main/java/org/apache/streampipes/model/connect/rules/value/AddTimestampRuleDescription.java
- ui/projects/streampipes/platform-services/src/lib/model/gen/streampipes-model.ts
- ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/sp-exception-message.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/sp-exception-message/sp-exception-message.component.scss
- ui/src/app/connect/services/transformation-rule.service.ts
> fix(#2830): Data adapter losing dimension selection

- streampipes-connect-shared/src/main/java/org/apache/streampipes/connect/shared/preprocessing/SupportsNestedTransformationRule.java
- streampipes-connect-shared/src/test/java/org/apache/streampipes/connect/shared/preprocessing/transform/schema/DeleteTransformationRuleTest.java
- ui/cypress/fixtures/connect/deleteTransformationRule/nestedInput.json
- ui/cypress/support/utils/ConnectEventSchemaUtils.ts
- ui/cypress/tests/adapter/rules/deleteTransformationRule.spec.ts
> fix(#2894): Fix flaky e2e test

- streampipes-client-python/tests/client/test_client.py
Replace deprecated `assertDictContainsSubset` in python client unit tests.
Part of the console output `warnings summary` is:
```
tests/client/test_client.py::TestStreamPipesClient::test_client_create
C:\Users\...\streampipes-dev\streampipes-client-python\tests\client\test_client.py:74: DeprecationWarning: assertDictContainsSubset is deprecated
self.assertDictContainsSubset(
tests/client/test_client.py::TestStreamPipesClient::test_client_init
C:\Users\...\streampipes-dev\streampipes-client-python\tests\client\test_client.py:47: DeprecationWarning: assertDictContainsSubset is deprecated
self.assertDictContainsSubset(
```
no
no
> fix: Replace deprecated assertDictContainsSubset in python client unit tests

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- installer/cli/README.md
- installer/compose/README.md
- installer/k8s/README.md
- streampipes-client-python/docs/getting-started/developing.md
- streampipes-client-python/docs/getting-started/first-steps.md
Inspired by the recent pull request, I wrote a simple python script dedicated to identifying broken links in project documentation. I also completed attempts to fix the broken links.
In addition, I noticed that there are extra spaces at the end of some lines. Maybe we can add markdown lint CI to standardize and improve quality? If that feature is acceptable, I'd be willing to do that part and use it to familiarize with the docs.
no
no
> fix: update broken links

- streampipes-client-python/streampipes/endpoint/api/data_lake_measure.py
- streampipes-client-python/streampipes/model/resource/query_result.py
- streampipes-client-python/tests/client/test_data_lake_series.py
Add python client QueryResult model field definitions.
Also I fixed the docstring of `DataLakeMeasureEndpoint.get()`, in the current version its return type is not `DataLakeMeasures` in the docstring but `<class 'streampipes.model.resource.query_ result.QueryResult'>`
no
no
> Fix: Add python client QueryResult model field definitions

- ui/cypress/support/utils/connect/ConnectBtns.ts
- ui/cypress/support/utils/connect/ConnectEventSchemaUtils.ts
- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/cypress/support/utils/datalake/DataLakeBtns.ts
- ui/cypress/support/utils/datalake/DataLakeUtils.ts
- ui/cypress/tests/adapter/editAdapter.smoke.spec.ts
- ui/cypress/tests/adapter/editAdapterSettingsAndPipeline.spec.ts
- ui/cypress/tests/adapter/editAdapterValuesAndFields.spec.ts
- ui/cypress/tests/adapter/rules/deleteTransformationRule.spec.ts
- ui/cypress/tests/adapter/rules/schemaRules.smoke.spec.ts
- ui/cypress/tests/adapter/rules/streamRules.spec.ts
- ui/cypress/tests/adapter/rules/valueRules.ts
- ui/src/app/configuration/datalake-configuration/datalake-configuration.component.html
- ui/src/app/connect/dialog/edit-event-property/components/edit-schema-transformation/edit-schema-transformation.component.html
- ui/src/app/connect/dialog/edit-event-property/components/edit-schema-transformation/edit-schema-transformation.component.scss
- ui/src/app/connect/dialog/edit-event-property/components/edit-schema-transformation/edit-schema-transformation.component.ts
- ui/src/app/connect/dialog/edit-event-property/components/edit-value-transformation/edit-correction-value/edit-correction-value.component.scss
- ui/src/app/connect/dialog/edit-event-property/edit-event-property.component.scss
This PR adds a warning message to the edit event property dialog if the adapter is in edit mode, see #2954.
Further it contains some minor improvements in the cypress testing library.
> fix(#2954): data type change in adapter causes data storage failure in influxdb

- installer/cli/bin/common
Hey thanks for providing this awesome piece of software.
While installing with the `cli-installer` I stumbled upon a legacy usage of `docker-compose` which broke on my system. 
https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2
This tiny pr fixes the issue.
> chore: cli installer switch to compose v2 api

- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/template/PipelineElementTemplateVisitor.java
- streampipes-pipeline-management/src/test/java/org/apache/streampipes/manager/template/PipelineElementTemplateVisitorTest.java
This functionality is needed to refactor the unit tests for the `StringToStateProcessor` class. The processor requires a `requiredPropertyWithNaryMapping` input from the user. The unit test framework for processing elements uses the pipeline element template functionality.
Is it possible that this new functionality of this PR will break the templates in the UI? Because we also do not have the original event schema.
> feat: Implement visit for mapping property nary in pipeline element templates

- streampipes-extensions/streampipes-processors-transformation-jvm/pom.xml
- streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/processor/stringoperator/state/StringToStateProcessor.java
- streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/stringoperator/counter/TestStringCounterProcessor.java
- streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/stringoperator/state/TestStringToStateProcessor.java
- streampipes-test-utils-executors/src/main/java/org/apache/streampipes/test/executors/ProcessingElementTestExecutor.java
- streampipes-test-utils-executors/src/main/java/org/apache/streampipes/test/executors/StreamPrefix.java
- streampipes-test-utils-executors/src/main/java/org/apache/streampipes/test/executors/TestConfigurationBuilder.java
- streampipes-test-utils-executors/src/test/java/org/apache/streampipes/test/executors/StreamPrefixTest.java
**Important:** Before this branch is merged to dev, the PR #3031 should be merged.
> refactor(#2779): Fix the test for TestStringToStateProcessor

- streampipes-model-client/src/main/java/org/apache/streampipes/model/client/user/PermissionBuilder.java
- streampipes-model/src/main/java/org/apache/streampipes/model/dashboard/DashboardModel.java
- streampipes-model/src/main/java/org/apache/streampipes/model/datalake/DataExplorerWidgetModel.java
- streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/AbstractCRUDResourceManager.java
- streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/DashboardResourceManager.java
- streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/DataExplorerWidgetResourceManager.java
- streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/PermissionResourceManager.java
- streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/SpResourceManager.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/dashboard/AbstractDashboardResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/dashboard/Dashboard.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/datalake/DataLakeDashboardResource.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/datalake/DataLakeWidgetResource.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/AvailableMigrations.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v970/DataExplorerDataViewMigration.java
- ui/projects/streampipes/platform-services/src/lib/apis/data-view-data-explorer.service.ts
- ui/src/app/data-explorer/components/overview/data-explorer-dashboard-overview/data-explorer-dashboard-overview.component.ts
- ui/src/app/data-explorer/components/overview/data-explorer-data-view-overview/data-explorer-data-view-overview.component.html
- ui/src/app/data-explorer/components/overview/data-explorer-data-view-overview/data-explorer-data-view-overview.component.ts
- ui/src/app/data-explorer/services/data-explorer-dashboard.service.ts
- ui/src/app/data-explorer/services/time-selection.service.ts
Add a migration for data explorer dashboards and data views
* Let data views inherit existing dashboard permissions
* Migrate time settings
> feat(#3079): Add permission management to data views

- ui/cypress/support/utils/datalake/DataLakeBtns.ts
- ui/cypress/support/utils/datalake/DataLakeUtils.ts
- ui/cypress/tests/datalake/timeOrderDataView.spec.ts
- ui/cypress/tests/datalake/timeRangeSelectors.spec.ts
- ui/cypress/tests/datalake/widgets/timeSeriesSave.spec.ts
- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/order-selection-panel/order-selection-panel.component.html
This commit introduces a new E2E test for data ordering in the data view. It tests the functionality of ascending and descending orders and verifies that the data is displayed correctly. Moreover, a minor bugfix in the TimeRangeSelector has been made.
No
> test: Add time order test + minor changes

- ui/projects/streampipes/platform-services/src/lib/apis/datalake-rest.service.ts
- ui/src/app/data-explorer/components/dashboard/data-explorer-dashboard-panel.component.ts
- ui/src/app/data-explorer/components/widgets/base/base-data-explorer-widget.directive.ts
- ui/src/app/data-explorer/components/widgets/gauge/config/gauge-widget-config.component.html
- ui/src/app/data-explorer/components/widgets/gauge/config/gauge-widget-config.component.ts
- ui/src/app/data-explorer/components/widgets/gauge/gauge-renderer.service.ts
- ui/src/app/data-explorer/components/widgets/gauge/model/gauge-widget.model.ts
- ui/src/app/data-explorer/data-explorer.module.ts
- ui/src/app/data-explorer/registry/data-explorer-widget-registry.ts
> feat(#3090): Add gauge chart to data explorer

- streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/TimeSeriesStorageInflux.java
- streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/client/InfluxClientProvider.java
- streampipes-data-explorer-influx/src/test/java/org/apache/streampipes/dataexplorer/influx/TimeSeriesStorageInfluxTest.java
- streampipes-extensions/streampipes-connectors-influx/src/main/java/org/apache/streampipes/extensions/connectors/influx/adapter/InfluxDbClient.java
- streampipes-extensions/streampipes-connectors-influx/src/main/java/org/apache/streampipes/extensions/connectors/influx/shared/SharedInfluxClient.java
- streampipes-extensions/streampipes-connectors-influx/src/main/java/org/apache/streampipes/extensions/connectors/influx/sink/InfluxDbClient.java
- streampipes-extensions/streampipes-connectors-influx/src/main/java/org/apache/streampipes/extensions/connectors/influx/sink/InfluxDbSink.java
Closes #2354. Moved the common functionality to InfluxClientProvider. 
Tested pipelines locally with Data Lake and InfluxDB Data Sinks. For both data ends up in the InfluxDB with no errors.
> 2354 harmonize influx store and influx db client

- streampipes-service-core/pom.xml
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/AvailableMigrations.java
- streampipes-service-core/src/main/java/org/apache/streampipes/service/core/migrations/v970/RemoveNodesFromOpcUaAdaptersMigration.java
- streampipes-service-core/src/test/java/org/apache/streampipes/service/core/migrations/v970/RemoveNodesFromOpcUaAdaptersMigrationTest.java
This PR introduces a migration script to remove the `nodes` and `latestFetchedNodes` fields from adapter instances in CouchDB. These fields are unnecessary for the `RuntimeResolvableTreeInputStaticProperty`, and their removal is expected to enhance StreamPipes' performance.
> fix(#3191): Add migration to remove nodes fields from opc ua adapters

- streampipes-service-extensions/src/main/java/org/apache/streampipes/service/extensions/function/StreamPipesFunctionHandler.java
Fix a bug which caused an exception if an output data stream of a function is already present. This fix updates any existing output data stream when the function is started.
> fix: Properly update output streams in functions

- streampipes-extensions/streampipes-processors-transformation-jvm/src/main/java/org/apache/streampipes/processors/transformation/jvm/processor/transformtoboolean/TransformToBooleanProcessor.java
- streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/transformtoboolean/TransformToBooleanProcessorTest.java
Ensure that the property selector prefix is removed before adding the output field to the `TransformBooleanProcessor`.
> fix(#3237): Remove selector prefix from output event

- streampipes-extensions/streampipes-extensions-all-iiot/src/main/java/org/apache/streampipes/extensions/all/iiot/AllExtensionsIIoTInit.java
This PR adds the `@SpringBootApplication` annotation to the `AllExtensionsIIoTInit` class to align it with other classes extending `StreamPipesExtensionsServiceBase`. This ensures consistency and expected behavior across all extension classes.
> fix: Add spring boot to AllExtensionsIIoTInit

- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/OpcUaConnectorsModuleExport.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/adapter/OpcUaAdapter.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/config/OpcUaAdapterConfig.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/config/SharedUserConfiguration.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/config/SpOpcUaConfigExtractor.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/migration/OpcUaAdapterMigrationV2.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/java/org/apache/streampipes/extensions/connectors/opcua/migration/OpcUaAdapterMigrationV3.java
- streampipes-extensions/streampipes-connectors-opcua/src/main/resources/org.apache.streampipes.connect.iiot.adapters.opcua/strings.en
- streampipes-wrapper-standalone/src/main/java/org/apache/streampipes/wrapper/standalone/runtime/StandaloneEventProcessorRuntime.java
> feat(#3283): Allow incomplete events in OPC-UA adapter

- ui/cypress/fixtures/connect/compact/machineDataSimulator.yml
- ui/cypress/support/builder/CompactAdapterBuilder.ts
- ui/cypress/support/utils/CompactUtils.ts
- ui/cypress/support/utils/GeneralUtils.ts
- ui/cypress/support/utils/ProcessingElementTestUtils.ts
- ui/cypress/support/utils/ThirdPartyIntegrationUtils.ts
- ui/cypress/support/utils/connect/CompactAdapterUtils.ts
- ui/cypress/support/utils/connect/ConnectBtns.ts
- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/cypress/support/utils/pipeline/PipelineBtns.ts
- ui/cypress/support/utils/pipeline/PipelineUtils.ts
- ui/cypress/tests/connect/compact/addCompactAdapter.ts
- ui/cypress/tests/connect/compact/uiConfiguration.ts
- ui/cypress/tests/connect/deleteAdapterWithMultipleUsers.smoke.spec.ts
- ui/cypress/tests/connect/editAdapterSettingsAndPipeline.spec.ts
- ui/cypress/tests/connect/persistInDataLake.smoke.spec.ts
- ui/cypress/tests/datalake/configuration.smoke.spec.ts
- ui/cypress/tests/experimental/restartStreamPipes/restartStreamPipes1.ts
- ui/cypress/tests/experimental/testJvmArchetype/testJvmArchetype.ts
- ui/cypress/tests/pipeline/pipelineTest.smoke.spec.ts
- ui/cypress/tests/pipeline/updatePipelineTest.smoke.spec.ts
- ui/cypress/tests/pipelineElement/PipelineElementDocumentation.spec.ts
- ui/cypress/tests/pipelineElementConfigurationTemplate/pipelineElementConfigurationTemplate.ts
- ui/cypress/tests/userManagement/testGroupManagement.spec.ts
- ui/cypress/tests/userManagement/testUserRolePipeline.spec.ts
- ui/projects/streampipes/shared-ui/src/lib/components/basic-nav-tabs/basic-nav-tabs.component.html
- ui/src/app/connect/components/adapter-configuration/start-adapter-configuration/start-adapter-configuration.component.html
- ui/src/app/core-ui/configuration-code-panel/configuration-code-panel.component.html
This PR introduces a Cypress test to ensure that the code editor for compact adapters is correctly displayed in the user interface. The code editor is utilized in two distinct areas of the application:
1. **Adapter Creation:** During the process of creating a new adapter.
2. **Adapter Details View:** Within the detailed view of an existing adapter.
The test verifies that the code editor appears as expected in both scenarios.
> feat(#3298): Add test to validate code editor for compact adapters in UI

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/management/AdapterMasterManagement.java
- streampipes-connect-management/src/test/java/org/apache/streampipes/connect/management/management/AdapterMasterManagementTest.java
- streampipes-resource-management/src/main/java/org/apache/streampipes/resource/management/AdapterResourceManager.java
- streampipes-resource-management/src/test/java/org/apache/streampipes/resource/management/AdapterResourceManagerTest.java
- streampipes-rest/src/main/java/org/apache/streampipes/rest/impl/connect/CompactAdapterResource.java
- ui/cypress/support/utils/connect/CompactAdapterUtils.ts
- ui/cypress/support/utils/connect/ConnectUtils.ts
- ui/cypress/tests/connect/compact/addCompactAdapter.ts
> feat(#3298): Return Conflict Status Code for Duplicate Adapter ID

- streampipes-connect-management/src/main/java/org/apache/streampipes/connect/management/compact/PersistPipelineHandler.java
- streampipes-model/src/main/java/org/apache/streampipes/model/output/AppendOutputStrategy.java
- streampipes-model/src/main/java/org/apache/streampipes/model/output/CustomOutputStrategy.java
- streampipes-model/src/main/java/org/apache/streampipes/model/output/FixedOutputStrategy.java
- streampipes-model/src/main/java/org/apache/streampipes/model/output/KeepOutputStrategy.java
- streampipes-model/src/main/java/org/apache/streampipes/model/output/ListOutputStrategy.java
- streampipes-model/src/main/java/org/apache/streampipes/model/output/OutputStrategy.java
- streampipes-model/src/main/java/org/apache/streampipes/model/output/OutputStrategyVisitor.java
- streampipes-model/src/main/java/org/apache/streampipes/model/output/TransformOutputStrategy.java
- streampipes-model/src/main/java/org/apache/streampipes/model/output/UserDefinedOutputStrategy.java
- streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/compact/CompactPipelineElement.java
- streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/compact/OutputConfiguration.java
- streampipes-model/src/main/java/org/apache/streampipes/model/pipeline/compact/UserDefinedOutput.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/CompactPipelineConverter.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/DataProcessorPipelineElementGenerator.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/pipeline/compact/generation/OutputStrategyGenerator.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/template/compact/CompactPipelineTemplateManagement.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/template/instances/PersistDataLakePipelineTemplate.java
- ui/projects/streampipes/platform-services/src/lib/model/gen/streampipes-model.ts
- ui/src/app/connect/dialog/adapter-started/adapter-started-dialog.component.ts
- ui/src/app/core-ui/help/help.component.html
- ui/src/app/core-ui/help/help.component.ts
Support custom and user-defined output strategies in the pipeline-as-code model.
Example: 
```
id: test
name: Test
description: ""
pipelineElements:
- type: stream
ref: 0_6fSh
id: sp:spdatastream:Kmneup
- type: processor
ref: 1_ScpA
id: org.apache.streampipes.processors.filters.jvm.project
connectedTo:
- 0_6fSh
configuration: []
output:
keep:
- s0::timestamp
- s0::volume_flow
- type: processor
ref: 2_QGAv
id: org.apache.streampipes.processors.enricher.jvm.jseval
connectedTo:
- 1_ScpA
configuration:
- jsFunction: >-
function process(event) {
// do processing here.
// return processed event.
// Type 'event' and press Ctrl+Space to see available fields.
// Example: 
return {timestamp: event.timestamp, tempInCelsius: (event.tempInKelvin - 273.15)};
}
output:
userDefined:
- fieldName: …
```
> Support output strategies in pipeline code

- ui/src/app/connect/components/adapter-code-panel/adapter-code-panel.component.html
- ui/src/app/core-ui/configuration-code-panel/configuration-code-panel.component.html
- ui/src/app/core-ui/configuration-code-panel/configuration-code-panel.component.scss
- ui/src/app/core-ui/configuration-code-panel/configuration-code-panel.component.ts
- ui/src/app/core-ui/core-ui.module.ts
- ui/src/app/core-ui/topics/topics.component.html
- ui/src/app/core-ui/topics/topics.component.scss
- ui/src/app/core-ui/topics/topics.component.ts
- ui/src/app/editor/components/pipeline/pipeline.component.html
- ui/src/app/editor/components/pipeline/pipeline.component.scss
- ui/src/app/editor/components/pipeline/pipeline.component.ts
- ui/src/app/editor/dialog/save-pipeline/save-pipeline-settings/save-pipeline-settings.component.html
- ui/src/app/editor/services/editor.service.ts
- ui/src/app/pipeline-details/dialogs/pipeline-code/pipeline-code-dialog.component.html
- ui/src/app/pipeline-details/pipeline-details.module.ts
This change introduces the option to view the input and output topics of elements in the pipeline editor’s view mode. For each element, a "View Topics" button is added, which opens a dialog displaying all topics associated with that element. The dialog window also includes a "Code" tab, which will allow code display functionality in the future. Additionally, the topics table in the dialog includes a copy button for copying the content to the user's clipboard. This button is also added to the "View Pipeline as Code" dialog window as option to copy the code to the user's clipboard.
> Add topics information to pipeline editor in view mode

- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/refresh-interval-settings/refresh-interval-settings.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/refresh-interval-settings/refresh-interval-settings.component.ts
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.ts
- ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
- ui/src/app/data-explorer/components/dashboard/dashboard-toolbar/dashboard-toolbar.component.html
- ui/src/app/data-explorer/components/dashboard/dashboard-toolbar/dashboard-toolbar.component.ts
- ui/src/app/data-explorer/components/dashboard/data-explorer-dashboard-panel.component.html
- ui/src/app/data-explorer/components/dashboard/data-explorer-dashboard-panel.component.ts
- ui/src/app/data-explorer/data-explorer.module.ts
This moves the refresh-interval component from the dashboard toolbar to the time selector menu.
> Move refresh interval option to time selector menu component

- streampipes-data-explorer-influx/src/main/java/org/apache/streampipes/dataexplorer/influx/client/InfluxClientUtils.java
Reuse the Influx client's HTTP connection pool for better performance.
> fix: Reuse Influx connection pool

- ui/cypress/support/utils/GeneralUtils.ts
- ui/cypress/support/utils/UserUtils.ts
- ui/cypress/support/utils/navigation/NavigationUtils.ts
- ui/cypress/tests/userManagement/testGroupManagement.spec.ts
- ui/cypress/tests/userManagement/testUserRoleConnect.spec.ts
- ui/cypress/tests/userManagement/testUserRolePipeline.spec.ts
- ui/cypress/tests/userManagement/testVariousUserRoles.smoke.spec.ts
- ui/package-lock.json
- ui/src/app/core/components/iconbar/iconbar.component.html
This PR introduces the following improvements:
1. **Refactoring the Icon Bar Component**:
- Migrated the icon bar component to leverage Angular's control flow syntax (`@for` and `@if`) for enhanced readability and maintainability.
- Updated the `iconbar.component.html` to include dynamic `data-cy` attributes for improved test targeting.
2. **Enhanced End-to-End Tests**:
- Replaced the generic `validateAmountOfNavigationIcons` method with specific assertions for individual navigation icons (e.g., `pipelinesIsDisplayed`).
- Introduced a new `NavigationUtils` utility to manage navigation icon assertions in a modular and reusable way.
> refactor(#3398): Add control flow syntax to icon bar and improved e2e tests

- streampipes-model/src/main/java/org/apache/streampipes/model/configuration/DefaultSpCoreConfiguration.java
- streampipes-pipeline-management/src/main/java/org/apache/streampipes/manager/setup/StreamPipesEnvChecker.java
Update asset and file directories used by the core service when the SP_CORE_ASSET_BASE_DIR variable is set.
> feat: Update asset and file directories upon restart

- ui/cypress/support/utils/UserUtils.ts
- ui/cypress/support/utils/configuration/ConfigurationBtns.ts
- ui/cypress/support/utils/configuration/ConfigurationUtils.ts
- ui/cypress/tests/apiDocumentation/apiDocumentation.smoke.spec.ts
- ui/cypress/tests/configuration/labels/general.spec.ts
- ui/cypress/tests/configuration/labels/labels.spec.ts
- ui/cypress/tests/login/login.smoke.spec.ts
> Minor code improvements two e2e tests

- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/refresh-interval-settings/refresh-interval-settings.component.ts
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-range-selector.component.ts
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/custom-time-range-selection/custom-time-range-selection.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/custom-time-range-selection/custom-time-range-selection.component.ts
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.html
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.scss
- ui/projects/streampipes/shared-ui/src/lib/components/time-selector/time-selector-menu/time-selector-menu.component.ts
- ui/projects/streampipes/shared-ui/src/lib/services/time-selection.service.ts
- ui/projects/streampipes/shared-ui/src/lib/shared-ui.module.ts
- ui/projects/streampipes/shared-ui/src/public-api.ts
- ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.html
- ui/src/app/data-explorer/components/widget/data-explorer-dashboard-widget.component.ts
This addresses the refresh interval settings for the widget time settings on the dashboard. It introduces the ability to refresh the data, with each widget having its own time settings. Moreover, the widget time settings have been fixed and should now display the correct data. Additionally, minor improvements were made to the time selector menu, including displaying the selected quick link in bold and making small name changes for better clarity.
> fix: refresh interval settings for widgets in dashboard

- ui/src/app/data-explorer/components/data-view/data-view-designer-panel/data-settings/filter-selection-panel/filter-selection-panel-row/escape-number-filter.service.ts
This is a minor PR that fixes a TypeError in escape-number-filter.service.ts caused by accessing a property on null or undefined.
> fix: Fix undefined error in escape-number-filter.service.ts

- streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/s7/config/ConfigurationParser.java
- streampipes-extensions/streampipes-connectors-plc/src/test/java/org/apache/streampipes/extensions/connectors/plc/adapter/s7/config/ConfigurationParserTest.java
> fix(#3465): Add support for variable string length in PLC4X adapters

- streampipes-extensions-api/src/main/java/org/apache/streampipes/extensions/api/extractor/IParameterExtractor.java
- streampipes-sdk/src/main/java/org/apache/streampipes/sdk/extractor/AbstractParameterExtractor.java
> refactor(#3139): Remove deprecated IParameterExtractor.selectedTreeNodesInternalNames

- ui/Dockerfile
- ui/docker-entrypoint.sh
Fixes #3446
Remove obsolete migration code.
> [WIP][#3446] Remove nginx default.conf SP 0.93.0 -> 0.95.0 migration code
